/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateTradingAccountCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTradingAccountCredentialRequest{}

// CreateTradingAccountCredentialRequest struct for CreateTradingAccountCredentialRequest
type CreateTradingAccountCredentialRequest struct {
	Venue Venue `json:"venue"`
	// Nickname of the credential
	Nickname *string `json:"nickname,omitempty"`
	CredentialType CredentialType `json:"credentialType"`
	ApiKey *string `json:"apiKey,omitempty"`
	ApiSecret *string `json:"apiSecret,omitempty"`
	ApiPassphrase *string `json:"apiPassphrase,omitempty"`
}

type _CreateTradingAccountCredentialRequest CreateTradingAccountCredentialRequest

// NewCreateTradingAccountCredentialRequest instantiates a new CreateTradingAccountCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTradingAccountCredentialRequest(venue Venue, credentialType CredentialType) *CreateTradingAccountCredentialRequest {
	this := CreateTradingAccountCredentialRequest{}
	this.Venue = venue
	this.CredentialType = credentialType
	return &this
}

// NewCreateTradingAccountCredentialRequestWithDefaults instantiates a new CreateTradingAccountCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTradingAccountCredentialRequestWithDefaults() *CreateTradingAccountCredentialRequest {
	this := CreateTradingAccountCredentialRequest{}
	return &this
}

// GetVenue returns the Venue field value
func (o *CreateTradingAccountCredentialRequest) GetVenue() Venue {
	if o == nil {
		var ret Venue
		return ret
	}

	return o.Venue
}

// GetVenueOk returns a tuple with the Venue field value
// and a boolean to check if the value has been set.
func (o *CreateTradingAccountCredentialRequest) GetVenueOk() (*Venue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Venue, true
}

// SetVenue sets field value
func (o *CreateTradingAccountCredentialRequest) SetVenue(v Venue) {
	o.Venue = v
}

// GetNickname returns the Nickname field value if set, zero value otherwise.
func (o *CreateTradingAccountCredentialRequest) GetNickname() string {
	if o == nil || IsNil(o.Nickname) {
		var ret string
		return ret
	}
	return *o.Nickname
}

// GetNicknameOk returns a tuple with the Nickname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTradingAccountCredentialRequest) GetNicknameOk() (*string, bool) {
	if o == nil || IsNil(o.Nickname) {
		return nil, false
	}
	return o.Nickname, true
}

// HasNickname returns a boolean if a field has been set.
func (o *CreateTradingAccountCredentialRequest) HasNickname() bool {
	if o != nil && !IsNil(o.Nickname) {
		return true
	}

	return false
}

// SetNickname gets a reference to the given string and assigns it to the Nickname field.
func (o *CreateTradingAccountCredentialRequest) SetNickname(v string) {
	o.Nickname = &v
}

// GetCredentialType returns the CredentialType field value
func (o *CreateTradingAccountCredentialRequest) GetCredentialType() CredentialType {
	if o == nil {
		var ret CredentialType
		return ret
	}

	return o.CredentialType
}

// GetCredentialTypeOk returns a tuple with the CredentialType field value
// and a boolean to check if the value has been set.
func (o *CreateTradingAccountCredentialRequest) GetCredentialTypeOk() (*CredentialType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialType, true
}

// SetCredentialType sets field value
func (o *CreateTradingAccountCredentialRequest) SetCredentialType(v CredentialType) {
	o.CredentialType = v
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise.
func (o *CreateTradingAccountCredentialRequest) GetApiKey() string {
	if o == nil || IsNil(o.ApiKey) {
		var ret string
		return ret
	}
	return *o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTradingAccountCredentialRequest) GetApiKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ApiKey) {
		return nil, false
	}
	return o.ApiKey, true
}

// HasApiKey returns a boolean if a field has been set.
func (o *CreateTradingAccountCredentialRequest) HasApiKey() bool {
	if o != nil && !IsNil(o.ApiKey) {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given string and assigns it to the ApiKey field.
func (o *CreateTradingAccountCredentialRequest) SetApiKey(v string) {
	o.ApiKey = &v
}

// GetApiSecret returns the ApiSecret field value if set, zero value otherwise.
func (o *CreateTradingAccountCredentialRequest) GetApiSecret() string {
	if o == nil || IsNil(o.ApiSecret) {
		var ret string
		return ret
	}
	return *o.ApiSecret
}

// GetApiSecretOk returns a tuple with the ApiSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTradingAccountCredentialRequest) GetApiSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ApiSecret) {
		return nil, false
	}
	return o.ApiSecret, true
}

// HasApiSecret returns a boolean if a field has been set.
func (o *CreateTradingAccountCredentialRequest) HasApiSecret() bool {
	if o != nil && !IsNil(o.ApiSecret) {
		return true
	}

	return false
}

// SetApiSecret gets a reference to the given string and assigns it to the ApiSecret field.
func (o *CreateTradingAccountCredentialRequest) SetApiSecret(v string) {
	o.ApiSecret = &v
}

// GetApiPassphrase returns the ApiPassphrase field value if set, zero value otherwise.
func (o *CreateTradingAccountCredentialRequest) GetApiPassphrase() string {
	if o == nil || IsNil(o.ApiPassphrase) {
		var ret string
		return ret
	}
	return *o.ApiPassphrase
}

// GetApiPassphraseOk returns a tuple with the ApiPassphrase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTradingAccountCredentialRequest) GetApiPassphraseOk() (*string, bool) {
	if o == nil || IsNil(o.ApiPassphrase) {
		return nil, false
	}
	return o.ApiPassphrase, true
}

// HasApiPassphrase returns a boolean if a field has been set.
func (o *CreateTradingAccountCredentialRequest) HasApiPassphrase() bool {
	if o != nil && !IsNil(o.ApiPassphrase) {
		return true
	}

	return false
}

// SetApiPassphrase gets a reference to the given string and assigns it to the ApiPassphrase field.
func (o *CreateTradingAccountCredentialRequest) SetApiPassphrase(v string) {
	o.ApiPassphrase = &v
}

func (o CreateTradingAccountCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTradingAccountCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["venue"] = o.Venue
	if !IsNil(o.Nickname) {
		toSerialize["nickname"] = o.Nickname
	}
	toSerialize["credentialType"] = o.CredentialType
	if !IsNil(o.ApiKey) {
		toSerialize["apiKey"] = o.ApiKey
	}
	if !IsNil(o.ApiSecret) {
		toSerialize["apiSecret"] = o.ApiSecret
	}
	if !IsNil(o.ApiPassphrase) {
		toSerialize["apiPassphrase"] = o.ApiPassphrase
	}
	return toSerialize, nil
}

func (o *CreateTradingAccountCredentialRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"venue",
		"credentialType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTradingAccountCredentialRequest := _CreateTradingAccountCredentialRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTradingAccountCredentialRequest)

	if err != nil {
		return err
	}

	*o = CreateTradingAccountCredentialRequest(varCreateTradingAccountCredentialRequest)

	return err
}

type NullableCreateTradingAccountCredentialRequest struct {
	value *CreateTradingAccountCredentialRequest
	isSet bool
}

func (v NullableCreateTradingAccountCredentialRequest) Get() *CreateTradingAccountCredentialRequest {
	return v.value
}

func (v *NullableCreateTradingAccountCredentialRequest) Set(val *CreateTradingAccountCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTradingAccountCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTradingAccountCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTradingAccountCredentialRequest(val *CreateTradingAccountCredentialRequest) *NullableCreateTradingAccountCredentialRequest {
	return &NullableCreateTradingAccountCredentialRequest{value: val, isSet: true}
}

func (v NullableCreateTradingAccountCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTradingAccountCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


