/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConnectTradingAccount200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectTradingAccount200Response{}

// ConnectTradingAccount200Response struct for ConnectTradingAccount200Response
type ConnectTradingAccount200Response struct {
	// Indicates if the operation was successful
	Success bool `json:"success"`
	// Error code (0 for success, negative for errors)
	Errno int32 `json:"errno"`
	// Error message (null for successful operations)
	Error NullableString `json:"error,omitempty"`
	Details NullableBaseResponseDetails `json:"details,omitempty"`
	Data *TradingAccount `json:"data,omitempty"`
}

type _ConnectTradingAccount200Response ConnectTradingAccount200Response

// NewConnectTradingAccount200Response instantiates a new ConnectTradingAccount200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectTradingAccount200Response(success bool, errno int32) *ConnectTradingAccount200Response {
	this := ConnectTradingAccount200Response{}
	this.Success = success
	this.Errno = errno
	return &this
}

// NewConnectTradingAccount200ResponseWithDefaults instantiates a new ConnectTradingAccount200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectTradingAccount200ResponseWithDefaults() *ConnectTradingAccount200Response {
	this := ConnectTradingAccount200Response{}
	return &this
}

// GetSuccess returns the Success field value
func (o *ConnectTradingAccount200Response) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *ConnectTradingAccount200Response) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ConnectTradingAccount200Response) SetSuccess(v bool) {
	o.Success = v
}

// GetErrno returns the Errno field value
func (o *ConnectTradingAccount200Response) GetErrno() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Errno
}

// GetErrnoOk returns a tuple with the Errno field value
// and a boolean to check if the value has been set.
func (o *ConnectTradingAccount200Response) GetErrnoOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Errno, true
}

// SetErrno sets field value
func (o *ConnectTradingAccount200Response) SetErrno(v int32) {
	o.Errno = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectTradingAccount200Response) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectTradingAccount200Response) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *ConnectTradingAccount200Response) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *ConnectTradingAccount200Response) SetError(v string) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *ConnectTradingAccount200Response) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *ConnectTradingAccount200Response) UnsetError() {
	o.Error.Unset()
}

// GetDetails returns the Details field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectTradingAccount200Response) GetDetails() BaseResponseDetails {
	if o == nil || IsNil(o.Details.Get()) {
		var ret BaseResponseDetails
		return ret
	}
	return *o.Details.Get()
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectTradingAccount200Response) GetDetailsOk() (*BaseResponseDetails, bool) {
	if o == nil {
		return nil, false
	}
	return o.Details.Get(), o.Details.IsSet()
}

// HasDetails returns a boolean if a field has been set.
func (o *ConnectTradingAccount200Response) HasDetails() bool {
	if o != nil && o.Details.IsSet() {
		return true
	}

	return false
}

// SetDetails gets a reference to the given NullableBaseResponseDetails and assigns it to the Details field.
func (o *ConnectTradingAccount200Response) SetDetails(v BaseResponseDetails) {
	o.Details.Set(&v)
}
// SetDetailsNil sets the value for Details to be an explicit nil
func (o *ConnectTradingAccount200Response) SetDetailsNil() {
	o.Details.Set(nil)
}

// UnsetDetails ensures that no value is present for Details, not even an explicit nil
func (o *ConnectTradingAccount200Response) UnsetDetails() {
	o.Details.Unset()
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ConnectTradingAccount200Response) GetData() TradingAccount {
	if o == nil || IsNil(o.Data) {
		var ret TradingAccount
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectTradingAccount200Response) GetDataOk() (*TradingAccount, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ConnectTradingAccount200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given TradingAccount and assigns it to the Data field.
func (o *ConnectTradingAccount200Response) SetData(v TradingAccount) {
	o.Data = &v
}

func (o ConnectTradingAccount200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectTradingAccount200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["errno"] = o.Errno
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if o.Details.IsSet() {
		toSerialize["details"] = o.Details.Get()
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

func (o *ConnectTradingAccount200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"errno",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectTradingAccount200Response := _ConnectTradingAccount200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectTradingAccount200Response)

	if err != nil {
		return err
	}

	*o = ConnectTradingAccount200Response(varConnectTradingAccount200Response)

	return err
}

type NullableConnectTradingAccount200Response struct {
	value *ConnectTradingAccount200Response
	isSet bool
}

func (v NullableConnectTradingAccount200Response) Get() *ConnectTradingAccount200Response {
	return v.value
}

func (v *NullableConnectTradingAccount200Response) Set(val *ConnectTradingAccount200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectTradingAccount200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectTradingAccount200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectTradingAccount200Response(val *ConnectTradingAccount200Response) *NullableConnectTradingAccount200Response {
	return &NullableConnectTradingAccount200Response{value: val, isSet: true}
}

func (v NullableConnectTradingAccount200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectTradingAccount200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


