/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Instrument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Instrument{}

// Instrument struct for Instrument
type Instrument struct {
	// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
	InstrumentId string `json:"instrumentId"`
	Venue Venue `json:"venue"`
	// Human-readable symbol format
	Symbol string `json:"symbol"`
	// Symbol format used by the exchange
	ExternalSymbol string `json:"externalSymbol"`
	// Symbol description, human readable description of the instrument
	Description *string `json:"description,omitempty"`
	InstrumentType InstrumentType `json:"instrumentType"`
	Status InstrumentStatus `json:"status"`
	BaseAsset string `json:"baseAsset"`
	QuoteAsset string `json:"quoteAsset"`
	BaseSecurityType SecurityType `json:"baseSecurityType"`
	QuoteSecurityType SecurityType `json:"quoteSecurityType"`
	// Base asset precision
	BasePrecision int32 `json:"basePrecision"`
	// Quote asset precision
	QuotePrecision int32 `json:"quotePrecision"`
	// Maximum significant digits for base asset
	BaseMaxSignificant NullableInt32 `json:"baseMaxSignificant"`
	// Maximum significant digits for quote asset
	QuoteMaxSignificant NullableInt32 `json:"quoteMaxSignificant"`
	// Decimal value as string to preserve precision
	LotSize string `json:"lotSize" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Decimal value as string to preserve precision
	PipSize string `json:"pipSize" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Base asset scale factor
	BaseScale NullableInt32 `json:"baseScale"`
	// Quote asset scale factor
	QuoteScale NullableInt32 `json:"quoteScale"`
	// Decimal value as string to preserve precision
	MinQuantity string `json:"minQuantity" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Decimal value as string to preserve precision
	MaxQuantity string `json:"maxQuantity" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Decimal value as string to preserve precision
	MinNotional string `json:"minNotional" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Decimal value as string to preserve precision
	MaxNotional *string `json:"maxNotional,omitempty" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Exchange-specific order filters
	OrderFilters map[string]interface{} `json:"orderFilters,omitempty"`
	OrderTypes []OrderType `json:"orderTypes"`
	TimeInForceOptions []TimeInForce `json:"timeInForceOptions"`
	// Trading hours and schedule information
	TradingHours map[string]interface{} `json:"tradingHours,omitempty"`
	// Whether iceberg orders are allowed
	IsIcebergAllowed *bool `json:"isIcebergAllowed,omitempty"`
	// Decimal value as string to preserve precision
	IcebergMinQuantity *string `json:"icebergMinQuantity,omitempty" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Unix timestamp in milliseconds
	DeliveryDate *int64 `json:"deliveryDate,omitempty"`
	// Delivery date in ISO 8601 format for derivatives
	DeliveryDateTime *time.Time `json:"deliveryDateTime,omitempty"`
	// Exercise style for options
	ExerciseStyle *string `json:"exerciseStyle,omitempty"`
	// Decimal value as string to preserve precision
	StrikePrice *string `json:"strikePrice,omitempty" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
}

type _Instrument Instrument

// NewInstrument instantiates a new Instrument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstrument(instrumentId string, venue Venue, symbol string, externalSymbol string, instrumentType InstrumentType, status InstrumentStatus, baseAsset string, quoteAsset string, baseSecurityType SecurityType, quoteSecurityType SecurityType, basePrecision int32, quotePrecision int32, baseMaxSignificant NullableInt32, quoteMaxSignificant NullableInt32, lotSize string, pipSize string, baseScale NullableInt32, quoteScale NullableInt32, minQuantity string, maxQuantity string, minNotional string, orderTypes []OrderType, timeInForceOptions []TimeInForce) *Instrument {
	this := Instrument{}
	this.InstrumentId = instrumentId
	this.Venue = venue
	this.Symbol = symbol
	this.ExternalSymbol = externalSymbol
	this.InstrumentType = instrumentType
	this.Status = status
	this.BaseAsset = baseAsset
	this.QuoteAsset = quoteAsset
	this.BaseSecurityType = baseSecurityType
	this.QuoteSecurityType = quoteSecurityType
	this.BasePrecision = basePrecision
	this.QuotePrecision = quotePrecision
	this.BaseMaxSignificant = baseMaxSignificant
	this.QuoteMaxSignificant = quoteMaxSignificant
	this.LotSize = lotSize
	this.PipSize = pipSize
	this.BaseScale = baseScale
	this.QuoteScale = quoteScale
	this.MinQuantity = minQuantity
	this.MaxQuantity = maxQuantity
	this.MinNotional = minNotional
	this.OrderTypes = orderTypes
	this.TimeInForceOptions = timeInForceOptions
	return &this
}

// NewInstrumentWithDefaults instantiates a new Instrument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstrumentWithDefaults() *Instrument {
	this := Instrument{}
	return &this
}

// GetInstrumentId returns the InstrumentId field value
func (o *Instrument) GetInstrumentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstrumentId
}

// GetInstrumentIdOk returns a tuple with the InstrumentId field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetInstrumentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstrumentId, true
}

// SetInstrumentId sets field value
func (o *Instrument) SetInstrumentId(v string) {
	o.InstrumentId = v
}

// GetVenue returns the Venue field value
func (o *Instrument) GetVenue() Venue {
	if o == nil {
		var ret Venue
		return ret
	}

	return o.Venue
}

// GetVenueOk returns a tuple with the Venue field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetVenueOk() (*Venue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Venue, true
}

// SetVenue sets field value
func (o *Instrument) SetVenue(v Venue) {
	o.Venue = v
}

// GetSymbol returns the Symbol field value
func (o *Instrument) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *Instrument) SetSymbol(v string) {
	o.Symbol = v
}

// GetExternalSymbol returns the ExternalSymbol field value
func (o *Instrument) GetExternalSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalSymbol
}

// GetExternalSymbolOk returns a tuple with the ExternalSymbol field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetExternalSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalSymbol, true
}

// SetExternalSymbol sets field value
func (o *Instrument) SetExternalSymbol(v string) {
	o.ExternalSymbol = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Instrument) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instrument) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Instrument) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Instrument) SetDescription(v string) {
	o.Description = &v
}

// GetInstrumentType returns the InstrumentType field value
func (o *Instrument) GetInstrumentType() InstrumentType {
	if o == nil {
		var ret InstrumentType
		return ret
	}

	return o.InstrumentType
}

// GetInstrumentTypeOk returns a tuple with the InstrumentType field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetInstrumentTypeOk() (*InstrumentType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstrumentType, true
}

// SetInstrumentType sets field value
func (o *Instrument) SetInstrumentType(v InstrumentType) {
	o.InstrumentType = v
}

// GetStatus returns the Status field value
func (o *Instrument) GetStatus() InstrumentStatus {
	if o == nil {
		var ret InstrumentStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetStatusOk() (*InstrumentStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Instrument) SetStatus(v InstrumentStatus) {
	o.Status = v
}

// GetBaseAsset returns the BaseAsset field value
func (o *Instrument) GetBaseAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseAsset
}

// GetBaseAssetOk returns a tuple with the BaseAsset field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetBaseAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseAsset, true
}

// SetBaseAsset sets field value
func (o *Instrument) SetBaseAsset(v string) {
	o.BaseAsset = v
}

// GetQuoteAsset returns the QuoteAsset field value
func (o *Instrument) GetQuoteAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteAsset
}

// GetQuoteAssetOk returns a tuple with the QuoteAsset field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetQuoteAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteAsset, true
}

// SetQuoteAsset sets field value
func (o *Instrument) SetQuoteAsset(v string) {
	o.QuoteAsset = v
}

// GetBaseSecurityType returns the BaseSecurityType field value
func (o *Instrument) GetBaseSecurityType() SecurityType {
	if o == nil {
		var ret SecurityType
		return ret
	}

	return o.BaseSecurityType
}

// GetBaseSecurityTypeOk returns a tuple with the BaseSecurityType field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetBaseSecurityTypeOk() (*SecurityType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseSecurityType, true
}

// SetBaseSecurityType sets field value
func (o *Instrument) SetBaseSecurityType(v SecurityType) {
	o.BaseSecurityType = v
}

// GetQuoteSecurityType returns the QuoteSecurityType field value
func (o *Instrument) GetQuoteSecurityType() SecurityType {
	if o == nil {
		var ret SecurityType
		return ret
	}

	return o.QuoteSecurityType
}

// GetQuoteSecurityTypeOk returns a tuple with the QuoteSecurityType field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetQuoteSecurityTypeOk() (*SecurityType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteSecurityType, true
}

// SetQuoteSecurityType sets field value
func (o *Instrument) SetQuoteSecurityType(v SecurityType) {
	o.QuoteSecurityType = v
}

// GetBasePrecision returns the BasePrecision field value
func (o *Instrument) GetBasePrecision() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BasePrecision
}

// GetBasePrecisionOk returns a tuple with the BasePrecision field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetBasePrecisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BasePrecision, true
}

// SetBasePrecision sets field value
func (o *Instrument) SetBasePrecision(v int32) {
	o.BasePrecision = v
}

// GetQuotePrecision returns the QuotePrecision field value
func (o *Instrument) GetQuotePrecision() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.QuotePrecision
}

// GetQuotePrecisionOk returns a tuple with the QuotePrecision field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetQuotePrecisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuotePrecision, true
}

// SetQuotePrecision sets field value
func (o *Instrument) SetQuotePrecision(v int32) {
	o.QuotePrecision = v
}

// GetBaseMaxSignificant returns the BaseMaxSignificant field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *Instrument) GetBaseMaxSignificant() int32 {
	if o == nil || o.BaseMaxSignificant.Get() == nil {
		var ret int32
		return ret
	}

	return *o.BaseMaxSignificant.Get()
}

// GetBaseMaxSignificantOk returns a tuple with the BaseMaxSignificant field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instrument) GetBaseMaxSignificantOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseMaxSignificant.Get(), o.BaseMaxSignificant.IsSet()
}

// SetBaseMaxSignificant sets field value
func (o *Instrument) SetBaseMaxSignificant(v int32) {
	o.BaseMaxSignificant.Set(&v)
}

// GetQuoteMaxSignificant returns the QuoteMaxSignificant field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *Instrument) GetQuoteMaxSignificant() int32 {
	if o == nil || o.QuoteMaxSignificant.Get() == nil {
		var ret int32
		return ret
	}

	return *o.QuoteMaxSignificant.Get()
}

// GetQuoteMaxSignificantOk returns a tuple with the QuoteMaxSignificant field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instrument) GetQuoteMaxSignificantOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.QuoteMaxSignificant.Get(), o.QuoteMaxSignificant.IsSet()
}

// SetQuoteMaxSignificant sets field value
func (o *Instrument) SetQuoteMaxSignificant(v int32) {
	o.QuoteMaxSignificant.Set(&v)
}

// GetLotSize returns the LotSize field value
func (o *Instrument) GetLotSize() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LotSize
}

// GetLotSizeOk returns a tuple with the LotSize field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetLotSizeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LotSize, true
}

// SetLotSize sets field value
func (o *Instrument) SetLotSize(v string) {
	o.LotSize = v
}

// GetPipSize returns the PipSize field value
func (o *Instrument) GetPipSize() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PipSize
}

// GetPipSizeOk returns a tuple with the PipSize field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetPipSizeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PipSize, true
}

// SetPipSize sets field value
func (o *Instrument) SetPipSize(v string) {
	o.PipSize = v
}

// GetBaseScale returns the BaseScale field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *Instrument) GetBaseScale() int32 {
	if o == nil || o.BaseScale.Get() == nil {
		var ret int32
		return ret
	}

	return *o.BaseScale.Get()
}

// GetBaseScaleOk returns a tuple with the BaseScale field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instrument) GetBaseScaleOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseScale.Get(), o.BaseScale.IsSet()
}

// SetBaseScale sets field value
func (o *Instrument) SetBaseScale(v int32) {
	o.BaseScale.Set(&v)
}

// GetQuoteScale returns the QuoteScale field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *Instrument) GetQuoteScale() int32 {
	if o == nil || o.QuoteScale.Get() == nil {
		var ret int32
		return ret
	}

	return *o.QuoteScale.Get()
}

// GetQuoteScaleOk returns a tuple with the QuoteScale field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instrument) GetQuoteScaleOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.QuoteScale.Get(), o.QuoteScale.IsSet()
}

// SetQuoteScale sets field value
func (o *Instrument) SetQuoteScale(v int32) {
	o.QuoteScale.Set(&v)
}

// GetMinQuantity returns the MinQuantity field value
func (o *Instrument) GetMinQuantity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinQuantity
}

// GetMinQuantityOk returns a tuple with the MinQuantity field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetMinQuantityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinQuantity, true
}

// SetMinQuantity sets field value
func (o *Instrument) SetMinQuantity(v string) {
	o.MinQuantity = v
}

// GetMaxQuantity returns the MaxQuantity field value
func (o *Instrument) GetMaxQuantity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MaxQuantity
}

// GetMaxQuantityOk returns a tuple with the MaxQuantity field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetMaxQuantityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxQuantity, true
}

// SetMaxQuantity sets field value
func (o *Instrument) SetMaxQuantity(v string) {
	o.MaxQuantity = v
}

// GetMinNotional returns the MinNotional field value
func (o *Instrument) GetMinNotional() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinNotional
}

// GetMinNotionalOk returns a tuple with the MinNotional field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetMinNotionalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinNotional, true
}

// SetMinNotional sets field value
func (o *Instrument) SetMinNotional(v string) {
	o.MinNotional = v
}

// GetMaxNotional returns the MaxNotional field value if set, zero value otherwise.
func (o *Instrument) GetMaxNotional() string {
	if o == nil || IsNil(o.MaxNotional) {
		var ret string
		return ret
	}
	return *o.MaxNotional
}

// GetMaxNotionalOk returns a tuple with the MaxNotional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instrument) GetMaxNotionalOk() (*string, bool) {
	if o == nil || IsNil(o.MaxNotional) {
		return nil, false
	}
	return o.MaxNotional, true
}

// HasMaxNotional returns a boolean if a field has been set.
func (o *Instrument) HasMaxNotional() bool {
	if o != nil && !IsNil(o.MaxNotional) {
		return true
	}

	return false
}

// SetMaxNotional gets a reference to the given string and assigns it to the MaxNotional field.
func (o *Instrument) SetMaxNotional(v string) {
	o.MaxNotional = &v
}

// GetOrderFilters returns the OrderFilters field value if set, zero value otherwise.
func (o *Instrument) GetOrderFilters() map[string]interface{} {
	if o == nil || IsNil(o.OrderFilters) {
		var ret map[string]interface{}
		return ret
	}
	return o.OrderFilters
}

// GetOrderFiltersOk returns a tuple with the OrderFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instrument) GetOrderFiltersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.OrderFilters) {
		return map[string]interface{}{}, false
	}
	return o.OrderFilters, true
}

// HasOrderFilters returns a boolean if a field has been set.
func (o *Instrument) HasOrderFilters() bool {
	if o != nil && !IsNil(o.OrderFilters) {
		return true
	}

	return false
}

// SetOrderFilters gets a reference to the given map[string]interface{} and assigns it to the OrderFilters field.
func (o *Instrument) SetOrderFilters(v map[string]interface{}) {
	o.OrderFilters = v
}

// GetOrderTypes returns the OrderTypes field value
func (o *Instrument) GetOrderTypes() []OrderType {
	if o == nil {
		var ret []OrderType
		return ret
	}

	return o.OrderTypes
}

// GetOrderTypesOk returns a tuple with the OrderTypes field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetOrderTypesOk() ([]OrderType, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderTypes, true
}

// SetOrderTypes sets field value
func (o *Instrument) SetOrderTypes(v []OrderType) {
	o.OrderTypes = v
}

// GetTimeInForceOptions returns the TimeInForceOptions field value
func (o *Instrument) GetTimeInForceOptions() []TimeInForce {
	if o == nil {
		var ret []TimeInForce
		return ret
	}

	return o.TimeInForceOptions
}

// GetTimeInForceOptionsOk returns a tuple with the TimeInForceOptions field value
// and a boolean to check if the value has been set.
func (o *Instrument) GetTimeInForceOptionsOk() ([]TimeInForce, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimeInForceOptions, true
}

// SetTimeInForceOptions sets field value
func (o *Instrument) SetTimeInForceOptions(v []TimeInForce) {
	o.TimeInForceOptions = v
}

// GetTradingHours returns the TradingHours field value if set, zero value otherwise.
func (o *Instrument) GetTradingHours() map[string]interface{} {
	if o == nil || IsNil(o.TradingHours) {
		var ret map[string]interface{}
		return ret
	}
	return o.TradingHours
}

// GetTradingHoursOk returns a tuple with the TradingHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instrument) GetTradingHoursOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TradingHours) {
		return map[string]interface{}{}, false
	}
	return o.TradingHours, true
}

// HasTradingHours returns a boolean if a field has been set.
func (o *Instrument) HasTradingHours() bool {
	if o != nil && !IsNil(o.TradingHours) {
		return true
	}

	return false
}

// SetTradingHours gets a reference to the given map[string]interface{} and assigns it to the TradingHours field.
func (o *Instrument) SetTradingHours(v map[string]interface{}) {
	o.TradingHours = v
}

// GetIsIcebergAllowed returns the IsIcebergAllowed field value if set, zero value otherwise.
func (o *Instrument) GetIsIcebergAllowed() bool {
	if o == nil || IsNil(o.IsIcebergAllowed) {
		var ret bool
		return ret
	}
	return *o.IsIcebergAllowed
}

// GetIsIcebergAllowedOk returns a tuple with the IsIcebergAllowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instrument) GetIsIcebergAllowedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsIcebergAllowed) {
		return nil, false
	}
	return o.IsIcebergAllowed, true
}

// HasIsIcebergAllowed returns a boolean if a field has been set.
func (o *Instrument) HasIsIcebergAllowed() bool {
	if o != nil && !IsNil(o.IsIcebergAllowed) {
		return true
	}

	return false
}

// SetIsIcebergAllowed gets a reference to the given bool and assigns it to the IsIcebergAllowed field.
func (o *Instrument) SetIsIcebergAllowed(v bool) {
	o.IsIcebergAllowed = &v
}

// GetIcebergMinQuantity returns the IcebergMinQuantity field value if set, zero value otherwise.
func (o *Instrument) GetIcebergMinQuantity() string {
	if o == nil || IsNil(o.IcebergMinQuantity) {
		var ret string
		return ret
	}
	return *o.IcebergMinQuantity
}

// GetIcebergMinQuantityOk returns a tuple with the IcebergMinQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instrument) GetIcebergMinQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.IcebergMinQuantity) {
		return nil, false
	}
	return o.IcebergMinQuantity, true
}

// HasIcebergMinQuantity returns a boolean if a field has been set.
func (o *Instrument) HasIcebergMinQuantity() bool {
	if o != nil && !IsNil(o.IcebergMinQuantity) {
		return true
	}

	return false
}

// SetIcebergMinQuantity gets a reference to the given string and assigns it to the IcebergMinQuantity field.
func (o *Instrument) SetIcebergMinQuantity(v string) {
	o.IcebergMinQuantity = &v
}

// GetDeliveryDate returns the DeliveryDate field value if set, zero value otherwise.
func (o *Instrument) GetDeliveryDate() int64 {
	if o == nil || IsNil(o.DeliveryDate) {
		var ret int64
		return ret
	}
	return *o.DeliveryDate
}

// GetDeliveryDateOk returns a tuple with the DeliveryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instrument) GetDeliveryDateOk() (*int64, bool) {
	if o == nil || IsNil(o.DeliveryDate) {
		return nil, false
	}
	return o.DeliveryDate, true
}

// HasDeliveryDate returns a boolean if a field has been set.
func (o *Instrument) HasDeliveryDate() bool {
	if o != nil && !IsNil(o.DeliveryDate) {
		return true
	}

	return false
}

// SetDeliveryDate gets a reference to the given int64 and assigns it to the DeliveryDate field.
func (o *Instrument) SetDeliveryDate(v int64) {
	o.DeliveryDate = &v
}

// GetDeliveryDateTime returns the DeliveryDateTime field value if set, zero value otherwise.
func (o *Instrument) GetDeliveryDateTime() time.Time {
	if o == nil || IsNil(o.DeliveryDateTime) {
		var ret time.Time
		return ret
	}
	return *o.DeliveryDateTime
}

// GetDeliveryDateTimeOk returns a tuple with the DeliveryDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instrument) GetDeliveryDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeliveryDateTime) {
		return nil, false
	}
	return o.DeliveryDateTime, true
}

// HasDeliveryDateTime returns a boolean if a field has been set.
func (o *Instrument) HasDeliveryDateTime() bool {
	if o != nil && !IsNil(o.DeliveryDateTime) {
		return true
	}

	return false
}

// SetDeliveryDateTime gets a reference to the given time.Time and assigns it to the DeliveryDateTime field.
func (o *Instrument) SetDeliveryDateTime(v time.Time) {
	o.DeliveryDateTime = &v
}

// GetExerciseStyle returns the ExerciseStyle field value if set, zero value otherwise.
func (o *Instrument) GetExerciseStyle() string {
	if o == nil || IsNil(o.ExerciseStyle) {
		var ret string
		return ret
	}
	return *o.ExerciseStyle
}

// GetExerciseStyleOk returns a tuple with the ExerciseStyle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instrument) GetExerciseStyleOk() (*string, bool) {
	if o == nil || IsNil(o.ExerciseStyle) {
		return nil, false
	}
	return o.ExerciseStyle, true
}

// HasExerciseStyle returns a boolean if a field has been set.
func (o *Instrument) HasExerciseStyle() bool {
	if o != nil && !IsNil(o.ExerciseStyle) {
		return true
	}

	return false
}

// SetExerciseStyle gets a reference to the given string and assigns it to the ExerciseStyle field.
func (o *Instrument) SetExerciseStyle(v string) {
	o.ExerciseStyle = &v
}

// GetStrikePrice returns the StrikePrice field value if set, zero value otherwise.
func (o *Instrument) GetStrikePrice() string {
	if o == nil || IsNil(o.StrikePrice) {
		var ret string
		return ret
	}
	return *o.StrikePrice
}

// GetStrikePriceOk returns a tuple with the StrikePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instrument) GetStrikePriceOk() (*string, bool) {
	if o == nil || IsNil(o.StrikePrice) {
		return nil, false
	}
	return o.StrikePrice, true
}

// HasStrikePrice returns a boolean if a field has been set.
func (o *Instrument) HasStrikePrice() bool {
	if o != nil && !IsNil(o.StrikePrice) {
		return true
	}

	return false
}

// SetStrikePrice gets a reference to the given string and assigns it to the StrikePrice field.
func (o *Instrument) SetStrikePrice(v string) {
	o.StrikePrice = &v
}

func (o Instrument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Instrument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instrumentId"] = o.InstrumentId
	toSerialize["venue"] = o.Venue
	toSerialize["symbol"] = o.Symbol
	toSerialize["externalSymbol"] = o.ExternalSymbol
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["instrumentType"] = o.InstrumentType
	toSerialize["status"] = o.Status
	toSerialize["baseAsset"] = o.BaseAsset
	toSerialize["quoteAsset"] = o.QuoteAsset
	toSerialize["baseSecurityType"] = o.BaseSecurityType
	toSerialize["quoteSecurityType"] = o.QuoteSecurityType
	toSerialize["basePrecision"] = o.BasePrecision
	toSerialize["quotePrecision"] = o.QuotePrecision
	toSerialize["baseMaxSignificant"] = o.BaseMaxSignificant.Get()
	toSerialize["quoteMaxSignificant"] = o.QuoteMaxSignificant.Get()
	toSerialize["lotSize"] = o.LotSize
	toSerialize["pipSize"] = o.PipSize
	toSerialize["baseScale"] = o.BaseScale.Get()
	toSerialize["quoteScale"] = o.QuoteScale.Get()
	toSerialize["minQuantity"] = o.MinQuantity
	toSerialize["maxQuantity"] = o.MaxQuantity
	toSerialize["minNotional"] = o.MinNotional
	if !IsNil(o.MaxNotional) {
		toSerialize["maxNotional"] = o.MaxNotional
	}
	if !IsNil(o.OrderFilters) {
		toSerialize["orderFilters"] = o.OrderFilters
	}
	toSerialize["orderTypes"] = o.OrderTypes
	toSerialize["timeInForceOptions"] = o.TimeInForceOptions
	if !IsNil(o.TradingHours) {
		toSerialize["tradingHours"] = o.TradingHours
	}
	if !IsNil(o.IsIcebergAllowed) {
		toSerialize["isIcebergAllowed"] = o.IsIcebergAllowed
	}
	if !IsNil(o.IcebergMinQuantity) {
		toSerialize["icebergMinQuantity"] = o.IcebergMinQuantity
	}
	if !IsNil(o.DeliveryDate) {
		toSerialize["deliveryDate"] = o.DeliveryDate
	}
	if !IsNil(o.DeliveryDateTime) {
		toSerialize["deliveryDateTime"] = o.DeliveryDateTime
	}
	if !IsNil(o.ExerciseStyle) {
		toSerialize["exerciseStyle"] = o.ExerciseStyle
	}
	if !IsNil(o.StrikePrice) {
		toSerialize["strikePrice"] = o.StrikePrice
	}
	return toSerialize, nil
}

func (o *Instrument) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instrumentId",
		"venue",
		"symbol",
		"externalSymbol",
		"instrumentType",
		"status",
		"baseAsset",
		"quoteAsset",
		"baseSecurityType",
		"quoteSecurityType",
		"basePrecision",
		"quotePrecision",
		"baseMaxSignificant",
		"quoteMaxSignificant",
		"lotSize",
		"pipSize",
		"baseScale",
		"quoteScale",
		"minQuantity",
		"maxQuantity",
		"minNotional",
		"orderTypes",
		"timeInForceOptions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstrument := _Instrument{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstrument)

	if err != nil {
		return err
	}

	*o = Instrument(varInstrument)

	return err
}

type NullableInstrument struct {
	value *Instrument
	isSet bool
}

func (v NullableInstrument) Get() *Instrument {
	return v.value
}

func (v *NullableInstrument) Set(val *Instrument) {
	v.value = val
	v.isSet = true
}

func (v NullableInstrument) IsSet() bool {
	return v.isSet
}

func (v *NullableInstrument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstrument(val *Instrument) *NullableInstrument {
	return &NullableInstrument{value: val, isSet: true}
}

func (v NullableInstrument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstrument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


