/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the RpcListKlinesParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpcListKlinesParams{}

// RpcListKlinesParams Request to list klines
type RpcListKlinesParams struct {
	InstrumentIds []string `json:"instrumentIds,omitempty"`
	Venue *Venue `json:"venue,omitempty"`
	Symbols []string `json:"symbols,omitempty"`
	Interval *string `json:"interval,omitempty"`
}

// NewRpcListKlinesParams instantiates a new RpcListKlinesParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpcListKlinesParams() *RpcListKlinesParams {
	this := RpcListKlinesParams{}
	return &this
}

// NewRpcListKlinesParamsWithDefaults instantiates a new RpcListKlinesParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpcListKlinesParamsWithDefaults() *RpcListKlinesParams {
	this := RpcListKlinesParams{}
	return &this
}

// GetInstrumentIds returns the InstrumentIds field value if set, zero value otherwise.
func (o *RpcListKlinesParams) GetInstrumentIds() []string {
	if o == nil || IsNil(o.InstrumentIds) {
		var ret []string
		return ret
	}
	return o.InstrumentIds
}

// GetInstrumentIdsOk returns a tuple with the InstrumentIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcListKlinesParams) GetInstrumentIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.InstrumentIds) {
		return nil, false
	}
	return o.InstrumentIds, true
}

// HasInstrumentIds returns a boolean if a field has been set.
func (o *RpcListKlinesParams) HasInstrumentIds() bool {
	if o != nil && !IsNil(o.InstrumentIds) {
		return true
	}

	return false
}

// SetInstrumentIds gets a reference to the given []string and assigns it to the InstrumentIds field.
func (o *RpcListKlinesParams) SetInstrumentIds(v []string) {
	o.InstrumentIds = v
}

// GetVenue returns the Venue field value if set, zero value otherwise.
func (o *RpcListKlinesParams) GetVenue() Venue {
	if o == nil || IsNil(o.Venue) {
		var ret Venue
		return ret
	}
	return *o.Venue
}

// GetVenueOk returns a tuple with the Venue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcListKlinesParams) GetVenueOk() (*Venue, bool) {
	if o == nil || IsNil(o.Venue) {
		return nil, false
	}
	return o.Venue, true
}

// HasVenue returns a boolean if a field has been set.
func (o *RpcListKlinesParams) HasVenue() bool {
	if o != nil && !IsNil(o.Venue) {
		return true
	}

	return false
}

// SetVenue gets a reference to the given Venue and assigns it to the Venue field.
func (o *RpcListKlinesParams) SetVenue(v Venue) {
	o.Venue = &v
}

// GetSymbols returns the Symbols field value if set, zero value otherwise.
func (o *RpcListKlinesParams) GetSymbols() []string {
	if o == nil || IsNil(o.Symbols) {
		var ret []string
		return ret
	}
	return o.Symbols
}

// GetSymbolsOk returns a tuple with the Symbols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcListKlinesParams) GetSymbolsOk() ([]string, bool) {
	if o == nil || IsNil(o.Symbols) {
		return nil, false
	}
	return o.Symbols, true
}

// HasSymbols returns a boolean if a field has been set.
func (o *RpcListKlinesParams) HasSymbols() bool {
	if o != nil && !IsNil(o.Symbols) {
		return true
	}

	return false
}

// SetSymbols gets a reference to the given []string and assigns it to the Symbols field.
func (o *RpcListKlinesParams) SetSymbols(v []string) {
	o.Symbols = v
}

// GetInterval returns the Interval field value if set, zero value otherwise.
func (o *RpcListKlinesParams) GetInterval() string {
	if o == nil || IsNil(o.Interval) {
		var ret string
		return ret
	}
	return *o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcListKlinesParams) GetIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.Interval) {
		return nil, false
	}
	return o.Interval, true
}

// HasInterval returns a boolean if a field has been set.
func (o *RpcListKlinesParams) HasInterval() bool {
	if o != nil && !IsNil(o.Interval) {
		return true
	}

	return false
}

// SetInterval gets a reference to the given string and assigns it to the Interval field.
func (o *RpcListKlinesParams) SetInterval(v string) {
	o.Interval = &v
}

func (o RpcListKlinesParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpcListKlinesParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstrumentIds) {
		toSerialize["instrumentIds"] = o.InstrumentIds
	}
	if !IsNil(o.Venue) {
		toSerialize["venue"] = o.Venue
	}
	if !IsNil(o.Symbols) {
		toSerialize["symbols"] = o.Symbols
	}
	if !IsNil(o.Interval) {
		toSerialize["interval"] = o.Interval
	}
	return toSerialize, nil
}

type NullableRpcListKlinesParams struct {
	value *RpcListKlinesParams
	isSet bool
}

func (v NullableRpcListKlinesParams) Get() *RpcListKlinesParams {
	return v.value
}

func (v *NullableRpcListKlinesParams) Set(val *RpcListKlinesParams) {
	v.value = val
	v.isSet = true
}

func (v NullableRpcListKlinesParams) IsSet() bool {
	return v.isSet
}

func (v *NullableRpcListKlinesParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpcListKlinesParams(val *RpcListKlinesParams) *NullableRpcListKlinesParams {
	return &NullableRpcListKlinesParams{value: val, isSet: true}
}

func (v NullableRpcListKlinesParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpcListKlinesParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


