/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// InstrumentStatus Instrument status
type InstrumentStatus string

// List of instrumentStatus
const (
	INSTRUMENTSTATUS_ACTIVE InstrumentStatus = "ACTIVE"
	INSTRUMENTSTATUS_INACTIVE InstrumentStatus = "INACTIVE"
	INSTRUMENTSTATUS_DISABLED InstrumentStatus = "DISABLED"
	INSTRUMENTSTATUS_DELISTED InstrumentStatus = "DELISTED"
)

// All allowed values of InstrumentStatus enum
var AllowedInstrumentStatusEnumValues = []InstrumentStatus{
	"ACTIVE",
	"INACTIVE",
	"DISABLED",
	"DELISTED",
}

func (v *InstrumentStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := InstrumentStatus(value)
	for _, existing := range AllowedInstrumentStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid InstrumentStatus", value)
}

// NewInstrumentStatusFromValue returns a pointer to a valid InstrumentStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewInstrumentStatusFromValue(v string) (*InstrumentStatus, error) {
	ev := InstrumentStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for InstrumentStatus: valid values are %v", v, AllowedInstrumentStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v InstrumentStatus) IsValid() bool {
	for _, existing := range AllowedInstrumentStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to instrumentStatus value
func (v InstrumentStatus) Ptr() *InstrumentStatus {
	return &v
}

type NullableInstrumentStatus struct {
	value *InstrumentStatus
	isSet bool
}

func (v NullableInstrumentStatus) Get() *InstrumentStatus {
	return v.value
}

func (v *NullableInstrumentStatus) Set(val *InstrumentStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableInstrumentStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableInstrumentStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstrumentStatus(val *InstrumentStatus) *NullableInstrumentStatus {
	return &NullableInstrumentStatus{value: val, isSet: true}
}

func (v NullableInstrumentStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstrumentStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

