/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// checks if the FermataCloseWalletRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FermataCloseWalletRequest{}

// FermataCloseWalletRequest struct for FermataCloseWalletRequest
type FermataCloseWalletRequest struct {
	// UUID string
	WalletId string `json:"walletId"`
	AdditionalProperties map[string]interface{}
}

type _FermataCloseWalletRequest FermataCloseWalletRequest

// NewFermataCloseWalletRequest instantiates a new FermataCloseWalletRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFermataCloseWalletRequest(walletId string) *FermataCloseWalletRequest {
	this := FermataCloseWalletRequest{}
	this.WalletId = walletId
	return &this
}

// NewFermataCloseWalletRequestWithDefaults instantiates a new FermataCloseWalletRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFermataCloseWalletRequestWithDefaults() *FermataCloseWalletRequest {
	this := FermataCloseWalletRequest{}
	return &this
}

// GetWalletId returns the WalletId field value
func (o *FermataCloseWalletRequest) GetWalletId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletId
}

// GetWalletIdOk returns a tuple with the WalletId field value
// and a boolean to check if the value has been set.
func (o *FermataCloseWalletRequest) GetWalletIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletId, true
}

// SetWalletId sets field value
func (o *FermataCloseWalletRequest) SetWalletId(v string) {
	o.WalletId = v
}

func (o FermataCloseWalletRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FermataCloseWalletRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["walletId"] = o.WalletId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FermataCloseWalletRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"walletId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFermataCloseWalletRequest := _FermataCloseWalletRequest{}

	err = json.Unmarshal(data, &varFermataCloseWalletRequest)

	if err != nil {
		return err
	}

	*o = FermataCloseWalletRequest(varFermataCloseWalletRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "walletId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFermataCloseWalletRequest struct {
	value *FermataCloseWalletRequest
	isSet bool
}

func (v NullableFermataCloseWalletRequest) Get() *FermataCloseWalletRequest {
	return v.value
}

func (v *NullableFermataCloseWalletRequest) Set(val *FermataCloseWalletRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFermataCloseWalletRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFermataCloseWalletRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFermataCloseWalletRequest(val *FermataCloseWalletRequest) *NullableFermataCloseWalletRequest {
	return &NullableFermataCloseWalletRequest{value: val, isSet: true}
}

func (v NullableFermataCloseWalletRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFermataCloseWalletRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


