/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the UnsubscribeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnsubscribeRequest{}

// UnsubscribeRequest struct for UnsubscribeRequest
type UnsubscribeRequest struct {
	// UUID string
	SubscriptionId *string `json:"subscriptionId,omitempty"`
	// UUID string
	TradingAccountId *string `json:"tradingAccountId,omitempty"`
	// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
	InstrumentId *string `json:"instrumentId,omitempty"`
}

// NewUnsubscribeRequest instantiates a new UnsubscribeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnsubscribeRequest() *UnsubscribeRequest {
	this := UnsubscribeRequest{}
	return &this
}

// NewUnsubscribeRequestWithDefaults instantiates a new UnsubscribeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnsubscribeRequestWithDefaults() *UnsubscribeRequest {
	this := UnsubscribeRequest{}
	return &this
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *UnsubscribeRequest) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsubscribeRequest) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *UnsubscribeRequest) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *UnsubscribeRequest) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

// GetTradingAccountId returns the TradingAccountId field value if set, zero value otherwise.
func (o *UnsubscribeRequest) GetTradingAccountId() string {
	if o == nil || IsNil(o.TradingAccountId) {
		var ret string
		return ret
	}
	return *o.TradingAccountId
}

// GetTradingAccountIdOk returns a tuple with the TradingAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsubscribeRequest) GetTradingAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.TradingAccountId) {
		return nil, false
	}
	return o.TradingAccountId, true
}

// HasTradingAccountId returns a boolean if a field has been set.
func (o *UnsubscribeRequest) HasTradingAccountId() bool {
	if o != nil && !IsNil(o.TradingAccountId) {
		return true
	}

	return false
}

// SetTradingAccountId gets a reference to the given string and assigns it to the TradingAccountId field.
func (o *UnsubscribeRequest) SetTradingAccountId(v string) {
	o.TradingAccountId = &v
}

// GetInstrumentId returns the InstrumentId field value if set, zero value otherwise.
func (o *UnsubscribeRequest) GetInstrumentId() string {
	if o == nil || IsNil(o.InstrumentId) {
		var ret string
		return ret
	}
	return *o.InstrumentId
}

// GetInstrumentIdOk returns a tuple with the InstrumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsubscribeRequest) GetInstrumentIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstrumentId) {
		return nil, false
	}
	return o.InstrumentId, true
}

// HasInstrumentId returns a boolean if a field has been set.
func (o *UnsubscribeRequest) HasInstrumentId() bool {
	if o != nil && !IsNil(o.InstrumentId) {
		return true
	}

	return false
}

// SetInstrumentId gets a reference to the given string and assigns it to the InstrumentId field.
func (o *UnsubscribeRequest) SetInstrumentId(v string) {
	o.InstrumentId = &v
}

func (o UnsubscribeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnsubscribeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscriptionId"] = o.SubscriptionId
	}
	if !IsNil(o.TradingAccountId) {
		toSerialize["tradingAccountId"] = o.TradingAccountId
	}
	if !IsNil(o.InstrumentId) {
		toSerialize["instrumentId"] = o.InstrumentId
	}
	return toSerialize, nil
}

type NullableUnsubscribeRequest struct {
	value *UnsubscribeRequest
	isSet bool
}

func (v NullableUnsubscribeRequest) Get() *UnsubscribeRequest {
	return v.value
}

func (v *NullableUnsubscribeRequest) Set(val *UnsubscribeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUnsubscribeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUnsubscribeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnsubscribeRequest(val *UnsubscribeRequest) *NullableUnsubscribeRequest {
	return &NullableUnsubscribeRequest{value: val, isSet: true}
}

func (v NullableUnsubscribeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnsubscribeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


