/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the RpcTradingAccountConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpcTradingAccountConfig{}

// RpcTradingAccountConfig Trading account configuration
type RpcTradingAccountConfig struct {
	// Account leverage
	Leverage *int32 `json:"leverage,omitempty"`
}

// NewRpcTradingAccountConfig instantiates a new RpcTradingAccountConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpcTradingAccountConfig() *RpcTradingAccountConfig {
	this := RpcTradingAccountConfig{}
	return &this
}

// NewRpcTradingAccountConfigWithDefaults instantiates a new RpcTradingAccountConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpcTradingAccountConfigWithDefaults() *RpcTradingAccountConfig {
	this := RpcTradingAccountConfig{}
	return &this
}

// GetLeverage returns the Leverage field value if set, zero value otherwise.
func (o *RpcTradingAccountConfig) GetLeverage() int32 {
	if o == nil || IsNil(o.Leverage) {
		var ret int32
		return ret
	}
	return *o.Leverage
}

// GetLeverageOk returns a tuple with the Leverage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradingAccountConfig) GetLeverageOk() (*int32, bool) {
	if o == nil || IsNil(o.Leverage) {
		return nil, false
	}
	return o.Leverage, true
}

// HasLeverage returns a boolean if a field has been set.
func (o *RpcTradingAccountConfig) HasLeverage() bool {
	if o != nil && !IsNil(o.Leverage) {
		return true
	}

	return false
}

// SetLeverage gets a reference to the given int32 and assigns it to the Leverage field.
func (o *RpcTradingAccountConfig) SetLeverage(v int32) {
	o.Leverage = &v
}

func (o RpcTradingAccountConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpcTradingAccountConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Leverage) {
		toSerialize["leverage"] = o.Leverage
	}
	return toSerialize, nil
}

type NullableRpcTradingAccountConfig struct {
	value *RpcTradingAccountConfig
	isSet bool
}

func (v NullableRpcTradingAccountConfig) Get() *RpcTradingAccountConfig {
	return v.value
}

func (v *NullableRpcTradingAccountConfig) Set(val *RpcTradingAccountConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableRpcTradingAccountConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableRpcTradingAccountConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpcTradingAccountConfig(val *RpcTradingAccountConfig) *NullableRpcTradingAccountConfig {
	return &NullableRpcTradingAccountConfig{value: val, isSet: true}
}

func (v NullableRpcTradingAccountConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpcTradingAccountConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


