/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RpcSaveTickersParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpcSaveTickersParams{}

// RpcSaveTickersParams Request to save tickers
type RpcSaveTickersParams struct {
	Tickers []RpcTicker `json:"tickers"`
}

type _RpcSaveTickersParams RpcSaveTickersParams

// NewRpcSaveTickersParams instantiates a new RpcSaveTickersParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpcSaveTickersParams(tickers []RpcTicker) *RpcSaveTickersParams {
	this := RpcSaveTickersParams{}
	this.Tickers = tickers
	return &this
}

// NewRpcSaveTickersParamsWithDefaults instantiates a new RpcSaveTickersParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpcSaveTickersParamsWithDefaults() *RpcSaveTickersParams {
	this := RpcSaveTickersParams{}
	return &this
}

// GetTickers returns the Tickers field value
func (o *RpcSaveTickersParams) GetTickers() []RpcTicker {
	if o == nil {
		var ret []RpcTicker
		return ret
	}

	return o.Tickers
}

// GetTickersOk returns a tuple with the Tickers field value
// and a boolean to check if the value has been set.
func (o *RpcSaveTickersParams) GetTickersOk() ([]RpcTicker, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tickers, true
}

// SetTickers sets field value
func (o *RpcSaveTickersParams) SetTickers(v []RpcTicker) {
	o.Tickers = v
}

func (o RpcSaveTickersParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpcSaveTickersParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tickers"] = o.Tickers
	return toSerialize, nil
}

func (o *RpcSaveTickersParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tickers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRpcSaveTickersParams := _RpcSaveTickersParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRpcSaveTickersParams)

	if err != nil {
		return err
	}

	*o = RpcSaveTickersParams(varRpcSaveTickersParams)

	return err
}

type NullableRpcSaveTickersParams struct {
	value *RpcSaveTickersParams
	isSet bool
}

func (v NullableRpcSaveTickersParams) Get() *RpcSaveTickersParams {
	return v.value
}

func (v *NullableRpcSaveTickersParams) Set(val *RpcSaveTickersParams) {
	v.value = val
	v.isSet = true
}

func (v NullableRpcSaveTickersParams) IsSet() bool {
	return v.isSet
}

func (v *NullableRpcSaveTickersParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpcSaveTickersParams(val *RpcSaveTickersParams) *NullableRpcSaveTickersParams {
	return &NullableRpcSaveTickersParams{value: val, isSet: true}
}

func (v NullableRpcSaveTickersParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpcSaveTickersParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


