/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Root500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Root500Response{}

// Root500Response struct for Root500Response
type Root500Response struct {
	// Indicates if the operation was successful
	Success bool `json:"success"`
	// Error code (0 for success, negative for errors)
	Errno int32 `json:"errno"`
	// Error message (null for successful operations)
	Error NullableString `json:"error"`
	Details NullableBaseResponseDetails `json:"details,omitempty"`
	Data NullableString `json:"data,omitempty"`
}

type _Root500Response Root500Response

// NewRoot500Response instantiates a new Root500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoot500Response(success bool, errno int32, error_ NullableString) *Root500Response {
	this := Root500Response{}
	this.Success = success
	this.Errno = errno
	this.Error = error_
	return &this
}

// NewRoot500ResponseWithDefaults instantiates a new Root500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoot500ResponseWithDefaults() *Root500Response {
	this := Root500Response{}
	return &this
}

// GetSuccess returns the Success field value
func (o *Root500Response) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *Root500Response) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *Root500Response) SetSuccess(v bool) {
	o.Success = v
}

// GetErrno returns the Errno field value
func (o *Root500Response) GetErrno() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Errno
}

// GetErrnoOk returns a tuple with the Errno field value
// and a boolean to check if the value has been set.
func (o *Root500Response) GetErrnoOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Errno, true
}

// SetErrno sets field value
func (o *Root500Response) SetErrno(v int32) {
	o.Errno = v
}

// GetError returns the Error field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Root500Response) GetError() string {
	if o == nil || o.Error.Get() == nil {
		var ret string
		return ret
	}

	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Root500Response) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// SetError sets field value
func (o *Root500Response) SetError(v string) {
	o.Error.Set(&v)
}

// GetDetails returns the Details field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Root500Response) GetDetails() BaseResponseDetails {
	if o == nil || IsNil(o.Details.Get()) {
		var ret BaseResponseDetails
		return ret
	}
	return *o.Details.Get()
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Root500Response) GetDetailsOk() (*BaseResponseDetails, bool) {
	if o == nil {
		return nil, false
	}
	return o.Details.Get(), o.Details.IsSet()
}

// HasDetails returns a boolean if a field has been set.
func (o *Root500Response) HasDetails() bool {
	if o != nil && o.Details.IsSet() {
		return true
	}

	return false
}

// SetDetails gets a reference to the given NullableBaseResponseDetails and assigns it to the Details field.
func (o *Root500Response) SetDetails(v BaseResponseDetails) {
	o.Details.Set(&v)
}
// SetDetailsNil sets the value for Details to be an explicit nil
func (o *Root500Response) SetDetailsNil() {
	o.Details.Set(nil)
}

// UnsetDetails ensures that no value is present for Details, not even an explicit nil
func (o *Root500Response) UnsetDetails() {
	o.Details.Unset()
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Root500Response) GetData() string {
	if o == nil || IsNil(o.Data.Get()) {
		var ret string
		return ret
	}
	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Root500Response) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// HasData returns a boolean if a field has been set.
func (o *Root500Response) HasData() bool {
	if o != nil && o.Data.IsSet() {
		return true
	}

	return false
}

// SetData gets a reference to the given NullableString and assigns it to the Data field.
func (o *Root500Response) SetData(v string) {
	o.Data.Set(&v)
}
// SetDataNil sets the value for Data to be an explicit nil
func (o *Root500Response) SetDataNil() {
	o.Data.Set(nil)
}

// UnsetData ensures that no value is present for Data, not even an explicit nil
func (o *Root500Response) UnsetData() {
	o.Data.Unset()
}

func (o Root500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Root500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["errno"] = o.Errno
	toSerialize["error"] = o.Error.Get()
	if o.Details.IsSet() {
		toSerialize["details"] = o.Details.Get()
	}
	if o.Data.IsSet() {
		toSerialize["data"] = o.Data.Get()
	}
	return toSerialize, nil
}

func (o *Root500Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"errno",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoot500Response := _Root500Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRoot500Response)

	if err != nil {
		return err
	}

	*o = Root500Response(varRoot500Response)

	return err
}

type NullableRoot500Response struct {
	value *Root500Response
	isSet bool
}

func (v NullableRoot500Response) Get() *Root500Response {
	return v.value
}

func (v *NullableRoot500Response) Set(val *Root500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRoot500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRoot500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoot500Response(val *Root500Response) *NullableRoot500Response {
	return &NullableRoot500Response{value: val, isSet: true}
}

func (v NullableRoot500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoot500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


