/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RpcSyncSecuritiesParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpcSyncSecuritiesParams{}

// RpcSyncSecuritiesParams Request to sync securities from venue
type RpcSyncSecuritiesParams struct {
	Venue Venue `json:"venue"`
	Securities []string `json:"securities,omitempty"`
}

type _RpcSyncSecuritiesParams RpcSyncSecuritiesParams

// NewRpcSyncSecuritiesParams instantiates a new RpcSyncSecuritiesParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpcSyncSecuritiesParams(venue Venue) *RpcSyncSecuritiesParams {
	this := RpcSyncSecuritiesParams{}
	this.Venue = venue
	return &this
}

// NewRpcSyncSecuritiesParamsWithDefaults instantiates a new RpcSyncSecuritiesParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpcSyncSecuritiesParamsWithDefaults() *RpcSyncSecuritiesParams {
	this := RpcSyncSecuritiesParams{}
	return &this
}

// GetVenue returns the Venue field value
func (o *RpcSyncSecuritiesParams) GetVenue() Venue {
	if o == nil {
		var ret Venue
		return ret
	}

	return o.Venue
}

// GetVenueOk returns a tuple with the Venue field value
// and a boolean to check if the value has been set.
func (o *RpcSyncSecuritiesParams) GetVenueOk() (*Venue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Venue, true
}

// SetVenue sets field value
func (o *RpcSyncSecuritiesParams) SetVenue(v Venue) {
	o.Venue = v
}

// GetSecurities returns the Securities field value if set, zero value otherwise.
func (o *RpcSyncSecuritiesParams) GetSecurities() []string {
	if o == nil || IsNil(o.Securities) {
		var ret []string
		return ret
	}
	return o.Securities
}

// GetSecuritiesOk returns a tuple with the Securities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcSyncSecuritiesParams) GetSecuritiesOk() ([]string, bool) {
	if o == nil || IsNil(o.Securities) {
		return nil, false
	}
	return o.Securities, true
}

// HasSecurities returns a boolean if a field has been set.
func (o *RpcSyncSecuritiesParams) HasSecurities() bool {
	if o != nil && !IsNil(o.Securities) {
		return true
	}

	return false
}

// SetSecurities gets a reference to the given []string and assigns it to the Securities field.
func (o *RpcSyncSecuritiesParams) SetSecurities(v []string) {
	o.Securities = v
}

func (o RpcSyncSecuritiesParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpcSyncSecuritiesParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["venue"] = o.Venue
	if !IsNil(o.Securities) {
		toSerialize["securities"] = o.Securities
	}
	return toSerialize, nil
}

func (o *RpcSyncSecuritiesParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"venue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRpcSyncSecuritiesParams := _RpcSyncSecuritiesParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRpcSyncSecuritiesParams)

	if err != nil {
		return err
	}

	*o = RpcSyncSecuritiesParams(varRpcSyncSecuritiesParams)

	return err
}

type NullableRpcSyncSecuritiesParams struct {
	value *RpcSyncSecuritiesParams
	isSet bool
}

func (v NullableRpcSyncSecuritiesParams) Get() *RpcSyncSecuritiesParams {
	return v.value
}

func (v *NullableRpcSyncSecuritiesParams) Set(val *RpcSyncSecuritiesParams) {
	v.value = val
	v.isSet = true
}

func (v NullableRpcSyncSecuritiesParams) IsSet() bool {
	return v.isSet
}

func (v *NullableRpcSyncSecuritiesParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpcSyncSecuritiesParams(val *RpcSyncSecuritiesParams) *NullableRpcSyncSecuritiesParams {
	return &NullableRpcSyncSecuritiesParams{value: val, isSet: true}
}

func (v NullableRpcSyncSecuritiesParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpcSyncSecuritiesParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


