/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the BaseResponseDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseResponseDetails{}

// BaseResponseDetails Additional error details (optional, only present in error responses)
type BaseResponseDetails struct {
	// Error code identifier (e.g., INVALID_TOKEN, ACCESS_DENIED)
	Code *string `json:"code,omitempty"`
	// Resource that was being accessed
	Resource *string `json:"resource,omitempty"`
	// Action that was being attempted
	Action *string `json:"action,omitempty"`
	// Required permissions or roles
	Required []string `json:"required,omitempty"`
	// Provided permissions or roles
	Provided []string `json:"provided,omitempty"`
	// Tenant ID if relevant to the error
	TenantId *string `json:"tenant_id,omitempty"`
	// Request ID for tracking and debugging
	RequestId *string `json:"request_id,omitempty"`
	// Additional metadata as key-value pairs
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// NewBaseResponseDetails instantiates a new BaseResponseDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseResponseDetails() *BaseResponseDetails {
	this := BaseResponseDetails{}
	return &this
}

// NewBaseResponseDetailsWithDefaults instantiates a new BaseResponseDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseResponseDetailsWithDefaults() *BaseResponseDetails {
	this := BaseResponseDetails{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *BaseResponseDetails) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseDetails) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *BaseResponseDetails) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *BaseResponseDetails) SetCode(v string) {
	o.Code = &v
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *BaseResponseDetails) GetResource() string {
	if o == nil || IsNil(o.Resource) {
		var ret string
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseDetails) GetResourceOk() (*string, bool) {
	if o == nil || IsNil(o.Resource) {
		return nil, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *BaseResponseDetails) HasResource() bool {
	if o != nil && !IsNil(o.Resource) {
		return true
	}

	return false
}

// SetResource gets a reference to the given string and assigns it to the Resource field.
func (o *BaseResponseDetails) SetResource(v string) {
	o.Resource = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *BaseResponseDetails) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseDetails) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *BaseResponseDetails) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *BaseResponseDetails) SetAction(v string) {
	o.Action = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *BaseResponseDetails) GetRequired() []string {
	if o == nil || IsNil(o.Required) {
		var ret []string
		return ret
	}
	return o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseDetails) GetRequiredOk() ([]string, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *BaseResponseDetails) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given []string and assigns it to the Required field.
func (o *BaseResponseDetails) SetRequired(v []string) {
	o.Required = v
}

// GetProvided returns the Provided field value if set, zero value otherwise.
func (o *BaseResponseDetails) GetProvided() []string {
	if o == nil || IsNil(o.Provided) {
		var ret []string
		return ret
	}
	return o.Provided
}

// GetProvidedOk returns a tuple with the Provided field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseDetails) GetProvidedOk() ([]string, bool) {
	if o == nil || IsNil(o.Provided) {
		return nil, false
	}
	return o.Provided, true
}

// HasProvided returns a boolean if a field has been set.
func (o *BaseResponseDetails) HasProvided() bool {
	if o != nil && !IsNil(o.Provided) {
		return true
	}

	return false
}

// SetProvided gets a reference to the given []string and assigns it to the Provided field.
func (o *BaseResponseDetails) SetProvided(v []string) {
	o.Provided = v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *BaseResponseDetails) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseDetails) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *BaseResponseDetails) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *BaseResponseDetails) SetTenantId(v string) {
	o.TenantId = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *BaseResponseDetails) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseDetails) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *BaseResponseDetails) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *BaseResponseDetails) SetRequestId(v string) {
	o.RequestId = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *BaseResponseDetails) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseDetails) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *BaseResponseDetails) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *BaseResponseDetails) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o BaseResponseDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseResponseDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Resource) {
		toSerialize["resource"] = o.Resource
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.Provided) {
		toSerialize["provided"] = o.Provided
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableBaseResponseDetails struct {
	value *BaseResponseDetails
	isSet bool
}

func (v NullableBaseResponseDetails) Get() *BaseResponseDetails {
	return v.value
}

func (v *NullableBaseResponseDetails) Set(val *BaseResponseDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseResponseDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseResponseDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseResponseDetails(val *BaseResponseDetails) *NullableBaseResponseDetails {
	return &NullableBaseResponseDetails{value: val, isSet: true}
}

func (v NullableBaseResponseDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseResponseDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


