/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PortfolioSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PortfolioSummary{}

// PortfolioSummary struct for PortfolioSummary
type PortfolioSummary struct {
	// UUID string
	TradingAccountId string `json:"tradingAccountId"`
	// Base currency for the portfolio summary
	Currency string `json:"currency"`
	// Leverage multiplier
	Leverage NullableInt32 `json:"leverage"`
	// Decimal value as string to preserve precision
	Equity string `json:"equity" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Decimal value as string to preserve precision
	Margin string `json:"margin" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Decimal value as string to preserve precision
	MarginLoan string `json:"marginLoan" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Decimal value as string to preserve precision
	MarginUsage string `json:"marginUsage" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Decimal value as string to preserve precision
	MarginRequirement string `json:"marginRequirement" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Decimal value as string to preserve precision
	MarginLevel string `json:"marginLevel" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Decimal value as string to preserve precision
	Credit string `json:"credit" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Decimal value as string to preserve precision
	RiskExposure string `json:"riskExposure" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Decimal value as string to preserve precision
	MaxRiskExposure *string `json:"maxRiskExposure,omitempty" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
	// Decimal value as string to preserve precision
	RiskExposureRate *string `json:"riskExposureRate,omitempty" validate:"regexp=^-?\\\\d+(\\\\.\\\\d+)?$"`
}

type _PortfolioSummary PortfolioSummary

// NewPortfolioSummary instantiates a new PortfolioSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPortfolioSummary(tradingAccountId string, currency string, leverage NullableInt32, equity string, margin string, marginLoan string, marginUsage string, marginRequirement string, marginLevel string, credit string, riskExposure string) *PortfolioSummary {
	this := PortfolioSummary{}
	this.TradingAccountId = tradingAccountId
	this.Currency = currency
	this.Leverage = leverage
	this.Equity = equity
	this.Margin = margin
	this.MarginLoan = marginLoan
	this.MarginUsage = marginUsage
	this.MarginRequirement = marginRequirement
	this.MarginLevel = marginLevel
	this.Credit = credit
	this.RiskExposure = riskExposure
	return &this
}

// NewPortfolioSummaryWithDefaults instantiates a new PortfolioSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPortfolioSummaryWithDefaults() *PortfolioSummary {
	this := PortfolioSummary{}
	return &this
}

// GetTradingAccountId returns the TradingAccountId field value
func (o *PortfolioSummary) GetTradingAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TradingAccountId
}

// GetTradingAccountIdOk returns a tuple with the TradingAccountId field value
// and a boolean to check if the value has been set.
func (o *PortfolioSummary) GetTradingAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TradingAccountId, true
}

// SetTradingAccountId sets field value
func (o *PortfolioSummary) SetTradingAccountId(v string) {
	o.TradingAccountId = v
}

// GetCurrency returns the Currency field value
func (o *PortfolioSummary) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PortfolioSummary) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PortfolioSummary) SetCurrency(v string) {
	o.Currency = v
}

// GetLeverage returns the Leverage field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *PortfolioSummary) GetLeverage() int32 {
	if o == nil || o.Leverage.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Leverage.Get()
}

// GetLeverageOk returns a tuple with the Leverage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PortfolioSummary) GetLeverageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Leverage.Get(), o.Leverage.IsSet()
}

// SetLeverage sets field value
func (o *PortfolioSummary) SetLeverage(v int32) {
	o.Leverage.Set(&v)
}

// GetEquity returns the Equity field value
func (o *PortfolioSummary) GetEquity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Equity
}

// GetEquityOk returns a tuple with the Equity field value
// and a boolean to check if the value has been set.
func (o *PortfolioSummary) GetEquityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Equity, true
}

// SetEquity sets field value
func (o *PortfolioSummary) SetEquity(v string) {
	o.Equity = v
}

// GetMargin returns the Margin field value
func (o *PortfolioSummary) GetMargin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Margin
}

// GetMarginOk returns a tuple with the Margin field value
// and a boolean to check if the value has been set.
func (o *PortfolioSummary) GetMarginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Margin, true
}

// SetMargin sets field value
func (o *PortfolioSummary) SetMargin(v string) {
	o.Margin = v
}

// GetMarginLoan returns the MarginLoan field value
func (o *PortfolioSummary) GetMarginLoan() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MarginLoan
}

// GetMarginLoanOk returns a tuple with the MarginLoan field value
// and a boolean to check if the value has been set.
func (o *PortfolioSummary) GetMarginLoanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MarginLoan, true
}

// SetMarginLoan sets field value
func (o *PortfolioSummary) SetMarginLoan(v string) {
	o.MarginLoan = v
}

// GetMarginUsage returns the MarginUsage field value
func (o *PortfolioSummary) GetMarginUsage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MarginUsage
}

// GetMarginUsageOk returns a tuple with the MarginUsage field value
// and a boolean to check if the value has been set.
func (o *PortfolioSummary) GetMarginUsageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MarginUsage, true
}

// SetMarginUsage sets field value
func (o *PortfolioSummary) SetMarginUsage(v string) {
	o.MarginUsage = v
}

// GetMarginRequirement returns the MarginRequirement field value
func (o *PortfolioSummary) GetMarginRequirement() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MarginRequirement
}

// GetMarginRequirementOk returns a tuple with the MarginRequirement field value
// and a boolean to check if the value has been set.
func (o *PortfolioSummary) GetMarginRequirementOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MarginRequirement, true
}

// SetMarginRequirement sets field value
func (o *PortfolioSummary) SetMarginRequirement(v string) {
	o.MarginRequirement = v
}

// GetMarginLevel returns the MarginLevel field value
func (o *PortfolioSummary) GetMarginLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MarginLevel
}

// GetMarginLevelOk returns a tuple with the MarginLevel field value
// and a boolean to check if the value has been set.
func (o *PortfolioSummary) GetMarginLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MarginLevel, true
}

// SetMarginLevel sets field value
func (o *PortfolioSummary) SetMarginLevel(v string) {
	o.MarginLevel = v
}

// GetCredit returns the Credit field value
func (o *PortfolioSummary) GetCredit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Credit
}

// GetCreditOk returns a tuple with the Credit field value
// and a boolean to check if the value has been set.
func (o *PortfolioSummary) GetCreditOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credit, true
}

// SetCredit sets field value
func (o *PortfolioSummary) SetCredit(v string) {
	o.Credit = v
}

// GetRiskExposure returns the RiskExposure field value
func (o *PortfolioSummary) GetRiskExposure() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RiskExposure
}

// GetRiskExposureOk returns a tuple with the RiskExposure field value
// and a boolean to check if the value has been set.
func (o *PortfolioSummary) GetRiskExposureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RiskExposure, true
}

// SetRiskExposure sets field value
func (o *PortfolioSummary) SetRiskExposure(v string) {
	o.RiskExposure = v
}

// GetMaxRiskExposure returns the MaxRiskExposure field value if set, zero value otherwise.
func (o *PortfolioSummary) GetMaxRiskExposure() string {
	if o == nil || IsNil(o.MaxRiskExposure) {
		var ret string
		return ret
	}
	return *o.MaxRiskExposure
}

// GetMaxRiskExposureOk returns a tuple with the MaxRiskExposure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortfolioSummary) GetMaxRiskExposureOk() (*string, bool) {
	if o == nil || IsNil(o.MaxRiskExposure) {
		return nil, false
	}
	return o.MaxRiskExposure, true
}

// HasMaxRiskExposure returns a boolean if a field has been set.
func (o *PortfolioSummary) HasMaxRiskExposure() bool {
	if o != nil && !IsNil(o.MaxRiskExposure) {
		return true
	}

	return false
}

// SetMaxRiskExposure gets a reference to the given string and assigns it to the MaxRiskExposure field.
func (o *PortfolioSummary) SetMaxRiskExposure(v string) {
	o.MaxRiskExposure = &v
}

// GetRiskExposureRate returns the RiskExposureRate field value if set, zero value otherwise.
func (o *PortfolioSummary) GetRiskExposureRate() string {
	if o == nil || IsNil(o.RiskExposureRate) {
		var ret string
		return ret
	}
	return *o.RiskExposureRate
}

// GetRiskExposureRateOk returns a tuple with the RiskExposureRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortfolioSummary) GetRiskExposureRateOk() (*string, bool) {
	if o == nil || IsNil(o.RiskExposureRate) {
		return nil, false
	}
	return o.RiskExposureRate, true
}

// HasRiskExposureRate returns a boolean if a field has been set.
func (o *PortfolioSummary) HasRiskExposureRate() bool {
	if o != nil && !IsNil(o.RiskExposureRate) {
		return true
	}

	return false
}

// SetRiskExposureRate gets a reference to the given string and assigns it to the RiskExposureRate field.
func (o *PortfolioSummary) SetRiskExposureRate(v string) {
	o.RiskExposureRate = &v
}

func (o PortfolioSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PortfolioSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tradingAccountId"] = o.TradingAccountId
	toSerialize["currency"] = o.Currency
	toSerialize["leverage"] = o.Leverage.Get()
	toSerialize["equity"] = o.Equity
	toSerialize["margin"] = o.Margin
	toSerialize["marginLoan"] = o.MarginLoan
	toSerialize["marginUsage"] = o.MarginUsage
	toSerialize["marginRequirement"] = o.MarginRequirement
	toSerialize["marginLevel"] = o.MarginLevel
	toSerialize["credit"] = o.Credit
	toSerialize["riskExposure"] = o.RiskExposure
	if !IsNil(o.MaxRiskExposure) {
		toSerialize["maxRiskExposure"] = o.MaxRiskExposure
	}
	if !IsNil(o.RiskExposureRate) {
		toSerialize["riskExposureRate"] = o.RiskExposureRate
	}
	return toSerialize, nil
}

func (o *PortfolioSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tradingAccountId",
		"currency",
		"leverage",
		"equity",
		"margin",
		"marginLoan",
		"marginUsage",
		"marginRequirement",
		"marginLevel",
		"credit",
		"riskExposure",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPortfolioSummary := _PortfolioSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPortfolioSummary)

	if err != nil {
		return err
	}

	*o = PortfolioSummary(varPortfolioSummary)

	return err
}

type NullablePortfolioSummary struct {
	value *PortfolioSummary
	isSet bool
}

func (v NullablePortfolioSummary) Get() *PortfolioSummary {
	return v.value
}

func (v *NullablePortfolioSummary) Set(val *PortfolioSummary) {
	v.value = val
	v.isSet = true
}

func (v NullablePortfolioSummary) IsSet() bool {
	return v.isSet
}

func (v *NullablePortfolioSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePortfolioSummary(val *PortfolioSummary) *NullablePortfolioSummary {
	return &NullablePortfolioSummary{value: val, isSet: true}
}

func (v NullablePortfolioSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePortfolioSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


