/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the RpcListCredentialsParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpcListCredentialsParams{}

// RpcListCredentialsParams Request to list credentials
type RpcListCredentialsParams struct {
	CredentialIds []string `json:"credentialIds,omitempty"`
	Venue *Venue `json:"venue,omitempty"`
	CredentialType NullableCredentialType `json:"credentialType,omitempty"`
	Status *CredentialStatus `json:"status,omitempty"`
	Pagination *RpcPagination `json:"pagination,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RpcListCredentialsParams RpcListCredentialsParams

// NewRpcListCredentialsParams instantiates a new RpcListCredentialsParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpcListCredentialsParams() *RpcListCredentialsParams {
	this := RpcListCredentialsParams{}
	return &this
}

// NewRpcListCredentialsParamsWithDefaults instantiates a new RpcListCredentialsParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpcListCredentialsParamsWithDefaults() *RpcListCredentialsParams {
	this := RpcListCredentialsParams{}
	return &this
}

// GetCredentialIds returns the CredentialIds field value if set, zero value otherwise.
func (o *RpcListCredentialsParams) GetCredentialIds() []string {
	if o == nil || IsNil(o.CredentialIds) {
		var ret []string
		return ret
	}
	return o.CredentialIds
}

// GetCredentialIdsOk returns a tuple with the CredentialIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcListCredentialsParams) GetCredentialIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.CredentialIds) {
		return nil, false
	}
	return o.CredentialIds, true
}

// HasCredentialIds returns a boolean if a field has been set.
func (o *RpcListCredentialsParams) HasCredentialIds() bool {
	if o != nil && !IsNil(o.CredentialIds) {
		return true
	}

	return false
}

// SetCredentialIds gets a reference to the given []string and assigns it to the CredentialIds field.
func (o *RpcListCredentialsParams) SetCredentialIds(v []string) {
	o.CredentialIds = v
}

// GetVenue returns the Venue field value if set, zero value otherwise.
func (o *RpcListCredentialsParams) GetVenue() Venue {
	if o == nil || IsNil(o.Venue) {
		var ret Venue
		return ret
	}
	return *o.Venue
}

// GetVenueOk returns a tuple with the Venue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcListCredentialsParams) GetVenueOk() (*Venue, bool) {
	if o == nil || IsNil(o.Venue) {
		return nil, false
	}
	return o.Venue, true
}

// HasVenue returns a boolean if a field has been set.
func (o *RpcListCredentialsParams) HasVenue() bool {
	if o != nil && !IsNil(o.Venue) {
		return true
	}

	return false
}

// SetVenue gets a reference to the given Venue and assigns it to the Venue field.
func (o *RpcListCredentialsParams) SetVenue(v Venue) {
	o.Venue = &v
}

// GetCredentialType returns the CredentialType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RpcListCredentialsParams) GetCredentialType() CredentialType {
	if o == nil || IsNil(o.CredentialType.Get()) {
		var ret CredentialType
		return ret
	}
	return *o.CredentialType.Get()
}

// GetCredentialTypeOk returns a tuple with the CredentialType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RpcListCredentialsParams) GetCredentialTypeOk() (*CredentialType, bool) {
	if o == nil {
		return nil, false
	}
	return o.CredentialType.Get(), o.CredentialType.IsSet()
}

// HasCredentialType returns a boolean if a field has been set.
func (o *RpcListCredentialsParams) HasCredentialType() bool {
	if o != nil && o.CredentialType.IsSet() {
		return true
	}

	return false
}

// SetCredentialType gets a reference to the given NullableCredentialType and assigns it to the CredentialType field.
func (o *RpcListCredentialsParams) SetCredentialType(v CredentialType) {
	o.CredentialType.Set(&v)
}
// SetCredentialTypeNil sets the value for CredentialType to be an explicit nil
func (o *RpcListCredentialsParams) SetCredentialTypeNil() {
	o.CredentialType.Set(nil)
}

// UnsetCredentialType ensures that no value is present for CredentialType, not even an explicit nil
func (o *RpcListCredentialsParams) UnsetCredentialType() {
	o.CredentialType.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RpcListCredentialsParams) GetStatus() CredentialStatus {
	if o == nil || IsNil(o.Status) {
		var ret CredentialStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcListCredentialsParams) GetStatusOk() (*CredentialStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RpcListCredentialsParams) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given CredentialStatus and assigns it to the Status field.
func (o *RpcListCredentialsParams) SetStatus(v CredentialStatus) {
	o.Status = &v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *RpcListCredentialsParams) GetPagination() RpcPagination {
	if o == nil || IsNil(o.Pagination) {
		var ret RpcPagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcListCredentialsParams) GetPaginationOk() (*RpcPagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *RpcListCredentialsParams) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given RpcPagination and assigns it to the Pagination field.
func (o *RpcListCredentialsParams) SetPagination(v RpcPagination) {
	o.Pagination = &v
}

func (o RpcListCredentialsParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpcListCredentialsParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CredentialIds) {
		toSerialize["credentialIds"] = o.CredentialIds
	}
	if !IsNil(o.Venue) {
		toSerialize["venue"] = o.Venue
	}
	if o.CredentialType.IsSet() {
		toSerialize["credentialType"] = o.CredentialType.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RpcListCredentialsParams) UnmarshalJSON(data []byte) (err error) {
	varRpcListCredentialsParams := _RpcListCredentialsParams{}

	err = json.Unmarshal(data, &varRpcListCredentialsParams)

	if err != nil {
		return err
	}

	*o = RpcListCredentialsParams(varRpcListCredentialsParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "credentialIds")
		delete(additionalProperties, "venue")
		delete(additionalProperties, "credentialType")
		delete(additionalProperties, "status")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRpcListCredentialsParams struct {
	value *RpcListCredentialsParams
	isSet bool
}

func (v NullableRpcListCredentialsParams) Get() *RpcListCredentialsParams {
	return v.value
}

func (v *NullableRpcListCredentialsParams) Set(val *RpcListCredentialsParams) {
	v.value = val
	v.isSet = true
}

func (v NullableRpcListCredentialsParams) IsSet() bool {
	return v.isSet
}

func (v *NullableRpcListCredentialsParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpcListCredentialsParams(val *RpcListCredentialsParams) *NullableRpcListCredentialsParams {
	return &NullableRpcListCredentialsParams{value: val, isSet: true}
}

func (v NullableRpcListCredentialsParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpcListCredentialsParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


