/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the RpcCredentialUpdatedEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpcCredentialUpdatedEvent{}

// RpcCredentialUpdatedEvent Credential update event (pushed via WebSocket)
type RpcCredentialUpdatedEvent struct {
	Data *RpcTradingAccountCredential `json:"data,omitempty"`
}

// NewRpcCredentialUpdatedEvent instantiates a new RpcCredentialUpdatedEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpcCredentialUpdatedEvent() *RpcCredentialUpdatedEvent {
	this := RpcCredentialUpdatedEvent{}
	return &this
}

// NewRpcCredentialUpdatedEventWithDefaults instantiates a new RpcCredentialUpdatedEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpcCredentialUpdatedEventWithDefaults() *RpcCredentialUpdatedEvent {
	this := RpcCredentialUpdatedEvent{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RpcCredentialUpdatedEvent) GetData() RpcTradingAccountCredential {
	if o == nil || IsNil(o.Data) {
		var ret RpcTradingAccountCredential
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcCredentialUpdatedEvent) GetDataOk() (*RpcTradingAccountCredential, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RpcCredentialUpdatedEvent) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given RpcTradingAccountCredential and assigns it to the Data field.
func (o *RpcCredentialUpdatedEvent) SetData(v RpcTradingAccountCredential) {
	o.Data = &v
}

func (o RpcCredentialUpdatedEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpcCredentialUpdatedEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableRpcCredentialUpdatedEvent struct {
	value *RpcCredentialUpdatedEvent
	isSet bool
}

func (v NullableRpcCredentialUpdatedEvent) Get() *RpcCredentialUpdatedEvent {
	return v.value
}

func (v *NullableRpcCredentialUpdatedEvent) Set(val *RpcCredentialUpdatedEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableRpcCredentialUpdatedEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableRpcCredentialUpdatedEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpcCredentialUpdatedEvent(val *RpcCredentialUpdatedEvent) *NullableRpcCredentialUpdatedEvent {
	return &NullableRpcCredentialUpdatedEvent{value: val, isSet: true}
}

func (v NullableRpcCredentialUpdatedEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpcCredentialUpdatedEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


