/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// TradingAccountCredentialStatus Status of the trading account credential
type TradingAccountCredentialStatus string

// List of tradingAccountCredentialStatus
const (
	TRADINGACCOUNTCREDENTIALSTATUS_CREATED TradingAccountCredentialStatus = "CREATED"
	TRADINGACCOUNTCREDENTIALSTATUS_REVOKED TradingAccountCredentialStatus = "REVOKED"
)

// All allowed values of TradingAccountCredentialStatus enum
var AllowedTradingAccountCredentialStatusEnumValues = []TradingAccountCredentialStatus{
	"CREATED",
	"REVOKED",
}

func (v *TradingAccountCredentialStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TradingAccountCredentialStatus(value)
	for _, existing := range AllowedTradingAccountCredentialStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TradingAccountCredentialStatus", value)
}

// NewTradingAccountCredentialStatusFromValue returns a pointer to a valid TradingAccountCredentialStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTradingAccountCredentialStatusFromValue(v string) (*TradingAccountCredentialStatus, error) {
	ev := TradingAccountCredentialStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TradingAccountCredentialStatus: valid values are %v", v, AllowedTradingAccountCredentialStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TradingAccountCredentialStatus) IsValid() bool {
	for _, existing := range AllowedTradingAccountCredentialStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to tradingAccountCredentialStatus value
func (v TradingAccountCredentialStatus) Ptr() *TradingAccountCredentialStatus {
	return &v
}

type NullableTradingAccountCredentialStatus struct {
	value *TradingAccountCredentialStatus
	isSet bool
}

func (v NullableTradingAccountCredentialStatus) Get() *TradingAccountCredentialStatus {
	return v.value
}

func (v *NullableTradingAccountCredentialStatus) Set(val *TradingAccountCredentialStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableTradingAccountCredentialStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableTradingAccountCredentialStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTradingAccountCredentialStatus(val *TradingAccountCredentialStatus) *NullableTradingAccountCredentialStatus {
	return &NullableTradingAccountCredentialStatus{value: val, isSet: true}
}

func (v NullableTradingAccountCredentialStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTradingAccountCredentialStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

