/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListMarketOrderBooks200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMarketOrderBooks200Response{}

// ListMarketOrderBooks200Response struct for ListMarketOrderBooks200Response
type ListMarketOrderBooks200Response struct {
	// Indicates if the operation was successful
	Success bool `json:"success"`
	// Error code (0 for success, negative for errors)
	Errno int32 `json:"errno"`
	// Error message (null for successful operations)
	Error NullableString `json:"error"`
	Details NullableBaseResponseDetails `json:"details,omitempty"`
	Data []Orderbook `json:"data,omitempty"`
}

type _ListMarketOrderBooks200Response ListMarketOrderBooks200Response

// NewListMarketOrderBooks200Response instantiates a new ListMarketOrderBooks200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMarketOrderBooks200Response(success bool, errno int32, error_ NullableString) *ListMarketOrderBooks200Response {
	this := ListMarketOrderBooks200Response{}
	this.Success = success
	this.Errno = errno
	this.Error = error_
	return &this
}

// NewListMarketOrderBooks200ResponseWithDefaults instantiates a new ListMarketOrderBooks200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMarketOrderBooks200ResponseWithDefaults() *ListMarketOrderBooks200Response {
	this := ListMarketOrderBooks200Response{}
	return &this
}

// GetSuccess returns the Success field value
func (o *ListMarketOrderBooks200Response) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *ListMarketOrderBooks200Response) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ListMarketOrderBooks200Response) SetSuccess(v bool) {
	o.Success = v
}

// GetErrno returns the Errno field value
func (o *ListMarketOrderBooks200Response) GetErrno() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Errno
}

// GetErrnoOk returns a tuple with the Errno field value
// and a boolean to check if the value has been set.
func (o *ListMarketOrderBooks200Response) GetErrnoOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Errno, true
}

// SetErrno sets field value
func (o *ListMarketOrderBooks200Response) SetErrno(v int32) {
	o.Errno = v
}

// GetError returns the Error field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListMarketOrderBooks200Response) GetError() string {
	if o == nil || o.Error.Get() == nil {
		var ret string
		return ret
	}

	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListMarketOrderBooks200Response) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// SetError sets field value
func (o *ListMarketOrderBooks200Response) SetError(v string) {
	o.Error.Set(&v)
}

// GetDetails returns the Details field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListMarketOrderBooks200Response) GetDetails() BaseResponseDetails {
	if o == nil || IsNil(o.Details.Get()) {
		var ret BaseResponseDetails
		return ret
	}
	return *o.Details.Get()
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListMarketOrderBooks200Response) GetDetailsOk() (*BaseResponseDetails, bool) {
	if o == nil {
		return nil, false
	}
	return o.Details.Get(), o.Details.IsSet()
}

// HasDetails returns a boolean if a field has been set.
func (o *ListMarketOrderBooks200Response) HasDetails() bool {
	if o != nil && o.Details.IsSet() {
		return true
	}

	return false
}

// SetDetails gets a reference to the given NullableBaseResponseDetails and assigns it to the Details field.
func (o *ListMarketOrderBooks200Response) SetDetails(v BaseResponseDetails) {
	o.Details.Set(&v)
}
// SetDetailsNil sets the value for Details to be an explicit nil
func (o *ListMarketOrderBooks200Response) SetDetailsNil() {
	o.Details.Set(nil)
}

// UnsetDetails ensures that no value is present for Details, not even an explicit nil
func (o *ListMarketOrderBooks200Response) UnsetDetails() {
	o.Details.Unset()
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListMarketOrderBooks200Response) GetData() []Orderbook {
	if o == nil || IsNil(o.Data) {
		var ret []Orderbook
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMarketOrderBooks200Response) GetDataOk() ([]Orderbook, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListMarketOrderBooks200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Orderbook and assigns it to the Data field.
func (o *ListMarketOrderBooks200Response) SetData(v []Orderbook) {
	o.Data = v
}

func (o ListMarketOrderBooks200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMarketOrderBooks200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["errno"] = o.Errno
	toSerialize["error"] = o.Error.Get()
	if o.Details.IsSet() {
		toSerialize["details"] = o.Details.Get()
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

func (o *ListMarketOrderBooks200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"errno",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListMarketOrderBooks200Response := _ListMarketOrderBooks200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListMarketOrderBooks200Response)

	if err != nil {
		return err
	}

	*o = ListMarketOrderBooks200Response(varListMarketOrderBooks200Response)

	return err
}

type NullableListMarketOrderBooks200Response struct {
	value *ListMarketOrderBooks200Response
	isSet bool
}

func (v NullableListMarketOrderBooks200Response) Get() *ListMarketOrderBooks200Response {
	return v.value
}

func (v *NullableListMarketOrderBooks200Response) Set(val *ListMarketOrderBooks200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListMarketOrderBooks200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListMarketOrderBooks200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMarketOrderBooks200Response(val *ListMarketOrderBooks200Response) *NullableListMarketOrderBooks200Response {
	return &NullableListMarketOrderBooks200Response{value: val, isSet: true}
}

func (v NullableListMarketOrderBooks200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMarketOrderBooks200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


