/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the FermataCreateWalletRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FermataCreateWalletRequest{}

// FermataCreateWalletRequest Create a new wallet
type FermataCreateWalletRequest struct {
	// Nickname for the new wallet
	Nickname *string `json:"nickname,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FermataCreateWalletRequest FermataCreateWalletRequest

// NewFermataCreateWalletRequest instantiates a new FermataCreateWalletRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFermataCreateWalletRequest() *FermataCreateWalletRequest {
	this := FermataCreateWalletRequest{}
	return &this
}

// NewFermataCreateWalletRequestWithDefaults instantiates a new FermataCreateWalletRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFermataCreateWalletRequestWithDefaults() *FermataCreateWalletRequest {
	this := FermataCreateWalletRequest{}
	return &this
}

// GetNickname returns the Nickname field value if set, zero value otherwise.
func (o *FermataCreateWalletRequest) GetNickname() string {
	if o == nil || IsNil(o.Nickname) {
		var ret string
		return ret
	}
	return *o.Nickname
}

// GetNicknameOk returns a tuple with the Nickname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FermataCreateWalletRequest) GetNicknameOk() (*string, bool) {
	if o == nil || IsNil(o.Nickname) {
		return nil, false
	}
	return o.Nickname, true
}

// HasNickname returns a boolean if a field has been set.
func (o *FermataCreateWalletRequest) HasNickname() bool {
	if o != nil && !IsNil(o.Nickname) {
		return true
	}

	return false
}

// SetNickname gets a reference to the given string and assigns it to the Nickname field.
func (o *FermataCreateWalletRequest) SetNickname(v string) {
	o.Nickname = &v
}

func (o FermataCreateWalletRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FermataCreateWalletRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Nickname) {
		toSerialize["nickname"] = o.Nickname
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FermataCreateWalletRequest) UnmarshalJSON(data []byte) (err error) {
	varFermataCreateWalletRequest := _FermataCreateWalletRequest{}

	err = json.Unmarshal(data, &varFermataCreateWalletRequest)

	if err != nil {
		return err
	}

	*o = FermataCreateWalletRequest(varFermataCreateWalletRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "nickname")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFermataCreateWalletRequest struct {
	value *FermataCreateWalletRequest
	isSet bool
}

func (v NullableFermataCreateWalletRequest) Get() *FermataCreateWalletRequest {
	return v.value
}

func (v *NullableFermataCreateWalletRequest) Set(val *FermataCreateWalletRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFermataCreateWalletRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFermataCreateWalletRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFermataCreateWalletRequest(val *FermataCreateWalletRequest) *NullableFermataCreateWalletRequest {
	return &NullableFermataCreateWalletRequest{value: val, isSet: true}
}

func (v NullableFermataCreateWalletRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFermataCreateWalletRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


