/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnableMarketInstrumentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnableMarketInstrumentRequest{}

// EnableMarketInstrumentRequest struct for EnableMarketInstrumentRequest
type EnableMarketInstrumentRequest struct {
	// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
	InstrumentId string `json:"instrumentId"`
}

type _EnableMarketInstrumentRequest EnableMarketInstrumentRequest

// NewEnableMarketInstrumentRequest instantiates a new EnableMarketInstrumentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnableMarketInstrumentRequest(instrumentId string) *EnableMarketInstrumentRequest {
	this := EnableMarketInstrumentRequest{}
	this.InstrumentId = instrumentId
	return &this
}

// NewEnableMarketInstrumentRequestWithDefaults instantiates a new EnableMarketInstrumentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnableMarketInstrumentRequestWithDefaults() *EnableMarketInstrumentRequest {
	this := EnableMarketInstrumentRequest{}
	return &this
}

// GetInstrumentId returns the InstrumentId field value
func (o *EnableMarketInstrumentRequest) GetInstrumentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstrumentId
}

// GetInstrumentIdOk returns a tuple with the InstrumentId field value
// and a boolean to check if the value has been set.
func (o *EnableMarketInstrumentRequest) GetInstrumentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstrumentId, true
}

// SetInstrumentId sets field value
func (o *EnableMarketInstrumentRequest) SetInstrumentId(v string) {
	o.InstrumentId = v
}

func (o EnableMarketInstrumentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnableMarketInstrumentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instrumentId"] = o.InstrumentId
	return toSerialize, nil
}

func (o *EnableMarketInstrumentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instrumentId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnableMarketInstrumentRequest := _EnableMarketInstrumentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnableMarketInstrumentRequest)

	if err != nil {
		return err
	}

	*o = EnableMarketInstrumentRequest(varEnableMarketInstrumentRequest)

	return err
}

type NullableEnableMarketInstrumentRequest struct {
	value *EnableMarketInstrumentRequest
	isSet bool
}

func (v NullableEnableMarketInstrumentRequest) Get() *EnableMarketInstrumentRequest {
	return v.value
}

func (v *NullableEnableMarketInstrumentRequest) Set(val *EnableMarketInstrumentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnableMarketInstrumentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnableMarketInstrumentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnableMarketInstrumentRequest(val *EnableMarketInstrumentRequest) *NullableEnableMarketInstrumentRequest {
	return &NullableEnableMarketInstrumentRequest{value: val, isSet: true}
}

func (v NullableEnableMarketInstrumentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnableMarketInstrumentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


