/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// KlineInterval Kline (candlestick) interval. Not all venues support every interval — refer to the venue's connector for the supported set.
type KlineInterval string

// List of klineInterval
const (
	KLINEINTERVAL_SECOND_1 KlineInterval = "1s"
	KLINEINTERVAL_MINUTE_1 KlineInterval = "1m"
	KLINEINTERVAL_MINUTE_3 KlineInterval = "3m"
	KLINEINTERVAL_MINUTE_5 KlineInterval = "5m"
	KLINEINTERVAL_MINUTE_15 KlineInterval = "15m"
	KLINEINTERVAL_MINUTE_30 KlineInterval = "30m"
	KLINEINTERVAL_HOUR_1 KlineInterval = "1h"
	KLINEINTERVAL_HOUR_2 KlineInterval = "2h"
	KLINEINTERVAL_HOUR_4 KlineInterval = "4h"
	KLINEINTERVAL_HOUR_6 KlineInterval = "6h"
	KLINEINTERVAL_HOUR_8 KlineInterval = "8h"
	KLINEINTERVAL_HOUR_12 KlineInterval = "12h"
	KLINEINTERVAL_DAY_1 KlineInterval = "1d"
	KLINEINTERVAL_DAY_3 KlineInterval = "3d"
	KLINEINTERVAL_WEEK_1 KlineInterval = "1w"
	KLINEINTERVAL_MONTH_1 KlineInterval = "1M"
)

// All allowed values of KlineInterval enum
var AllowedKlineIntervalEnumValues = []KlineInterval{
	"1s",
	"1m",
	"3m",
	"5m",
	"15m",
	"30m",
	"1h",
	"2h",
	"4h",
	"6h",
	"8h",
	"12h",
	"1d",
	"3d",
	"1w",
	"1M",
}

func (v *KlineInterval) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := KlineInterval(value)
	for _, existing := range AllowedKlineIntervalEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid KlineInterval", value)
}

// NewKlineIntervalFromValue returns a pointer to a valid KlineInterval
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewKlineIntervalFromValue(v string) (*KlineInterval, error) {
	ev := KlineInterval(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for KlineInterval: valid values are %v", v, AllowedKlineIntervalEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v KlineInterval) IsValid() bool {
	for _, existing := range AllowedKlineIntervalEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to klineInterval value
func (v KlineInterval) Ptr() *KlineInterval {
	return &v
}

type NullableKlineInterval struct {
	value *KlineInterval
	isSet bool
}

func (v NullableKlineInterval) Get() *KlineInterval {
	return v.value
}

func (v *NullableKlineInterval) Set(val *KlineInterval) {
	v.value = val
	v.isSet = true
}

func (v NullableKlineInterval) IsSet() bool {
	return v.isSet
}

func (v *NullableKlineInterval) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKlineInterval(val *KlineInterval) *NullableKlineInterval {
	return &NullableKlineInterval{value: val, isSet: true}
}

func (v NullableKlineInterval) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKlineInterval) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

