/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the Quote type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Quote{}

// Quote RFQ quote — a bilateral contract between the user and the dealer with a guaranteed execution price
type Quote struct {
	// UUID string
	QuoteId string `json:"quoteId"`
	// Client-provided reference for idempotency and tracking
	QuoteRequestId *string `json:"quoteRequestId,omitempty"`
	// External quote identifier from upstream venue
	ExternalQuoteId *string `json:"externalQuoteId,omitempty"`
	Venue *Venue `json:"venue,omitempty"`
	// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
	InstrumentId *string `json:"instrumentId,omitempty"`
	// UUID string
	DealerAccountId string `json:"dealerAccountId"`
	// UUID string
	TraderAccountId *string `json:"traderAccountId,omitempty"`
	// Base asset being traded
	BaseAsset string `json:"baseAsset"`
	// Quote asset (payment currency)
	QuoteAsset string `json:"quoteAsset"`
	OrderSide OrderSide `json:"orderSide"`
	QuantityType *QuantityType `json:"quantityType,omitempty"`
	// Positive decimal value as string
	Quantity string `json:"quantity" validate:"regexp=^\\\\d+(\\\\.\\\\d+)?$"`
	// Positive decimal value as string
	QuoteQuantity string `json:"quoteQuantity" validate:"regexp=^\\\\d+(\\\\.\\\\d+)?$"`
	// Positive decimal value as string
	Price string `json:"price" validate:"regexp=^\\\\d+(\\\\.\\\\d+)?$"`
	Status QuoteStatus `json:"status"`
	// Reason for quote rejection, if status is REJECTED
	RejectReason *string `json:"rejectReason,omitempty"`
	// Unix timestamp in milliseconds
	CreatedAt int64 `json:"createdAt"`
	// Quote creation timestamp in ISO 8601 format
	CreatedAtDateTime *time.Time `json:"createdAtDateTime,omitempty"`
	// Unix timestamp in milliseconds
	UpdatedAt *int64 `json:"updatedAt,omitempty"`
	// Last update timestamp in ISO 8601 format
	UpdatedAtDateTime *time.Time `json:"updatedAtDateTime,omitempty"`
	// Unix timestamp in milliseconds
	ExpireAt int64 `json:"expireAt"`
	// Quote expiration timestamp in ISO 8601 format
	ExpireAtDateTime *time.Time `json:"expireAtDateTime,omitempty"`
	// UUID string
	PricingProfileId *string `json:"pricingProfileId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Quote Quote

// NewQuote instantiates a new Quote object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuote(quoteId string, dealerAccountId string, baseAsset string, quoteAsset string, orderSide OrderSide, quantity string, quoteQuantity string, price string, status QuoteStatus, createdAt int64, expireAt int64) *Quote {
	this := Quote{}
	this.QuoteId = quoteId
	this.DealerAccountId = dealerAccountId
	this.BaseAsset = baseAsset
	this.QuoteAsset = quoteAsset
	this.OrderSide = orderSide
	this.Quantity = quantity
	this.QuoteQuantity = quoteQuantity
	this.Price = price
	this.Status = status
	this.CreatedAt = createdAt
	this.ExpireAt = expireAt
	return &this
}

// NewQuoteWithDefaults instantiates a new Quote object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteWithDefaults() *Quote {
	this := Quote{}
	return &this
}

// GetQuoteId returns the QuoteId field value
func (o *Quote) GetQuoteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteId
}

// GetQuoteIdOk returns a tuple with the QuoteId field value
// and a boolean to check if the value has been set.
func (o *Quote) GetQuoteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteId, true
}

// SetQuoteId sets field value
func (o *Quote) SetQuoteId(v string) {
	o.QuoteId = v
}

// GetQuoteRequestId returns the QuoteRequestId field value if set, zero value otherwise.
func (o *Quote) GetQuoteRequestId() string {
	if o == nil || IsNil(o.QuoteRequestId) {
		var ret string
		return ret
	}
	return *o.QuoteRequestId
}

// GetQuoteRequestIdOk returns a tuple with the QuoteRequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quote) GetQuoteRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.QuoteRequestId) {
		return nil, false
	}
	return o.QuoteRequestId, true
}

// HasQuoteRequestId returns a boolean if a field has been set.
func (o *Quote) HasQuoteRequestId() bool {
	if o != nil && !IsNil(o.QuoteRequestId) {
		return true
	}

	return false
}

// SetQuoteRequestId gets a reference to the given string and assigns it to the QuoteRequestId field.
func (o *Quote) SetQuoteRequestId(v string) {
	o.QuoteRequestId = &v
}

// GetExternalQuoteId returns the ExternalQuoteId field value if set, zero value otherwise.
func (o *Quote) GetExternalQuoteId() string {
	if o == nil || IsNil(o.ExternalQuoteId) {
		var ret string
		return ret
	}
	return *o.ExternalQuoteId
}

// GetExternalQuoteIdOk returns a tuple with the ExternalQuoteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quote) GetExternalQuoteIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalQuoteId) {
		return nil, false
	}
	return o.ExternalQuoteId, true
}

// HasExternalQuoteId returns a boolean if a field has been set.
func (o *Quote) HasExternalQuoteId() bool {
	if o != nil && !IsNil(o.ExternalQuoteId) {
		return true
	}

	return false
}

// SetExternalQuoteId gets a reference to the given string and assigns it to the ExternalQuoteId field.
func (o *Quote) SetExternalQuoteId(v string) {
	o.ExternalQuoteId = &v
}

// GetVenue returns the Venue field value if set, zero value otherwise.
func (o *Quote) GetVenue() Venue {
	if o == nil || IsNil(o.Venue) {
		var ret Venue
		return ret
	}
	return *o.Venue
}

// GetVenueOk returns a tuple with the Venue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quote) GetVenueOk() (*Venue, bool) {
	if o == nil || IsNil(o.Venue) {
		return nil, false
	}
	return o.Venue, true
}

// HasVenue returns a boolean if a field has been set.
func (o *Quote) HasVenue() bool {
	if o != nil && !IsNil(o.Venue) {
		return true
	}

	return false
}

// SetVenue gets a reference to the given Venue and assigns it to the Venue field.
func (o *Quote) SetVenue(v Venue) {
	o.Venue = &v
}

// GetInstrumentId returns the InstrumentId field value if set, zero value otherwise.
func (o *Quote) GetInstrumentId() string {
	if o == nil || IsNil(o.InstrumentId) {
		var ret string
		return ret
	}
	return *o.InstrumentId
}

// GetInstrumentIdOk returns a tuple with the InstrumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quote) GetInstrumentIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstrumentId) {
		return nil, false
	}
	return o.InstrumentId, true
}

// HasInstrumentId returns a boolean if a field has been set.
func (o *Quote) HasInstrumentId() bool {
	if o != nil && !IsNil(o.InstrumentId) {
		return true
	}

	return false
}

// SetInstrumentId gets a reference to the given string and assigns it to the InstrumentId field.
func (o *Quote) SetInstrumentId(v string) {
	o.InstrumentId = &v
}

// GetDealerAccountId returns the DealerAccountId field value
func (o *Quote) GetDealerAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DealerAccountId
}

// GetDealerAccountIdOk returns a tuple with the DealerAccountId field value
// and a boolean to check if the value has been set.
func (o *Quote) GetDealerAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DealerAccountId, true
}

// SetDealerAccountId sets field value
func (o *Quote) SetDealerAccountId(v string) {
	o.DealerAccountId = v
}

// GetTraderAccountId returns the TraderAccountId field value if set, zero value otherwise.
func (o *Quote) GetTraderAccountId() string {
	if o == nil || IsNil(o.TraderAccountId) {
		var ret string
		return ret
	}
	return *o.TraderAccountId
}

// GetTraderAccountIdOk returns a tuple with the TraderAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quote) GetTraderAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.TraderAccountId) {
		return nil, false
	}
	return o.TraderAccountId, true
}

// HasTraderAccountId returns a boolean if a field has been set.
func (o *Quote) HasTraderAccountId() bool {
	if o != nil && !IsNil(o.TraderAccountId) {
		return true
	}

	return false
}

// SetTraderAccountId gets a reference to the given string and assigns it to the TraderAccountId field.
func (o *Quote) SetTraderAccountId(v string) {
	o.TraderAccountId = &v
}

// GetBaseAsset returns the BaseAsset field value
func (o *Quote) GetBaseAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseAsset
}

// GetBaseAssetOk returns a tuple with the BaseAsset field value
// and a boolean to check if the value has been set.
func (o *Quote) GetBaseAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseAsset, true
}

// SetBaseAsset sets field value
func (o *Quote) SetBaseAsset(v string) {
	o.BaseAsset = v
}

// GetQuoteAsset returns the QuoteAsset field value
func (o *Quote) GetQuoteAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteAsset
}

// GetQuoteAssetOk returns a tuple with the QuoteAsset field value
// and a boolean to check if the value has been set.
func (o *Quote) GetQuoteAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteAsset, true
}

// SetQuoteAsset sets field value
func (o *Quote) SetQuoteAsset(v string) {
	o.QuoteAsset = v
}

// GetOrderSide returns the OrderSide field value
func (o *Quote) GetOrderSide() OrderSide {
	if o == nil {
		var ret OrderSide
		return ret
	}

	return o.OrderSide
}

// GetOrderSideOk returns a tuple with the OrderSide field value
// and a boolean to check if the value has been set.
func (o *Quote) GetOrderSideOk() (*OrderSide, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderSide, true
}

// SetOrderSide sets field value
func (o *Quote) SetOrderSide(v OrderSide) {
	o.OrderSide = v
}

// GetQuantityType returns the QuantityType field value if set, zero value otherwise.
func (o *Quote) GetQuantityType() QuantityType {
	if o == nil || IsNil(o.QuantityType) {
		var ret QuantityType
		return ret
	}
	return *o.QuantityType
}

// GetQuantityTypeOk returns a tuple with the QuantityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quote) GetQuantityTypeOk() (*QuantityType, bool) {
	if o == nil || IsNil(o.QuantityType) {
		return nil, false
	}
	return o.QuantityType, true
}

// HasQuantityType returns a boolean if a field has been set.
func (o *Quote) HasQuantityType() bool {
	if o != nil && !IsNil(o.QuantityType) {
		return true
	}

	return false
}

// SetQuantityType gets a reference to the given QuantityType and assigns it to the QuantityType field.
func (o *Quote) SetQuantityType(v QuantityType) {
	o.QuantityType = &v
}

// GetQuantity returns the Quantity field value
func (o *Quote) GetQuantity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *Quote) GetQuantityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *Quote) SetQuantity(v string) {
	o.Quantity = v
}

// GetQuoteQuantity returns the QuoteQuantity field value
func (o *Quote) GetQuoteQuantity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteQuantity
}

// GetQuoteQuantityOk returns a tuple with the QuoteQuantity field value
// and a boolean to check if the value has been set.
func (o *Quote) GetQuoteQuantityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteQuantity, true
}

// SetQuoteQuantity sets field value
func (o *Quote) SetQuoteQuantity(v string) {
	o.QuoteQuantity = v
}

// GetPrice returns the Price field value
func (o *Quote) GetPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *Quote) GetPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *Quote) SetPrice(v string) {
	o.Price = v
}

// GetStatus returns the Status field value
func (o *Quote) GetStatus() QuoteStatus {
	if o == nil {
		var ret QuoteStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Quote) GetStatusOk() (*QuoteStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Quote) SetStatus(v QuoteStatus) {
	o.Status = v
}

// GetRejectReason returns the RejectReason field value if set, zero value otherwise.
func (o *Quote) GetRejectReason() string {
	if o == nil || IsNil(o.RejectReason) {
		var ret string
		return ret
	}
	return *o.RejectReason
}

// GetRejectReasonOk returns a tuple with the RejectReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quote) GetRejectReasonOk() (*string, bool) {
	if o == nil || IsNil(o.RejectReason) {
		return nil, false
	}
	return o.RejectReason, true
}

// HasRejectReason returns a boolean if a field has been set.
func (o *Quote) HasRejectReason() bool {
	if o != nil && !IsNil(o.RejectReason) {
		return true
	}

	return false
}

// SetRejectReason gets a reference to the given string and assigns it to the RejectReason field.
func (o *Quote) SetRejectReason(v string) {
	o.RejectReason = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Quote) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Quote) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Quote) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetCreatedAtDateTime returns the CreatedAtDateTime field value if set, zero value otherwise.
func (o *Quote) GetCreatedAtDateTime() time.Time {
	if o == nil || IsNil(o.CreatedAtDateTime) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAtDateTime
}

// GetCreatedAtDateTimeOk returns a tuple with the CreatedAtDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quote) GetCreatedAtDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAtDateTime) {
		return nil, false
	}
	return o.CreatedAtDateTime, true
}

// HasCreatedAtDateTime returns a boolean if a field has been set.
func (o *Quote) HasCreatedAtDateTime() bool {
	if o != nil && !IsNil(o.CreatedAtDateTime) {
		return true
	}

	return false
}

// SetCreatedAtDateTime gets a reference to the given time.Time and assigns it to the CreatedAtDateTime field.
func (o *Quote) SetCreatedAtDateTime(v time.Time) {
	o.CreatedAtDateTime = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Quote) GetUpdatedAt() int64 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int64
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quote) GetUpdatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Quote) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int64 and assigns it to the UpdatedAt field.
func (o *Quote) SetUpdatedAt(v int64) {
	o.UpdatedAt = &v
}

// GetUpdatedAtDateTime returns the UpdatedAtDateTime field value if set, zero value otherwise.
func (o *Quote) GetUpdatedAtDateTime() time.Time {
	if o == nil || IsNil(o.UpdatedAtDateTime) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAtDateTime
}

// GetUpdatedAtDateTimeOk returns a tuple with the UpdatedAtDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quote) GetUpdatedAtDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAtDateTime) {
		return nil, false
	}
	return o.UpdatedAtDateTime, true
}

// HasUpdatedAtDateTime returns a boolean if a field has been set.
func (o *Quote) HasUpdatedAtDateTime() bool {
	if o != nil && !IsNil(o.UpdatedAtDateTime) {
		return true
	}

	return false
}

// SetUpdatedAtDateTime gets a reference to the given time.Time and assigns it to the UpdatedAtDateTime field.
func (o *Quote) SetUpdatedAtDateTime(v time.Time) {
	o.UpdatedAtDateTime = &v
}

// GetExpireAt returns the ExpireAt field value
func (o *Quote) GetExpireAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ExpireAt
}

// GetExpireAtOk returns a tuple with the ExpireAt field value
// and a boolean to check if the value has been set.
func (o *Quote) GetExpireAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpireAt, true
}

// SetExpireAt sets field value
func (o *Quote) SetExpireAt(v int64) {
	o.ExpireAt = v
}

// GetExpireAtDateTime returns the ExpireAtDateTime field value if set, zero value otherwise.
func (o *Quote) GetExpireAtDateTime() time.Time {
	if o == nil || IsNil(o.ExpireAtDateTime) {
		var ret time.Time
		return ret
	}
	return *o.ExpireAtDateTime
}

// GetExpireAtDateTimeOk returns a tuple with the ExpireAtDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quote) GetExpireAtDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpireAtDateTime) {
		return nil, false
	}
	return o.ExpireAtDateTime, true
}

// HasExpireAtDateTime returns a boolean if a field has been set.
func (o *Quote) HasExpireAtDateTime() bool {
	if o != nil && !IsNil(o.ExpireAtDateTime) {
		return true
	}

	return false
}

// SetExpireAtDateTime gets a reference to the given time.Time and assigns it to the ExpireAtDateTime field.
func (o *Quote) SetExpireAtDateTime(v time.Time) {
	o.ExpireAtDateTime = &v
}

// GetPricingProfileId returns the PricingProfileId field value if set, zero value otherwise.
func (o *Quote) GetPricingProfileId() string {
	if o == nil || IsNil(o.PricingProfileId) {
		var ret string
		return ret
	}
	return *o.PricingProfileId
}

// GetPricingProfileIdOk returns a tuple with the PricingProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Quote) GetPricingProfileIdOk() (*string, bool) {
	if o == nil || IsNil(o.PricingProfileId) {
		return nil, false
	}
	return o.PricingProfileId, true
}

// HasPricingProfileId returns a boolean if a field has been set.
func (o *Quote) HasPricingProfileId() bool {
	if o != nil && !IsNil(o.PricingProfileId) {
		return true
	}

	return false
}

// SetPricingProfileId gets a reference to the given string and assigns it to the PricingProfileId field.
func (o *Quote) SetPricingProfileId(v string) {
	o.PricingProfileId = &v
}

func (o Quote) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Quote) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quoteId"] = o.QuoteId
	if !IsNil(o.QuoteRequestId) {
		toSerialize["quoteRequestId"] = o.QuoteRequestId
	}
	if !IsNil(o.ExternalQuoteId) {
		toSerialize["externalQuoteId"] = o.ExternalQuoteId
	}
	if !IsNil(o.Venue) {
		toSerialize["venue"] = o.Venue
	}
	if !IsNil(o.InstrumentId) {
		toSerialize["instrumentId"] = o.InstrumentId
	}
	toSerialize["dealerAccountId"] = o.DealerAccountId
	if !IsNil(o.TraderAccountId) {
		toSerialize["traderAccountId"] = o.TraderAccountId
	}
	toSerialize["baseAsset"] = o.BaseAsset
	toSerialize["quoteAsset"] = o.QuoteAsset
	toSerialize["orderSide"] = o.OrderSide
	if !IsNil(o.QuantityType) {
		toSerialize["quantityType"] = o.QuantityType
	}
	toSerialize["quantity"] = o.Quantity
	toSerialize["quoteQuantity"] = o.QuoteQuantity
	toSerialize["price"] = o.Price
	toSerialize["status"] = o.Status
	if !IsNil(o.RejectReason) {
		toSerialize["rejectReason"] = o.RejectReason
	}
	toSerialize["createdAt"] = o.CreatedAt
	if !IsNil(o.CreatedAtDateTime) {
		toSerialize["createdAtDateTime"] = o.CreatedAtDateTime
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.UpdatedAtDateTime) {
		toSerialize["updatedAtDateTime"] = o.UpdatedAtDateTime
	}
	toSerialize["expireAt"] = o.ExpireAt
	if !IsNil(o.ExpireAtDateTime) {
		toSerialize["expireAtDateTime"] = o.ExpireAtDateTime
	}
	if !IsNil(o.PricingProfileId) {
		toSerialize["pricingProfileId"] = o.PricingProfileId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Quote) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"quoteId",
		"dealerAccountId",
		"baseAsset",
		"quoteAsset",
		"orderSide",
		"quantity",
		"quoteQuantity",
		"price",
		"status",
		"createdAt",
		"expireAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuote := _Quote{}

	err = json.Unmarshal(data, &varQuote)

	if err != nil {
		return err
	}

	*o = Quote(varQuote)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "quoteId")
		delete(additionalProperties, "quoteRequestId")
		delete(additionalProperties, "externalQuoteId")
		delete(additionalProperties, "venue")
		delete(additionalProperties, "instrumentId")
		delete(additionalProperties, "dealerAccountId")
		delete(additionalProperties, "traderAccountId")
		delete(additionalProperties, "baseAsset")
		delete(additionalProperties, "quoteAsset")
		delete(additionalProperties, "orderSide")
		delete(additionalProperties, "quantityType")
		delete(additionalProperties, "quantity")
		delete(additionalProperties, "quoteQuantity")
		delete(additionalProperties, "price")
		delete(additionalProperties, "status")
		delete(additionalProperties, "rejectReason")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "createdAtDateTime")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "updatedAtDateTime")
		delete(additionalProperties, "expireAt")
		delete(additionalProperties, "expireAtDateTime")
		delete(additionalProperties, "pricingProfileId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQuote struct {
	value *Quote
	isSet bool
}

func (v NullableQuote) Get() *Quote {
	return v.value
}

func (v *NullableQuote) Set(val *Quote) {
	v.value = val
	v.isSet = true
}

func (v NullableQuote) IsSet() bool {
	return v.isSet
}

func (v *NullableQuote) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuote(val *Quote) *NullableQuote {
	return &NullableQuote{value: val, isSet: true}
}

func (v NullableQuote) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuote) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


