/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// checks if the FermataPauseDealerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FermataPauseDealerRequest{}

// FermataPauseDealerRequest Pause a dealer
type FermataPauseDealerRequest struct {
	// UUID string
	DealerAccountId string `json:"dealerAccountId"`
	AdditionalProperties map[string]interface{}
}

type _FermataPauseDealerRequest FermataPauseDealerRequest

// NewFermataPauseDealerRequest instantiates a new FermataPauseDealerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFermataPauseDealerRequest(dealerAccountId string) *FermataPauseDealerRequest {
	this := FermataPauseDealerRequest{}
	this.DealerAccountId = dealerAccountId
	return &this
}

// NewFermataPauseDealerRequestWithDefaults instantiates a new FermataPauseDealerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFermataPauseDealerRequestWithDefaults() *FermataPauseDealerRequest {
	this := FermataPauseDealerRequest{}
	return &this
}

// GetDealerAccountId returns the DealerAccountId field value
func (o *FermataPauseDealerRequest) GetDealerAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DealerAccountId
}

// GetDealerAccountIdOk returns a tuple with the DealerAccountId field value
// and a boolean to check if the value has been set.
func (o *FermataPauseDealerRequest) GetDealerAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DealerAccountId, true
}

// SetDealerAccountId sets field value
func (o *FermataPauseDealerRequest) SetDealerAccountId(v string) {
	o.DealerAccountId = v
}

func (o FermataPauseDealerRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FermataPauseDealerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dealerAccountId"] = o.DealerAccountId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FermataPauseDealerRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dealerAccountId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFermataPauseDealerRequest := _FermataPauseDealerRequest{}

	err = json.Unmarshal(data, &varFermataPauseDealerRequest)

	if err != nil {
		return err
	}

	*o = FermataPauseDealerRequest(varFermataPauseDealerRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "dealerAccountId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFermataPauseDealerRequest struct {
	value *FermataPauseDealerRequest
	isSet bool
}

func (v NullableFermataPauseDealerRequest) Get() *FermataPauseDealerRequest {
	return v.value
}

func (v *NullableFermataPauseDealerRequest) Set(val *FermataPauseDealerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFermataPauseDealerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFermataPauseDealerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFermataPauseDealerRequest(val *FermataPauseDealerRequest) *NullableFermataPauseDealerRequest {
	return &NullableFermataPauseDealerRequest{value: val, isSet: true}
}

func (v NullableFermataPauseDealerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFermataPauseDealerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


