/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifyTradingAccountCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyTradingAccountCredentialRequest{}

// VerifyTradingAccountCredentialRequest struct for VerifyTradingAccountCredentialRequest
type VerifyTradingAccountCredentialRequest struct {
	CredentialIds []string `json:"credentialIds"`
}

type _VerifyTradingAccountCredentialRequest VerifyTradingAccountCredentialRequest

// NewVerifyTradingAccountCredentialRequest instantiates a new VerifyTradingAccountCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyTradingAccountCredentialRequest(credentialIds []string) *VerifyTradingAccountCredentialRequest {
	this := VerifyTradingAccountCredentialRequest{}
	this.CredentialIds = credentialIds
	return &this
}

// NewVerifyTradingAccountCredentialRequestWithDefaults instantiates a new VerifyTradingAccountCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyTradingAccountCredentialRequestWithDefaults() *VerifyTradingAccountCredentialRequest {
	this := VerifyTradingAccountCredentialRequest{}
	return &this
}

// GetCredentialIds returns the CredentialIds field value
func (o *VerifyTradingAccountCredentialRequest) GetCredentialIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CredentialIds
}

// GetCredentialIdsOk returns a tuple with the CredentialIds field value
// and a boolean to check if the value has been set.
func (o *VerifyTradingAccountCredentialRequest) GetCredentialIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CredentialIds, true
}

// SetCredentialIds sets field value
func (o *VerifyTradingAccountCredentialRequest) SetCredentialIds(v []string) {
	o.CredentialIds = v
}

func (o VerifyTradingAccountCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyTradingAccountCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credentialIds"] = o.CredentialIds
	return toSerialize, nil
}

func (o *VerifyTradingAccountCredentialRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credentialIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyTradingAccountCredentialRequest := _VerifyTradingAccountCredentialRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyTradingAccountCredentialRequest)

	if err != nil {
		return err
	}

	*o = VerifyTradingAccountCredentialRequest(varVerifyTradingAccountCredentialRequest)

	return err
}

type NullableVerifyTradingAccountCredentialRequest struct {
	value *VerifyTradingAccountCredentialRequest
	isSet bool
}

func (v NullableVerifyTradingAccountCredentialRequest) Get() *VerifyTradingAccountCredentialRequest {
	return v.value
}

func (v *NullableVerifyTradingAccountCredentialRequest) Set(val *VerifyTradingAccountCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyTradingAccountCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyTradingAccountCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyTradingAccountCredentialRequest(val *VerifyTradingAccountCredentialRequest) *NullableVerifyTradingAccountCredentialRequest {
	return &NullableVerifyTradingAccountCredentialRequest{value: val, isSet: true}
}

func (v NullableVerifyTradingAccountCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyTradingAccountCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


