/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RpcCreateSubscriptionParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpcCreateSubscriptionParams{}

// RpcCreateSubscriptionParams Request to create a market data subscription
type RpcCreateSubscriptionParams struct {
	Venue Venue `json:"venue"`
	Instruments []string `json:"instruments,omitempty"`
	SubscriptionType SubscriptionType `json:"subscriptionType"`
}

type _RpcCreateSubscriptionParams RpcCreateSubscriptionParams

// NewRpcCreateSubscriptionParams instantiates a new RpcCreateSubscriptionParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpcCreateSubscriptionParams(venue Venue, subscriptionType SubscriptionType) *RpcCreateSubscriptionParams {
	this := RpcCreateSubscriptionParams{}
	this.Venue = venue
	this.SubscriptionType = subscriptionType
	return &this
}

// NewRpcCreateSubscriptionParamsWithDefaults instantiates a new RpcCreateSubscriptionParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpcCreateSubscriptionParamsWithDefaults() *RpcCreateSubscriptionParams {
	this := RpcCreateSubscriptionParams{}
	return &this
}

// GetVenue returns the Venue field value
func (o *RpcCreateSubscriptionParams) GetVenue() Venue {
	if o == nil {
		var ret Venue
		return ret
	}

	return o.Venue
}

// GetVenueOk returns a tuple with the Venue field value
// and a boolean to check if the value has been set.
func (o *RpcCreateSubscriptionParams) GetVenueOk() (*Venue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Venue, true
}

// SetVenue sets field value
func (o *RpcCreateSubscriptionParams) SetVenue(v Venue) {
	o.Venue = v
}

// GetInstruments returns the Instruments field value if set, zero value otherwise.
func (o *RpcCreateSubscriptionParams) GetInstruments() []string {
	if o == nil || IsNil(o.Instruments) {
		var ret []string
		return ret
	}
	return o.Instruments
}

// GetInstrumentsOk returns a tuple with the Instruments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcCreateSubscriptionParams) GetInstrumentsOk() ([]string, bool) {
	if o == nil || IsNil(o.Instruments) {
		return nil, false
	}
	return o.Instruments, true
}

// HasInstruments returns a boolean if a field has been set.
func (o *RpcCreateSubscriptionParams) HasInstruments() bool {
	if o != nil && !IsNil(o.Instruments) {
		return true
	}

	return false
}

// SetInstruments gets a reference to the given []string and assigns it to the Instruments field.
func (o *RpcCreateSubscriptionParams) SetInstruments(v []string) {
	o.Instruments = v
}

// GetSubscriptionType returns the SubscriptionType field value
func (o *RpcCreateSubscriptionParams) GetSubscriptionType() SubscriptionType {
	if o == nil {
		var ret SubscriptionType
		return ret
	}

	return o.SubscriptionType
}

// GetSubscriptionTypeOk returns a tuple with the SubscriptionType field value
// and a boolean to check if the value has been set.
func (o *RpcCreateSubscriptionParams) GetSubscriptionTypeOk() (*SubscriptionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionType, true
}

// SetSubscriptionType sets field value
func (o *RpcCreateSubscriptionParams) SetSubscriptionType(v SubscriptionType) {
	o.SubscriptionType = v
}

func (o RpcCreateSubscriptionParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpcCreateSubscriptionParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["venue"] = o.Venue
	if !IsNil(o.Instruments) {
		toSerialize["instruments"] = o.Instruments
	}
	toSerialize["subscriptionType"] = o.SubscriptionType
	return toSerialize, nil
}

func (o *RpcCreateSubscriptionParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"venue",
		"subscriptionType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRpcCreateSubscriptionParams := _RpcCreateSubscriptionParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRpcCreateSubscriptionParams)

	if err != nil {
		return err
	}

	*o = RpcCreateSubscriptionParams(varRpcCreateSubscriptionParams)

	return err
}

type NullableRpcCreateSubscriptionParams struct {
	value *RpcCreateSubscriptionParams
	isSet bool
}

func (v NullableRpcCreateSubscriptionParams) Get() *RpcCreateSubscriptionParams {
	return v.value
}

func (v *NullableRpcCreateSubscriptionParams) Set(val *RpcCreateSubscriptionParams) {
	v.value = val
	v.isSet = true
}

func (v NullableRpcCreateSubscriptionParams) IsSet() bool {
	return v.isSet
}

func (v *NullableRpcCreateSubscriptionParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpcCreateSubscriptionParams(val *RpcCreateSubscriptionParams) *NullableRpcCreateSubscriptionParams {
	return &NullableRpcCreateSubscriptionParams{value: val, isSet: true}
}

func (v NullableRpcCreateSubscriptionParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpcCreateSubscriptionParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


