/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TradingAccountCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TradingAccountCredential{}

// TradingAccountCredential struct for TradingAccountCredential
type TradingAccountCredential struct {
	// UUID string
	CredentialId string `json:"credentialId"`
	Venue Venue `json:"venue"`
	CredentialType CredentialType `json:"credentialType"`
	Nickname *string `json:"nickname,omitempty"`
	Status TradingAccountCredentialStatus `json:"status"`
	// Unix timestamp in milliseconds
	CreatedAt int64 `json:"createdAt"`
	// Creation timestamp in ISO 8601 format
	CreatedAtDateTime *time.Time `json:"createdAtDateTime,omitempty"`
	// Unix timestamp in milliseconds
	UpdatedAt int64 `json:"updatedAt"`
	// Last update timestamp in ISO 8601 format
	UpdatedAtDateTime *time.Time `json:"updatedAtDateTime,omitempty"`
	// Unix timestamp in milliseconds
	RevokedAt *int64 `json:"revokedAt,omitempty"`
	// Revocation timestamp in ISO 8601 format
	RevokedAtDateTime *time.Time `json:"revokedAtDateTime,omitempty"`
}

type _TradingAccountCredential TradingAccountCredential

// NewTradingAccountCredential instantiates a new TradingAccountCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTradingAccountCredential(credentialId string, venue Venue, credentialType CredentialType, status TradingAccountCredentialStatus, createdAt int64, updatedAt int64) *TradingAccountCredential {
	this := TradingAccountCredential{}
	this.CredentialId = credentialId
	this.Venue = venue
	this.CredentialType = credentialType
	this.Status = status
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewTradingAccountCredentialWithDefaults instantiates a new TradingAccountCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTradingAccountCredentialWithDefaults() *TradingAccountCredential {
	this := TradingAccountCredential{}
	return &this
}

// GetCredentialId returns the CredentialId field value
func (o *TradingAccountCredential) GetCredentialId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CredentialId
}

// GetCredentialIdOk returns a tuple with the CredentialId field value
// and a boolean to check if the value has been set.
func (o *TradingAccountCredential) GetCredentialIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialId, true
}

// SetCredentialId sets field value
func (o *TradingAccountCredential) SetCredentialId(v string) {
	o.CredentialId = v
}

// GetVenue returns the Venue field value
func (o *TradingAccountCredential) GetVenue() Venue {
	if o == nil {
		var ret Venue
		return ret
	}

	return o.Venue
}

// GetVenueOk returns a tuple with the Venue field value
// and a boolean to check if the value has been set.
func (o *TradingAccountCredential) GetVenueOk() (*Venue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Venue, true
}

// SetVenue sets field value
func (o *TradingAccountCredential) SetVenue(v Venue) {
	o.Venue = v
}

// GetCredentialType returns the CredentialType field value
func (o *TradingAccountCredential) GetCredentialType() CredentialType {
	if o == nil {
		var ret CredentialType
		return ret
	}

	return o.CredentialType
}

// GetCredentialTypeOk returns a tuple with the CredentialType field value
// and a boolean to check if the value has been set.
func (o *TradingAccountCredential) GetCredentialTypeOk() (*CredentialType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialType, true
}

// SetCredentialType sets field value
func (o *TradingAccountCredential) SetCredentialType(v CredentialType) {
	o.CredentialType = v
}

// GetNickname returns the Nickname field value if set, zero value otherwise.
func (o *TradingAccountCredential) GetNickname() string {
	if o == nil || IsNil(o.Nickname) {
		var ret string
		return ret
	}
	return *o.Nickname
}

// GetNicknameOk returns a tuple with the Nickname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TradingAccountCredential) GetNicknameOk() (*string, bool) {
	if o == nil || IsNil(o.Nickname) {
		return nil, false
	}
	return o.Nickname, true
}

// HasNickname returns a boolean if a field has been set.
func (o *TradingAccountCredential) HasNickname() bool {
	if o != nil && !IsNil(o.Nickname) {
		return true
	}

	return false
}

// SetNickname gets a reference to the given string and assigns it to the Nickname field.
func (o *TradingAccountCredential) SetNickname(v string) {
	o.Nickname = &v
}

// GetStatus returns the Status field value
func (o *TradingAccountCredential) GetStatus() TradingAccountCredentialStatus {
	if o == nil {
		var ret TradingAccountCredentialStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TradingAccountCredential) GetStatusOk() (*TradingAccountCredentialStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TradingAccountCredential) SetStatus(v TradingAccountCredentialStatus) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TradingAccountCredential) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TradingAccountCredential) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TradingAccountCredential) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetCreatedAtDateTime returns the CreatedAtDateTime field value if set, zero value otherwise.
func (o *TradingAccountCredential) GetCreatedAtDateTime() time.Time {
	if o == nil || IsNil(o.CreatedAtDateTime) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAtDateTime
}

// GetCreatedAtDateTimeOk returns a tuple with the CreatedAtDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TradingAccountCredential) GetCreatedAtDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAtDateTime) {
		return nil, false
	}
	return o.CreatedAtDateTime, true
}

// HasCreatedAtDateTime returns a boolean if a field has been set.
func (o *TradingAccountCredential) HasCreatedAtDateTime() bool {
	if o != nil && !IsNil(o.CreatedAtDateTime) {
		return true
	}

	return false
}

// SetCreatedAtDateTime gets a reference to the given time.Time and assigns it to the CreatedAtDateTime field.
func (o *TradingAccountCredential) SetCreatedAtDateTime(v time.Time) {
	o.CreatedAtDateTime = &v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *TradingAccountCredential) GetUpdatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *TradingAccountCredential) GetUpdatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *TradingAccountCredential) SetUpdatedAt(v int64) {
	o.UpdatedAt = v
}

// GetUpdatedAtDateTime returns the UpdatedAtDateTime field value if set, zero value otherwise.
func (o *TradingAccountCredential) GetUpdatedAtDateTime() time.Time {
	if o == nil || IsNil(o.UpdatedAtDateTime) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAtDateTime
}

// GetUpdatedAtDateTimeOk returns a tuple with the UpdatedAtDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TradingAccountCredential) GetUpdatedAtDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAtDateTime) {
		return nil, false
	}
	return o.UpdatedAtDateTime, true
}

// HasUpdatedAtDateTime returns a boolean if a field has been set.
func (o *TradingAccountCredential) HasUpdatedAtDateTime() bool {
	if o != nil && !IsNil(o.UpdatedAtDateTime) {
		return true
	}

	return false
}

// SetUpdatedAtDateTime gets a reference to the given time.Time and assigns it to the UpdatedAtDateTime field.
func (o *TradingAccountCredential) SetUpdatedAtDateTime(v time.Time) {
	o.UpdatedAtDateTime = &v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise.
func (o *TradingAccountCredential) GetRevokedAt() int64 {
	if o == nil || IsNil(o.RevokedAt) {
		var ret int64
		return ret
	}
	return *o.RevokedAt
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TradingAccountCredential) GetRevokedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.RevokedAt) {
		return nil, false
	}
	return o.RevokedAt, true
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *TradingAccountCredential) HasRevokedAt() bool {
	if o != nil && !IsNil(o.RevokedAt) {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given int64 and assigns it to the RevokedAt field.
func (o *TradingAccountCredential) SetRevokedAt(v int64) {
	o.RevokedAt = &v
}

// GetRevokedAtDateTime returns the RevokedAtDateTime field value if set, zero value otherwise.
func (o *TradingAccountCredential) GetRevokedAtDateTime() time.Time {
	if o == nil || IsNil(o.RevokedAtDateTime) {
		var ret time.Time
		return ret
	}
	return *o.RevokedAtDateTime
}

// GetRevokedAtDateTimeOk returns a tuple with the RevokedAtDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TradingAccountCredential) GetRevokedAtDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RevokedAtDateTime) {
		return nil, false
	}
	return o.RevokedAtDateTime, true
}

// HasRevokedAtDateTime returns a boolean if a field has been set.
func (o *TradingAccountCredential) HasRevokedAtDateTime() bool {
	if o != nil && !IsNil(o.RevokedAtDateTime) {
		return true
	}

	return false
}

// SetRevokedAtDateTime gets a reference to the given time.Time and assigns it to the RevokedAtDateTime field.
func (o *TradingAccountCredential) SetRevokedAtDateTime(v time.Time) {
	o.RevokedAtDateTime = &v
}

func (o TradingAccountCredential) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TradingAccountCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credentialId"] = o.CredentialId
	toSerialize["venue"] = o.Venue
	toSerialize["credentialType"] = o.CredentialType
	if !IsNil(o.Nickname) {
		toSerialize["nickname"] = o.Nickname
	}
	toSerialize["status"] = o.Status
	toSerialize["createdAt"] = o.CreatedAt
	if !IsNil(o.CreatedAtDateTime) {
		toSerialize["createdAtDateTime"] = o.CreatedAtDateTime
	}
	toSerialize["updatedAt"] = o.UpdatedAt
	if !IsNil(o.UpdatedAtDateTime) {
		toSerialize["updatedAtDateTime"] = o.UpdatedAtDateTime
	}
	if !IsNil(o.RevokedAt) {
		toSerialize["revokedAt"] = o.RevokedAt
	}
	if !IsNil(o.RevokedAtDateTime) {
		toSerialize["revokedAtDateTime"] = o.RevokedAtDateTime
	}
	return toSerialize, nil
}

func (o *TradingAccountCredential) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credentialId",
		"venue",
		"credentialType",
		"status",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTradingAccountCredential := _TradingAccountCredential{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTradingAccountCredential)

	if err != nil {
		return err
	}

	*o = TradingAccountCredential(varTradingAccountCredential)

	return err
}

type NullableTradingAccountCredential struct {
	value *TradingAccountCredential
	isSet bool
}

func (v NullableTradingAccountCredential) Get() *TradingAccountCredential {
	return v.value
}

func (v *NullableTradingAccountCredential) Set(val *TradingAccountCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableTradingAccountCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableTradingAccountCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTradingAccountCredential(val *TradingAccountCredential) *NullableTradingAccountCredential {
	return &NullableTradingAccountCredential{value: val, isSet: true}
}

func (v NullableTradingAccountCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTradingAccountCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


