/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the Root200ResponseAllOfData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Root200ResponseAllOfData{}

// Root200ResponseAllOfData struct for Root200ResponseAllOfData
type Root200ResponseAllOfData struct {
	Name *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
	Description *string `json:"description,omitempty"`
	Documentation *string `json:"documentation,omitempty"`
}

// NewRoot200ResponseAllOfData instantiates a new Root200ResponseAllOfData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoot200ResponseAllOfData() *Root200ResponseAllOfData {
	this := Root200ResponseAllOfData{}
	return &this
}

// NewRoot200ResponseAllOfDataWithDefaults instantiates a new Root200ResponseAllOfData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoot200ResponseAllOfDataWithDefaults() *Root200ResponseAllOfData {
	this := Root200ResponseAllOfData{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Root200ResponseAllOfData) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Root200ResponseAllOfData) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Root200ResponseAllOfData) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Root200ResponseAllOfData) SetName(v string) {
	o.Name = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *Root200ResponseAllOfData) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Root200ResponseAllOfData) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *Root200ResponseAllOfData) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *Root200ResponseAllOfData) SetVersion(v string) {
	o.Version = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Root200ResponseAllOfData) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Root200ResponseAllOfData) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Root200ResponseAllOfData) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Root200ResponseAllOfData) SetDescription(v string) {
	o.Description = &v
}

// GetDocumentation returns the Documentation field value if set, zero value otherwise.
func (o *Root200ResponseAllOfData) GetDocumentation() string {
	if o == nil || IsNil(o.Documentation) {
		var ret string
		return ret
	}
	return *o.Documentation
}

// GetDocumentationOk returns a tuple with the Documentation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Root200ResponseAllOfData) GetDocumentationOk() (*string, bool) {
	if o == nil || IsNil(o.Documentation) {
		return nil, false
	}
	return o.Documentation, true
}

// HasDocumentation returns a boolean if a field has been set.
func (o *Root200ResponseAllOfData) HasDocumentation() bool {
	if o != nil && !IsNil(o.Documentation) {
		return true
	}

	return false
}

// SetDocumentation gets a reference to the given string and assigns it to the Documentation field.
func (o *Root200ResponseAllOfData) SetDocumentation(v string) {
	o.Documentation = &v
}

func (o Root200ResponseAllOfData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Root200ResponseAllOfData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Documentation) {
		toSerialize["documentation"] = o.Documentation
	}
	return toSerialize, nil
}

type NullableRoot200ResponseAllOfData struct {
	value *Root200ResponseAllOfData
	isSet bool
}

func (v NullableRoot200ResponseAllOfData) Get() *Root200ResponseAllOfData {
	return v.value
}

func (v *NullableRoot200ResponseAllOfData) Set(val *Root200ResponseAllOfData) {
	v.value = val
	v.isSet = true
}

func (v NullableRoot200ResponseAllOfData) IsSet() bool {
	return v.isSet
}

func (v *NullableRoot200ResponseAllOfData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoot200ResponseAllOfData(val *Root200ResponseAllOfData) *NullableRoot200ResponseAllOfData {
	return &NullableRoot200ResponseAllOfData{value: val, isSet: true}
}

func (v NullableRoot200ResponseAllOfData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoot200ResponseAllOfData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


