/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
)

// checks if the RpcTradeOrder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpcTradeOrder{}

// RpcTradeOrder Trade order model
type RpcTradeOrder struct {
	// Unique trade order ID
	TradeOrderId *string `json:"tradeOrderId,omitempty"`
	// Client-assigned order ID
	ClientOrderId *string `json:"clientOrderId,omitempty"`
	// Original client order ID (for cancel/replace)
	OriginalClientOrderId *string `json:"originalClientOrderId,omitempty"`
	// Order ID from external venue
	ExternalOrderId *string `json:"externalOrderId,omitempty"`
	// Idempotency key
	IdempotencyKey *string `json:"idempotencyKey,omitempty"`
	// Trading venue
	Venue *string `json:"venue,omitempty"`
	// Trading account ID
	TradingAccountId *string `json:"tradingAccountId,omitempty"`
	// External account ID at venue
	ExternalTradingAccountId *string `json:"externalTradingAccountId,omitempty"`
	// Instrument ID (VENUE:BASE/QUOTE)
	InstrumentId *string `json:"instrumentId,omitempty"`
	// Symbol at external venue
	ExternalSymbol *string `json:"externalSymbol,omitempty"`
	// Base asset
	BaseAsset *string `json:"baseAsset,omitempty"`
	// Quote asset
	QuoteAsset *string `json:"quoteAsset,omitempty"`
	OrderType *OrderType `json:"orderType,omitempty"`
	OrderSide *OrderSide `json:"orderSide,omitempty"`
	QuantityType *QuantityType `json:"quantityType,omitempty"`
	// Order quantity (decimal string)
	Quantity *string `json:"quantity,omitempty"`
	// Quantity in quote currency
	QuoteCurrencyQuantity *string `json:"quoteCurrencyQuantity,omitempty"`
	// Quantity as position percentage
	PositionPercentage *string `json:"positionPercentage,omitempty"`
	QuantityRounding *QuantityRounding `json:"quantityRounding,omitempty"`
	// Limit price (decimal string)
	LimitPrice *string `json:"limitPrice,omitempty"`
	// Stop price (decimal string)
	StopPrice *string `json:"stopPrice,omitempty"`
	TimeInForce *TimeInForce `json:"timeInForce,omitempty"`
	Status *OrderStatus `json:"status,omitempty"`
	// Average executed price
	ExecutedPrice *string `json:"executedPrice,omitempty"`
	// Percentage of order filled
	ExecutedPercentage *string `json:"executedPercentage,omitempty"`
	// Quantity executed
	ExecutedQuantity *string `json:"executedQuantity,omitempty"`
	// Total cost in quote currency
	ExecutedCost *string `json:"executedCost,omitempty"`
	// Fees charged
	Fees []RpcSecurityQuantity `json:"fees,omitempty"`
	// Reason for cancellation
	CancelReason *string `json:"cancelReason,omitempty"`
	// Reason for rejection
	RejectReason *string `json:"rejectReason,omitempty"`
	// Order creation time
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Last update time
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Order expiration time (for GTD)
	ExpireAt *time.Time `json:"expireAt,omitempty"`
	// Time of last execution
	LastExecutionAt *time.Time `json:"lastExecutionAt,omitempty"`
	// Time of cancellation
	CanceledAt *time.Time `json:"canceledAt,omitempty"`
}

// NewRpcTradeOrder instantiates a new RpcTradeOrder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpcTradeOrder() *RpcTradeOrder {
	this := RpcTradeOrder{}
	var quantityRounding QuantityRounding = QUANTITYROUNDING_EMPTY
	this.QuantityRounding = &quantityRounding
	return &this
}

// NewRpcTradeOrderWithDefaults instantiates a new RpcTradeOrder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpcTradeOrderWithDefaults() *RpcTradeOrder {
	this := RpcTradeOrder{}
	var quantityRounding QuantityRounding = QUANTITYROUNDING_EMPTY
	this.QuantityRounding = &quantityRounding
	return &this
}

// GetTradeOrderId returns the TradeOrderId field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetTradeOrderId() string {
	if o == nil || IsNil(o.TradeOrderId) {
		var ret string
		return ret
	}
	return *o.TradeOrderId
}

// GetTradeOrderIdOk returns a tuple with the TradeOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetTradeOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.TradeOrderId) {
		return nil, false
	}
	return o.TradeOrderId, true
}

// HasTradeOrderId returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasTradeOrderId() bool {
	if o != nil && !IsNil(o.TradeOrderId) {
		return true
	}

	return false
}

// SetTradeOrderId gets a reference to the given string and assigns it to the TradeOrderId field.
func (o *RpcTradeOrder) SetTradeOrderId(v string) {
	o.TradeOrderId = &v
}

// GetClientOrderId returns the ClientOrderId field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetClientOrderId() string {
	if o == nil || IsNil(o.ClientOrderId) {
		var ret string
		return ret
	}
	return *o.ClientOrderId
}

// GetClientOrderIdOk returns a tuple with the ClientOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetClientOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientOrderId) {
		return nil, false
	}
	return o.ClientOrderId, true
}

// HasClientOrderId returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasClientOrderId() bool {
	if o != nil && !IsNil(o.ClientOrderId) {
		return true
	}

	return false
}

// SetClientOrderId gets a reference to the given string and assigns it to the ClientOrderId field.
func (o *RpcTradeOrder) SetClientOrderId(v string) {
	o.ClientOrderId = &v
}

// GetOriginalClientOrderId returns the OriginalClientOrderId field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetOriginalClientOrderId() string {
	if o == nil || IsNil(o.OriginalClientOrderId) {
		var ret string
		return ret
	}
	return *o.OriginalClientOrderId
}

// GetOriginalClientOrderIdOk returns a tuple with the OriginalClientOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetOriginalClientOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OriginalClientOrderId) {
		return nil, false
	}
	return o.OriginalClientOrderId, true
}

// HasOriginalClientOrderId returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasOriginalClientOrderId() bool {
	if o != nil && !IsNil(o.OriginalClientOrderId) {
		return true
	}

	return false
}

// SetOriginalClientOrderId gets a reference to the given string and assigns it to the OriginalClientOrderId field.
func (o *RpcTradeOrder) SetOriginalClientOrderId(v string) {
	o.OriginalClientOrderId = &v
}

// GetExternalOrderId returns the ExternalOrderId field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetExternalOrderId() string {
	if o == nil || IsNil(o.ExternalOrderId) {
		var ret string
		return ret
	}
	return *o.ExternalOrderId
}

// GetExternalOrderIdOk returns a tuple with the ExternalOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetExternalOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalOrderId) {
		return nil, false
	}
	return o.ExternalOrderId, true
}

// HasExternalOrderId returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasExternalOrderId() bool {
	if o != nil && !IsNil(o.ExternalOrderId) {
		return true
	}

	return false
}

// SetExternalOrderId gets a reference to the given string and assigns it to the ExternalOrderId field.
func (o *RpcTradeOrder) SetExternalOrderId(v string) {
	o.ExternalOrderId = &v
}

// GetIdempotencyKey returns the IdempotencyKey field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetIdempotencyKey() string {
	if o == nil || IsNil(o.IdempotencyKey) {
		var ret string
		return ret
	}
	return *o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IdempotencyKey) {
		return nil, false
	}
	return o.IdempotencyKey, true
}

// HasIdempotencyKey returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasIdempotencyKey() bool {
	if o != nil && !IsNil(o.IdempotencyKey) {
		return true
	}

	return false
}

// SetIdempotencyKey gets a reference to the given string and assigns it to the IdempotencyKey field.
func (o *RpcTradeOrder) SetIdempotencyKey(v string) {
	o.IdempotencyKey = &v
}

// GetVenue returns the Venue field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetVenue() string {
	if o == nil || IsNil(o.Venue) {
		var ret string
		return ret
	}
	return *o.Venue
}

// GetVenueOk returns a tuple with the Venue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetVenueOk() (*string, bool) {
	if o == nil || IsNil(o.Venue) {
		return nil, false
	}
	return o.Venue, true
}

// HasVenue returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasVenue() bool {
	if o != nil && !IsNil(o.Venue) {
		return true
	}

	return false
}

// SetVenue gets a reference to the given string and assigns it to the Venue field.
func (o *RpcTradeOrder) SetVenue(v string) {
	o.Venue = &v
}

// GetTradingAccountId returns the TradingAccountId field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetTradingAccountId() string {
	if o == nil || IsNil(o.TradingAccountId) {
		var ret string
		return ret
	}
	return *o.TradingAccountId
}

// GetTradingAccountIdOk returns a tuple with the TradingAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetTradingAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.TradingAccountId) {
		return nil, false
	}
	return o.TradingAccountId, true
}

// HasTradingAccountId returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasTradingAccountId() bool {
	if o != nil && !IsNil(o.TradingAccountId) {
		return true
	}

	return false
}

// SetTradingAccountId gets a reference to the given string and assigns it to the TradingAccountId field.
func (o *RpcTradeOrder) SetTradingAccountId(v string) {
	o.TradingAccountId = &v
}

// GetExternalTradingAccountId returns the ExternalTradingAccountId field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetExternalTradingAccountId() string {
	if o == nil || IsNil(o.ExternalTradingAccountId) {
		var ret string
		return ret
	}
	return *o.ExternalTradingAccountId
}

// GetExternalTradingAccountIdOk returns a tuple with the ExternalTradingAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetExternalTradingAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalTradingAccountId) {
		return nil, false
	}
	return o.ExternalTradingAccountId, true
}

// HasExternalTradingAccountId returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasExternalTradingAccountId() bool {
	if o != nil && !IsNil(o.ExternalTradingAccountId) {
		return true
	}

	return false
}

// SetExternalTradingAccountId gets a reference to the given string and assigns it to the ExternalTradingAccountId field.
func (o *RpcTradeOrder) SetExternalTradingAccountId(v string) {
	o.ExternalTradingAccountId = &v
}

// GetInstrumentId returns the InstrumentId field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetInstrumentId() string {
	if o == nil || IsNil(o.InstrumentId) {
		var ret string
		return ret
	}
	return *o.InstrumentId
}

// GetInstrumentIdOk returns a tuple with the InstrumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetInstrumentIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstrumentId) {
		return nil, false
	}
	return o.InstrumentId, true
}

// HasInstrumentId returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasInstrumentId() bool {
	if o != nil && !IsNil(o.InstrumentId) {
		return true
	}

	return false
}

// SetInstrumentId gets a reference to the given string and assigns it to the InstrumentId field.
func (o *RpcTradeOrder) SetInstrumentId(v string) {
	o.InstrumentId = &v
}

// GetExternalSymbol returns the ExternalSymbol field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetExternalSymbol() string {
	if o == nil || IsNil(o.ExternalSymbol) {
		var ret string
		return ret
	}
	return *o.ExternalSymbol
}

// GetExternalSymbolOk returns a tuple with the ExternalSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetExternalSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSymbol) {
		return nil, false
	}
	return o.ExternalSymbol, true
}

// HasExternalSymbol returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasExternalSymbol() bool {
	if o != nil && !IsNil(o.ExternalSymbol) {
		return true
	}

	return false
}

// SetExternalSymbol gets a reference to the given string and assigns it to the ExternalSymbol field.
func (o *RpcTradeOrder) SetExternalSymbol(v string) {
	o.ExternalSymbol = &v
}

// GetBaseAsset returns the BaseAsset field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetBaseAsset() string {
	if o == nil || IsNil(o.BaseAsset) {
		var ret string
		return ret
	}
	return *o.BaseAsset
}

// GetBaseAssetOk returns a tuple with the BaseAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetBaseAssetOk() (*string, bool) {
	if o == nil || IsNil(o.BaseAsset) {
		return nil, false
	}
	return o.BaseAsset, true
}

// HasBaseAsset returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasBaseAsset() bool {
	if o != nil && !IsNil(o.BaseAsset) {
		return true
	}

	return false
}

// SetBaseAsset gets a reference to the given string and assigns it to the BaseAsset field.
func (o *RpcTradeOrder) SetBaseAsset(v string) {
	o.BaseAsset = &v
}

// GetQuoteAsset returns the QuoteAsset field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetQuoteAsset() string {
	if o == nil || IsNil(o.QuoteAsset) {
		var ret string
		return ret
	}
	return *o.QuoteAsset
}

// GetQuoteAssetOk returns a tuple with the QuoteAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetQuoteAssetOk() (*string, bool) {
	if o == nil || IsNil(o.QuoteAsset) {
		return nil, false
	}
	return o.QuoteAsset, true
}

// HasQuoteAsset returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasQuoteAsset() bool {
	if o != nil && !IsNil(o.QuoteAsset) {
		return true
	}

	return false
}

// SetQuoteAsset gets a reference to the given string and assigns it to the QuoteAsset field.
func (o *RpcTradeOrder) SetQuoteAsset(v string) {
	o.QuoteAsset = &v
}

// GetOrderType returns the OrderType field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetOrderType() OrderType {
	if o == nil || IsNil(o.OrderType) {
		var ret OrderType
		return ret
	}
	return *o.OrderType
}

// GetOrderTypeOk returns a tuple with the OrderType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetOrderTypeOk() (*OrderType, bool) {
	if o == nil || IsNil(o.OrderType) {
		return nil, false
	}
	return o.OrderType, true
}

// HasOrderType returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasOrderType() bool {
	if o != nil && !IsNil(o.OrderType) {
		return true
	}

	return false
}

// SetOrderType gets a reference to the given OrderType and assigns it to the OrderType field.
func (o *RpcTradeOrder) SetOrderType(v OrderType) {
	o.OrderType = &v
}

// GetOrderSide returns the OrderSide field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetOrderSide() OrderSide {
	if o == nil || IsNil(o.OrderSide) {
		var ret OrderSide
		return ret
	}
	return *o.OrderSide
}

// GetOrderSideOk returns a tuple with the OrderSide field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetOrderSideOk() (*OrderSide, bool) {
	if o == nil || IsNil(o.OrderSide) {
		return nil, false
	}
	return o.OrderSide, true
}

// HasOrderSide returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasOrderSide() bool {
	if o != nil && !IsNil(o.OrderSide) {
		return true
	}

	return false
}

// SetOrderSide gets a reference to the given OrderSide and assigns it to the OrderSide field.
func (o *RpcTradeOrder) SetOrderSide(v OrderSide) {
	o.OrderSide = &v
}

// GetQuantityType returns the QuantityType field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetQuantityType() QuantityType {
	if o == nil || IsNil(o.QuantityType) {
		var ret QuantityType
		return ret
	}
	return *o.QuantityType
}

// GetQuantityTypeOk returns a tuple with the QuantityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetQuantityTypeOk() (*QuantityType, bool) {
	if o == nil || IsNil(o.QuantityType) {
		return nil, false
	}
	return o.QuantityType, true
}

// HasQuantityType returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasQuantityType() bool {
	if o != nil && !IsNil(o.QuantityType) {
		return true
	}

	return false
}

// SetQuantityType gets a reference to the given QuantityType and assigns it to the QuantityType field.
func (o *RpcTradeOrder) SetQuantityType(v QuantityType) {
	o.QuantityType = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetQuantity() string {
	if o == nil || IsNil(o.Quantity) {
		var ret string
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given string and assigns it to the Quantity field.
func (o *RpcTradeOrder) SetQuantity(v string) {
	o.Quantity = &v
}

// GetQuoteCurrencyQuantity returns the QuoteCurrencyQuantity field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetQuoteCurrencyQuantity() string {
	if o == nil || IsNil(o.QuoteCurrencyQuantity) {
		var ret string
		return ret
	}
	return *o.QuoteCurrencyQuantity
}

// GetQuoteCurrencyQuantityOk returns a tuple with the QuoteCurrencyQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetQuoteCurrencyQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.QuoteCurrencyQuantity) {
		return nil, false
	}
	return o.QuoteCurrencyQuantity, true
}

// HasQuoteCurrencyQuantity returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasQuoteCurrencyQuantity() bool {
	if o != nil && !IsNil(o.QuoteCurrencyQuantity) {
		return true
	}

	return false
}

// SetQuoteCurrencyQuantity gets a reference to the given string and assigns it to the QuoteCurrencyQuantity field.
func (o *RpcTradeOrder) SetQuoteCurrencyQuantity(v string) {
	o.QuoteCurrencyQuantity = &v
}

// GetPositionPercentage returns the PositionPercentage field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetPositionPercentage() string {
	if o == nil || IsNil(o.PositionPercentage) {
		var ret string
		return ret
	}
	return *o.PositionPercentage
}

// GetPositionPercentageOk returns a tuple with the PositionPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetPositionPercentageOk() (*string, bool) {
	if o == nil || IsNil(o.PositionPercentage) {
		return nil, false
	}
	return o.PositionPercentage, true
}

// HasPositionPercentage returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasPositionPercentage() bool {
	if o != nil && !IsNil(o.PositionPercentage) {
		return true
	}

	return false
}

// SetPositionPercentage gets a reference to the given string and assigns it to the PositionPercentage field.
func (o *RpcTradeOrder) SetPositionPercentage(v string) {
	o.PositionPercentage = &v
}

// GetQuantityRounding returns the QuantityRounding field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetQuantityRounding() QuantityRounding {
	if o == nil || IsNil(o.QuantityRounding) {
		var ret QuantityRounding
		return ret
	}
	return *o.QuantityRounding
}

// GetQuantityRoundingOk returns a tuple with the QuantityRounding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetQuantityRoundingOk() (*QuantityRounding, bool) {
	if o == nil || IsNil(o.QuantityRounding) {
		return nil, false
	}
	return o.QuantityRounding, true
}

// HasQuantityRounding returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasQuantityRounding() bool {
	if o != nil && !IsNil(o.QuantityRounding) {
		return true
	}

	return false
}

// SetQuantityRounding gets a reference to the given QuantityRounding and assigns it to the QuantityRounding field.
func (o *RpcTradeOrder) SetQuantityRounding(v QuantityRounding) {
	o.QuantityRounding = &v
}

// GetLimitPrice returns the LimitPrice field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetLimitPrice() string {
	if o == nil || IsNil(o.LimitPrice) {
		var ret string
		return ret
	}
	return *o.LimitPrice
}

// GetLimitPriceOk returns a tuple with the LimitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetLimitPriceOk() (*string, bool) {
	if o == nil || IsNil(o.LimitPrice) {
		return nil, false
	}
	return o.LimitPrice, true
}

// HasLimitPrice returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasLimitPrice() bool {
	if o != nil && !IsNil(o.LimitPrice) {
		return true
	}

	return false
}

// SetLimitPrice gets a reference to the given string and assigns it to the LimitPrice field.
func (o *RpcTradeOrder) SetLimitPrice(v string) {
	o.LimitPrice = &v
}

// GetStopPrice returns the StopPrice field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetStopPrice() string {
	if o == nil || IsNil(o.StopPrice) {
		var ret string
		return ret
	}
	return *o.StopPrice
}

// GetStopPriceOk returns a tuple with the StopPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetStopPriceOk() (*string, bool) {
	if o == nil || IsNil(o.StopPrice) {
		return nil, false
	}
	return o.StopPrice, true
}

// HasStopPrice returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasStopPrice() bool {
	if o != nil && !IsNil(o.StopPrice) {
		return true
	}

	return false
}

// SetStopPrice gets a reference to the given string and assigns it to the StopPrice field.
func (o *RpcTradeOrder) SetStopPrice(v string) {
	o.StopPrice = &v
}

// GetTimeInForce returns the TimeInForce field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetTimeInForce() TimeInForce {
	if o == nil || IsNil(o.TimeInForce) {
		var ret TimeInForce
		return ret
	}
	return *o.TimeInForce
}

// GetTimeInForceOk returns a tuple with the TimeInForce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetTimeInForceOk() (*TimeInForce, bool) {
	if o == nil || IsNil(o.TimeInForce) {
		return nil, false
	}
	return o.TimeInForce, true
}

// HasTimeInForce returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasTimeInForce() bool {
	if o != nil && !IsNil(o.TimeInForce) {
		return true
	}

	return false
}

// SetTimeInForce gets a reference to the given TimeInForce and assigns it to the TimeInForce field.
func (o *RpcTradeOrder) SetTimeInForce(v TimeInForce) {
	o.TimeInForce = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetStatus() OrderStatus {
	if o == nil || IsNil(o.Status) {
		var ret OrderStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetStatusOk() (*OrderStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given OrderStatus and assigns it to the Status field.
func (o *RpcTradeOrder) SetStatus(v OrderStatus) {
	o.Status = &v
}

// GetExecutedPrice returns the ExecutedPrice field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetExecutedPrice() string {
	if o == nil || IsNil(o.ExecutedPrice) {
		var ret string
		return ret
	}
	return *o.ExecutedPrice
}

// GetExecutedPriceOk returns a tuple with the ExecutedPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetExecutedPriceOk() (*string, bool) {
	if o == nil || IsNil(o.ExecutedPrice) {
		return nil, false
	}
	return o.ExecutedPrice, true
}

// HasExecutedPrice returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasExecutedPrice() bool {
	if o != nil && !IsNil(o.ExecutedPrice) {
		return true
	}

	return false
}

// SetExecutedPrice gets a reference to the given string and assigns it to the ExecutedPrice field.
func (o *RpcTradeOrder) SetExecutedPrice(v string) {
	o.ExecutedPrice = &v
}

// GetExecutedPercentage returns the ExecutedPercentage field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetExecutedPercentage() string {
	if o == nil || IsNil(o.ExecutedPercentage) {
		var ret string
		return ret
	}
	return *o.ExecutedPercentage
}

// GetExecutedPercentageOk returns a tuple with the ExecutedPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetExecutedPercentageOk() (*string, bool) {
	if o == nil || IsNil(o.ExecutedPercentage) {
		return nil, false
	}
	return o.ExecutedPercentage, true
}

// HasExecutedPercentage returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasExecutedPercentage() bool {
	if o != nil && !IsNil(o.ExecutedPercentage) {
		return true
	}

	return false
}

// SetExecutedPercentage gets a reference to the given string and assigns it to the ExecutedPercentage field.
func (o *RpcTradeOrder) SetExecutedPercentage(v string) {
	o.ExecutedPercentage = &v
}

// GetExecutedQuantity returns the ExecutedQuantity field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetExecutedQuantity() string {
	if o == nil || IsNil(o.ExecutedQuantity) {
		var ret string
		return ret
	}
	return *o.ExecutedQuantity
}

// GetExecutedQuantityOk returns a tuple with the ExecutedQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetExecutedQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.ExecutedQuantity) {
		return nil, false
	}
	return o.ExecutedQuantity, true
}

// HasExecutedQuantity returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasExecutedQuantity() bool {
	if o != nil && !IsNil(o.ExecutedQuantity) {
		return true
	}

	return false
}

// SetExecutedQuantity gets a reference to the given string and assigns it to the ExecutedQuantity field.
func (o *RpcTradeOrder) SetExecutedQuantity(v string) {
	o.ExecutedQuantity = &v
}

// GetExecutedCost returns the ExecutedCost field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetExecutedCost() string {
	if o == nil || IsNil(o.ExecutedCost) {
		var ret string
		return ret
	}
	return *o.ExecutedCost
}

// GetExecutedCostOk returns a tuple with the ExecutedCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetExecutedCostOk() (*string, bool) {
	if o == nil || IsNil(o.ExecutedCost) {
		return nil, false
	}
	return o.ExecutedCost, true
}

// HasExecutedCost returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasExecutedCost() bool {
	if o != nil && !IsNil(o.ExecutedCost) {
		return true
	}

	return false
}

// SetExecutedCost gets a reference to the given string and assigns it to the ExecutedCost field.
func (o *RpcTradeOrder) SetExecutedCost(v string) {
	o.ExecutedCost = &v
}

// GetFees returns the Fees field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetFees() []RpcSecurityQuantity {
	if o == nil || IsNil(o.Fees) {
		var ret []RpcSecurityQuantity
		return ret
	}
	return o.Fees
}

// GetFeesOk returns a tuple with the Fees field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetFeesOk() ([]RpcSecurityQuantity, bool) {
	if o == nil || IsNil(o.Fees) {
		return nil, false
	}
	return o.Fees, true
}

// HasFees returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasFees() bool {
	if o != nil && !IsNil(o.Fees) {
		return true
	}

	return false
}

// SetFees gets a reference to the given []RpcSecurityQuantity and assigns it to the Fees field.
func (o *RpcTradeOrder) SetFees(v []RpcSecurityQuantity) {
	o.Fees = v
}

// GetCancelReason returns the CancelReason field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetCancelReason() string {
	if o == nil || IsNil(o.CancelReason) {
		var ret string
		return ret
	}
	return *o.CancelReason
}

// GetCancelReasonOk returns a tuple with the CancelReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetCancelReasonOk() (*string, bool) {
	if o == nil || IsNil(o.CancelReason) {
		return nil, false
	}
	return o.CancelReason, true
}

// HasCancelReason returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasCancelReason() bool {
	if o != nil && !IsNil(o.CancelReason) {
		return true
	}

	return false
}

// SetCancelReason gets a reference to the given string and assigns it to the CancelReason field.
func (o *RpcTradeOrder) SetCancelReason(v string) {
	o.CancelReason = &v
}

// GetRejectReason returns the RejectReason field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetRejectReason() string {
	if o == nil || IsNil(o.RejectReason) {
		var ret string
		return ret
	}
	return *o.RejectReason
}

// GetRejectReasonOk returns a tuple with the RejectReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetRejectReasonOk() (*string, bool) {
	if o == nil || IsNil(o.RejectReason) {
		return nil, false
	}
	return o.RejectReason, true
}

// HasRejectReason returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasRejectReason() bool {
	if o != nil && !IsNil(o.RejectReason) {
		return true
	}

	return false
}

// SetRejectReason gets a reference to the given string and assigns it to the RejectReason field.
func (o *RpcTradeOrder) SetRejectReason(v string) {
	o.RejectReason = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *RpcTradeOrder) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *RpcTradeOrder) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetExpireAt returns the ExpireAt field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetExpireAt() time.Time {
	if o == nil || IsNil(o.ExpireAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpireAt
}

// GetExpireAtOk returns a tuple with the ExpireAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetExpireAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpireAt) {
		return nil, false
	}
	return o.ExpireAt, true
}

// HasExpireAt returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasExpireAt() bool {
	if o != nil && !IsNil(o.ExpireAt) {
		return true
	}

	return false
}

// SetExpireAt gets a reference to the given time.Time and assigns it to the ExpireAt field.
func (o *RpcTradeOrder) SetExpireAt(v time.Time) {
	o.ExpireAt = &v
}

// GetLastExecutionAt returns the LastExecutionAt field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetLastExecutionAt() time.Time {
	if o == nil || IsNil(o.LastExecutionAt) {
		var ret time.Time
		return ret
	}
	return *o.LastExecutionAt
}

// GetLastExecutionAtOk returns a tuple with the LastExecutionAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetLastExecutionAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastExecutionAt) {
		return nil, false
	}
	return o.LastExecutionAt, true
}

// HasLastExecutionAt returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasLastExecutionAt() bool {
	if o != nil && !IsNil(o.LastExecutionAt) {
		return true
	}

	return false
}

// SetLastExecutionAt gets a reference to the given time.Time and assigns it to the LastExecutionAt field.
func (o *RpcTradeOrder) SetLastExecutionAt(v time.Time) {
	o.LastExecutionAt = &v
}

// GetCanceledAt returns the CanceledAt field value if set, zero value otherwise.
func (o *RpcTradeOrder) GetCanceledAt() time.Time {
	if o == nil || IsNil(o.CanceledAt) {
		var ret time.Time
		return ret
	}
	return *o.CanceledAt
}

// GetCanceledAtOk returns a tuple with the CanceledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrder) GetCanceledAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CanceledAt) {
		return nil, false
	}
	return o.CanceledAt, true
}

// HasCanceledAt returns a boolean if a field has been set.
func (o *RpcTradeOrder) HasCanceledAt() bool {
	if o != nil && !IsNil(o.CanceledAt) {
		return true
	}

	return false
}

// SetCanceledAt gets a reference to the given time.Time and assigns it to the CanceledAt field.
func (o *RpcTradeOrder) SetCanceledAt(v time.Time) {
	o.CanceledAt = &v
}

func (o RpcTradeOrder) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpcTradeOrder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TradeOrderId) {
		toSerialize["tradeOrderId"] = o.TradeOrderId
	}
	if !IsNil(o.ClientOrderId) {
		toSerialize["clientOrderId"] = o.ClientOrderId
	}
	if !IsNil(o.OriginalClientOrderId) {
		toSerialize["originalClientOrderId"] = o.OriginalClientOrderId
	}
	if !IsNil(o.ExternalOrderId) {
		toSerialize["externalOrderId"] = o.ExternalOrderId
	}
	if !IsNil(o.IdempotencyKey) {
		toSerialize["idempotencyKey"] = o.IdempotencyKey
	}
	if !IsNil(o.Venue) {
		toSerialize["venue"] = o.Venue
	}
	if !IsNil(o.TradingAccountId) {
		toSerialize["tradingAccountId"] = o.TradingAccountId
	}
	if !IsNil(o.ExternalTradingAccountId) {
		toSerialize["externalTradingAccountId"] = o.ExternalTradingAccountId
	}
	if !IsNil(o.InstrumentId) {
		toSerialize["instrumentId"] = o.InstrumentId
	}
	if !IsNil(o.ExternalSymbol) {
		toSerialize["externalSymbol"] = o.ExternalSymbol
	}
	if !IsNil(o.BaseAsset) {
		toSerialize["baseAsset"] = o.BaseAsset
	}
	if !IsNil(o.QuoteAsset) {
		toSerialize["quoteAsset"] = o.QuoteAsset
	}
	if !IsNil(o.OrderType) {
		toSerialize["orderType"] = o.OrderType
	}
	if !IsNil(o.OrderSide) {
		toSerialize["orderSide"] = o.OrderSide
	}
	if !IsNil(o.QuantityType) {
		toSerialize["quantityType"] = o.QuantityType
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.QuoteCurrencyQuantity) {
		toSerialize["quoteCurrencyQuantity"] = o.QuoteCurrencyQuantity
	}
	if !IsNil(o.PositionPercentage) {
		toSerialize["positionPercentage"] = o.PositionPercentage
	}
	if !IsNil(o.QuantityRounding) {
		toSerialize["quantityRounding"] = o.QuantityRounding
	}
	if !IsNil(o.LimitPrice) {
		toSerialize["limitPrice"] = o.LimitPrice
	}
	if !IsNil(o.StopPrice) {
		toSerialize["stopPrice"] = o.StopPrice
	}
	if !IsNil(o.TimeInForce) {
		toSerialize["timeInForce"] = o.TimeInForce
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ExecutedPrice) {
		toSerialize["executedPrice"] = o.ExecutedPrice
	}
	if !IsNil(o.ExecutedPercentage) {
		toSerialize["executedPercentage"] = o.ExecutedPercentage
	}
	if !IsNil(o.ExecutedQuantity) {
		toSerialize["executedQuantity"] = o.ExecutedQuantity
	}
	if !IsNil(o.ExecutedCost) {
		toSerialize["executedCost"] = o.ExecutedCost
	}
	if !IsNil(o.Fees) {
		toSerialize["fees"] = o.Fees
	}
	if !IsNil(o.CancelReason) {
		toSerialize["cancelReason"] = o.CancelReason
	}
	if !IsNil(o.RejectReason) {
		toSerialize["rejectReason"] = o.RejectReason
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.ExpireAt) {
		toSerialize["expireAt"] = o.ExpireAt
	}
	if !IsNil(o.LastExecutionAt) {
		toSerialize["lastExecutionAt"] = o.LastExecutionAt
	}
	if !IsNil(o.CanceledAt) {
		toSerialize["canceledAt"] = o.CanceledAt
	}
	return toSerialize, nil
}

type NullableRpcTradeOrder struct {
	value *RpcTradeOrder
	isSet bool
}

func (v NullableRpcTradeOrder) Get() *RpcTradeOrder {
	return v.value
}

func (v *NullableRpcTradeOrder) Set(val *RpcTradeOrder) {
	v.value = val
	v.isSet = true
}

func (v NullableRpcTradeOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableRpcTradeOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpcTradeOrder(val *RpcTradeOrder) *NullableRpcTradeOrder {
	return &NullableRpcTradeOrder{value: val, isSet: true}
}

func (v NullableRpcTradeOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpcTradeOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


