/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
)

// checks if the RpcInstrument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpcInstrument{}

// RpcInstrument Financial instrument
type RpcInstrument struct {
	// Unique instrument identifier (format: VENUE:BASE/QUOTE)
	InstrumentId *string `json:"instrumentId,omitempty"`
	Venue *Venue `json:"venue,omitempty"`
	Symbol *string `json:"symbol,omitempty"`
	ExternalSymbol *string `json:"externalSymbol,omitempty"`
	Description *string `json:"description,omitempty"`
	InstrumentType *InstrumentType `json:"instrumentType,omitempty"`
	Status *InstrumentStatus `json:"status,omitempty"`
	BaseAsset *string `json:"baseAsset,omitempty"`
	QuoteAsset *string `json:"quoteAsset,omitempty"`
	BaseSecurityType *SecurityType `json:"baseSecurityType,omitempty"`
	QuoteSecurityType *SecurityType `json:"quoteSecurityType,omitempty"`
	BasePrecision *int32 `json:"basePrecision,omitempty"`
	QuotePrecision *int32 `json:"quotePrecision,omitempty"`
	// Decimal value as string
	LotSize *string `json:"lotSize,omitempty"`
	// Decimal value as string
	PipSize *string `json:"pipSize,omitempty"`
	// Decimal value as string
	MinQuantity *string `json:"minQuantity,omitempty"`
	// Decimal value as string
	MaxQuantity *string `json:"maxQuantity,omitempty"`
	// Decimal value as string
	MinNotional *string `json:"minNotional,omitempty"`
	// Decimal value as string
	MaxNotional *string `json:"maxNotional,omitempty"`
	OrderTypes []string `json:"orderTypes,omitempty"`
	TimeInForceOptions []string `json:"timeInForceOptions,omitempty"`
	// Decimal value as string
	Fee *string `json:"fee,omitempty"`
	IsIcebergAllowed *bool `json:"isIcebergAllowed,omitempty"`
	// Decimal value as string
	ContractSize *string `json:"contractSize,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewRpcInstrument instantiates a new RpcInstrument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpcInstrument() *RpcInstrument {
	this := RpcInstrument{}
	return &this
}

// NewRpcInstrumentWithDefaults instantiates a new RpcInstrument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpcInstrumentWithDefaults() *RpcInstrument {
	this := RpcInstrument{}
	return &this
}

// GetInstrumentId returns the InstrumentId field value if set, zero value otherwise.
func (o *RpcInstrument) GetInstrumentId() string {
	if o == nil || IsNil(o.InstrumentId) {
		var ret string
		return ret
	}
	return *o.InstrumentId
}

// GetInstrumentIdOk returns a tuple with the InstrumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetInstrumentIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstrumentId) {
		return nil, false
	}
	return o.InstrumentId, true
}

// HasInstrumentId returns a boolean if a field has been set.
func (o *RpcInstrument) HasInstrumentId() bool {
	if o != nil && !IsNil(o.InstrumentId) {
		return true
	}

	return false
}

// SetInstrumentId gets a reference to the given string and assigns it to the InstrumentId field.
func (o *RpcInstrument) SetInstrumentId(v string) {
	o.InstrumentId = &v
}

// GetVenue returns the Venue field value if set, zero value otherwise.
func (o *RpcInstrument) GetVenue() Venue {
	if o == nil || IsNil(o.Venue) {
		var ret Venue
		return ret
	}
	return *o.Venue
}

// GetVenueOk returns a tuple with the Venue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetVenueOk() (*Venue, bool) {
	if o == nil || IsNil(o.Venue) {
		return nil, false
	}
	return o.Venue, true
}

// HasVenue returns a boolean if a field has been set.
func (o *RpcInstrument) HasVenue() bool {
	if o != nil && !IsNil(o.Venue) {
		return true
	}

	return false
}

// SetVenue gets a reference to the given Venue and assigns it to the Venue field.
func (o *RpcInstrument) SetVenue(v Venue) {
	o.Venue = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *RpcInstrument) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *RpcInstrument) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *RpcInstrument) SetSymbol(v string) {
	o.Symbol = &v
}

// GetExternalSymbol returns the ExternalSymbol field value if set, zero value otherwise.
func (o *RpcInstrument) GetExternalSymbol() string {
	if o == nil || IsNil(o.ExternalSymbol) {
		var ret string
		return ret
	}
	return *o.ExternalSymbol
}

// GetExternalSymbolOk returns a tuple with the ExternalSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetExternalSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSymbol) {
		return nil, false
	}
	return o.ExternalSymbol, true
}

// HasExternalSymbol returns a boolean if a field has been set.
func (o *RpcInstrument) HasExternalSymbol() bool {
	if o != nil && !IsNil(o.ExternalSymbol) {
		return true
	}

	return false
}

// SetExternalSymbol gets a reference to the given string and assigns it to the ExternalSymbol field.
func (o *RpcInstrument) SetExternalSymbol(v string) {
	o.ExternalSymbol = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RpcInstrument) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RpcInstrument) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RpcInstrument) SetDescription(v string) {
	o.Description = &v
}

// GetInstrumentType returns the InstrumentType field value if set, zero value otherwise.
func (o *RpcInstrument) GetInstrumentType() InstrumentType {
	if o == nil || IsNil(o.InstrumentType) {
		var ret InstrumentType
		return ret
	}
	return *o.InstrumentType
}

// GetInstrumentTypeOk returns a tuple with the InstrumentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetInstrumentTypeOk() (*InstrumentType, bool) {
	if o == nil || IsNil(o.InstrumentType) {
		return nil, false
	}
	return o.InstrumentType, true
}

// HasInstrumentType returns a boolean if a field has been set.
func (o *RpcInstrument) HasInstrumentType() bool {
	if o != nil && !IsNil(o.InstrumentType) {
		return true
	}

	return false
}

// SetInstrumentType gets a reference to the given InstrumentType and assigns it to the InstrumentType field.
func (o *RpcInstrument) SetInstrumentType(v InstrumentType) {
	o.InstrumentType = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RpcInstrument) GetStatus() InstrumentStatus {
	if o == nil || IsNil(o.Status) {
		var ret InstrumentStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetStatusOk() (*InstrumentStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RpcInstrument) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given InstrumentStatus and assigns it to the Status field.
func (o *RpcInstrument) SetStatus(v InstrumentStatus) {
	o.Status = &v
}

// GetBaseAsset returns the BaseAsset field value if set, zero value otherwise.
func (o *RpcInstrument) GetBaseAsset() string {
	if o == nil || IsNil(o.BaseAsset) {
		var ret string
		return ret
	}
	return *o.BaseAsset
}

// GetBaseAssetOk returns a tuple with the BaseAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetBaseAssetOk() (*string, bool) {
	if o == nil || IsNil(o.BaseAsset) {
		return nil, false
	}
	return o.BaseAsset, true
}

// HasBaseAsset returns a boolean if a field has been set.
func (o *RpcInstrument) HasBaseAsset() bool {
	if o != nil && !IsNil(o.BaseAsset) {
		return true
	}

	return false
}

// SetBaseAsset gets a reference to the given string and assigns it to the BaseAsset field.
func (o *RpcInstrument) SetBaseAsset(v string) {
	o.BaseAsset = &v
}

// GetQuoteAsset returns the QuoteAsset field value if set, zero value otherwise.
func (o *RpcInstrument) GetQuoteAsset() string {
	if o == nil || IsNil(o.QuoteAsset) {
		var ret string
		return ret
	}
	return *o.QuoteAsset
}

// GetQuoteAssetOk returns a tuple with the QuoteAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetQuoteAssetOk() (*string, bool) {
	if o == nil || IsNil(o.QuoteAsset) {
		return nil, false
	}
	return o.QuoteAsset, true
}

// HasQuoteAsset returns a boolean if a field has been set.
func (o *RpcInstrument) HasQuoteAsset() bool {
	if o != nil && !IsNil(o.QuoteAsset) {
		return true
	}

	return false
}

// SetQuoteAsset gets a reference to the given string and assigns it to the QuoteAsset field.
func (o *RpcInstrument) SetQuoteAsset(v string) {
	o.QuoteAsset = &v
}

// GetBaseSecurityType returns the BaseSecurityType field value if set, zero value otherwise.
func (o *RpcInstrument) GetBaseSecurityType() SecurityType {
	if o == nil || IsNil(o.BaseSecurityType) {
		var ret SecurityType
		return ret
	}
	return *o.BaseSecurityType
}

// GetBaseSecurityTypeOk returns a tuple with the BaseSecurityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetBaseSecurityTypeOk() (*SecurityType, bool) {
	if o == nil || IsNil(o.BaseSecurityType) {
		return nil, false
	}
	return o.BaseSecurityType, true
}

// HasBaseSecurityType returns a boolean if a field has been set.
func (o *RpcInstrument) HasBaseSecurityType() bool {
	if o != nil && !IsNil(o.BaseSecurityType) {
		return true
	}

	return false
}

// SetBaseSecurityType gets a reference to the given SecurityType and assigns it to the BaseSecurityType field.
func (o *RpcInstrument) SetBaseSecurityType(v SecurityType) {
	o.BaseSecurityType = &v
}

// GetQuoteSecurityType returns the QuoteSecurityType field value if set, zero value otherwise.
func (o *RpcInstrument) GetQuoteSecurityType() SecurityType {
	if o == nil || IsNil(o.QuoteSecurityType) {
		var ret SecurityType
		return ret
	}
	return *o.QuoteSecurityType
}

// GetQuoteSecurityTypeOk returns a tuple with the QuoteSecurityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetQuoteSecurityTypeOk() (*SecurityType, bool) {
	if o == nil || IsNil(o.QuoteSecurityType) {
		return nil, false
	}
	return o.QuoteSecurityType, true
}

// HasQuoteSecurityType returns a boolean if a field has been set.
func (o *RpcInstrument) HasQuoteSecurityType() bool {
	if o != nil && !IsNil(o.QuoteSecurityType) {
		return true
	}

	return false
}

// SetQuoteSecurityType gets a reference to the given SecurityType and assigns it to the QuoteSecurityType field.
func (o *RpcInstrument) SetQuoteSecurityType(v SecurityType) {
	o.QuoteSecurityType = &v
}

// GetBasePrecision returns the BasePrecision field value if set, zero value otherwise.
func (o *RpcInstrument) GetBasePrecision() int32 {
	if o == nil || IsNil(o.BasePrecision) {
		var ret int32
		return ret
	}
	return *o.BasePrecision
}

// GetBasePrecisionOk returns a tuple with the BasePrecision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetBasePrecisionOk() (*int32, bool) {
	if o == nil || IsNil(o.BasePrecision) {
		return nil, false
	}
	return o.BasePrecision, true
}

// HasBasePrecision returns a boolean if a field has been set.
func (o *RpcInstrument) HasBasePrecision() bool {
	if o != nil && !IsNil(o.BasePrecision) {
		return true
	}

	return false
}

// SetBasePrecision gets a reference to the given int32 and assigns it to the BasePrecision field.
func (o *RpcInstrument) SetBasePrecision(v int32) {
	o.BasePrecision = &v
}

// GetQuotePrecision returns the QuotePrecision field value if set, zero value otherwise.
func (o *RpcInstrument) GetQuotePrecision() int32 {
	if o == nil || IsNil(o.QuotePrecision) {
		var ret int32
		return ret
	}
	return *o.QuotePrecision
}

// GetQuotePrecisionOk returns a tuple with the QuotePrecision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetQuotePrecisionOk() (*int32, bool) {
	if o == nil || IsNil(o.QuotePrecision) {
		return nil, false
	}
	return o.QuotePrecision, true
}

// HasQuotePrecision returns a boolean if a field has been set.
func (o *RpcInstrument) HasQuotePrecision() bool {
	if o != nil && !IsNil(o.QuotePrecision) {
		return true
	}

	return false
}

// SetQuotePrecision gets a reference to the given int32 and assigns it to the QuotePrecision field.
func (o *RpcInstrument) SetQuotePrecision(v int32) {
	o.QuotePrecision = &v
}

// GetLotSize returns the LotSize field value if set, zero value otherwise.
func (o *RpcInstrument) GetLotSize() string {
	if o == nil || IsNil(o.LotSize) {
		var ret string
		return ret
	}
	return *o.LotSize
}

// GetLotSizeOk returns a tuple with the LotSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetLotSizeOk() (*string, bool) {
	if o == nil || IsNil(o.LotSize) {
		return nil, false
	}
	return o.LotSize, true
}

// HasLotSize returns a boolean if a field has been set.
func (o *RpcInstrument) HasLotSize() bool {
	if o != nil && !IsNil(o.LotSize) {
		return true
	}

	return false
}

// SetLotSize gets a reference to the given string and assigns it to the LotSize field.
func (o *RpcInstrument) SetLotSize(v string) {
	o.LotSize = &v
}

// GetPipSize returns the PipSize field value if set, zero value otherwise.
func (o *RpcInstrument) GetPipSize() string {
	if o == nil || IsNil(o.PipSize) {
		var ret string
		return ret
	}
	return *o.PipSize
}

// GetPipSizeOk returns a tuple with the PipSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetPipSizeOk() (*string, bool) {
	if o == nil || IsNil(o.PipSize) {
		return nil, false
	}
	return o.PipSize, true
}

// HasPipSize returns a boolean if a field has been set.
func (o *RpcInstrument) HasPipSize() bool {
	if o != nil && !IsNil(o.PipSize) {
		return true
	}

	return false
}

// SetPipSize gets a reference to the given string and assigns it to the PipSize field.
func (o *RpcInstrument) SetPipSize(v string) {
	o.PipSize = &v
}

// GetMinQuantity returns the MinQuantity field value if set, zero value otherwise.
func (o *RpcInstrument) GetMinQuantity() string {
	if o == nil || IsNil(o.MinQuantity) {
		var ret string
		return ret
	}
	return *o.MinQuantity
}

// GetMinQuantityOk returns a tuple with the MinQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetMinQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.MinQuantity) {
		return nil, false
	}
	return o.MinQuantity, true
}

// HasMinQuantity returns a boolean if a field has been set.
func (o *RpcInstrument) HasMinQuantity() bool {
	if o != nil && !IsNil(o.MinQuantity) {
		return true
	}

	return false
}

// SetMinQuantity gets a reference to the given string and assigns it to the MinQuantity field.
func (o *RpcInstrument) SetMinQuantity(v string) {
	o.MinQuantity = &v
}

// GetMaxQuantity returns the MaxQuantity field value if set, zero value otherwise.
func (o *RpcInstrument) GetMaxQuantity() string {
	if o == nil || IsNil(o.MaxQuantity) {
		var ret string
		return ret
	}
	return *o.MaxQuantity
}

// GetMaxQuantityOk returns a tuple with the MaxQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetMaxQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.MaxQuantity) {
		return nil, false
	}
	return o.MaxQuantity, true
}

// HasMaxQuantity returns a boolean if a field has been set.
func (o *RpcInstrument) HasMaxQuantity() bool {
	if o != nil && !IsNil(o.MaxQuantity) {
		return true
	}

	return false
}

// SetMaxQuantity gets a reference to the given string and assigns it to the MaxQuantity field.
func (o *RpcInstrument) SetMaxQuantity(v string) {
	o.MaxQuantity = &v
}

// GetMinNotional returns the MinNotional field value if set, zero value otherwise.
func (o *RpcInstrument) GetMinNotional() string {
	if o == nil || IsNil(o.MinNotional) {
		var ret string
		return ret
	}
	return *o.MinNotional
}

// GetMinNotionalOk returns a tuple with the MinNotional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetMinNotionalOk() (*string, bool) {
	if o == nil || IsNil(o.MinNotional) {
		return nil, false
	}
	return o.MinNotional, true
}

// HasMinNotional returns a boolean if a field has been set.
func (o *RpcInstrument) HasMinNotional() bool {
	if o != nil && !IsNil(o.MinNotional) {
		return true
	}

	return false
}

// SetMinNotional gets a reference to the given string and assigns it to the MinNotional field.
func (o *RpcInstrument) SetMinNotional(v string) {
	o.MinNotional = &v
}

// GetMaxNotional returns the MaxNotional field value if set, zero value otherwise.
func (o *RpcInstrument) GetMaxNotional() string {
	if o == nil || IsNil(o.MaxNotional) {
		var ret string
		return ret
	}
	return *o.MaxNotional
}

// GetMaxNotionalOk returns a tuple with the MaxNotional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetMaxNotionalOk() (*string, bool) {
	if o == nil || IsNil(o.MaxNotional) {
		return nil, false
	}
	return o.MaxNotional, true
}

// HasMaxNotional returns a boolean if a field has been set.
func (o *RpcInstrument) HasMaxNotional() bool {
	if o != nil && !IsNil(o.MaxNotional) {
		return true
	}

	return false
}

// SetMaxNotional gets a reference to the given string and assigns it to the MaxNotional field.
func (o *RpcInstrument) SetMaxNotional(v string) {
	o.MaxNotional = &v
}

// GetOrderTypes returns the OrderTypes field value if set, zero value otherwise.
func (o *RpcInstrument) GetOrderTypes() []string {
	if o == nil || IsNil(o.OrderTypes) {
		var ret []string
		return ret
	}
	return o.OrderTypes
}

// GetOrderTypesOk returns a tuple with the OrderTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetOrderTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.OrderTypes) {
		return nil, false
	}
	return o.OrderTypes, true
}

// HasOrderTypes returns a boolean if a field has been set.
func (o *RpcInstrument) HasOrderTypes() bool {
	if o != nil && !IsNil(o.OrderTypes) {
		return true
	}

	return false
}

// SetOrderTypes gets a reference to the given []string and assigns it to the OrderTypes field.
func (o *RpcInstrument) SetOrderTypes(v []string) {
	o.OrderTypes = v
}

// GetTimeInForceOptions returns the TimeInForceOptions field value if set, zero value otherwise.
func (o *RpcInstrument) GetTimeInForceOptions() []string {
	if o == nil || IsNil(o.TimeInForceOptions) {
		var ret []string
		return ret
	}
	return o.TimeInForceOptions
}

// GetTimeInForceOptionsOk returns a tuple with the TimeInForceOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetTimeInForceOptionsOk() ([]string, bool) {
	if o == nil || IsNil(o.TimeInForceOptions) {
		return nil, false
	}
	return o.TimeInForceOptions, true
}

// HasTimeInForceOptions returns a boolean if a field has been set.
func (o *RpcInstrument) HasTimeInForceOptions() bool {
	if o != nil && !IsNil(o.TimeInForceOptions) {
		return true
	}

	return false
}

// SetTimeInForceOptions gets a reference to the given []string and assigns it to the TimeInForceOptions field.
func (o *RpcInstrument) SetTimeInForceOptions(v []string) {
	o.TimeInForceOptions = v
}

// GetFee returns the Fee field value if set, zero value otherwise.
func (o *RpcInstrument) GetFee() string {
	if o == nil || IsNil(o.Fee) {
		var ret string
		return ret
	}
	return *o.Fee
}

// GetFeeOk returns a tuple with the Fee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetFeeOk() (*string, bool) {
	if o == nil || IsNil(o.Fee) {
		return nil, false
	}
	return o.Fee, true
}

// HasFee returns a boolean if a field has been set.
func (o *RpcInstrument) HasFee() bool {
	if o != nil && !IsNil(o.Fee) {
		return true
	}

	return false
}

// SetFee gets a reference to the given string and assigns it to the Fee field.
func (o *RpcInstrument) SetFee(v string) {
	o.Fee = &v
}

// GetIsIcebergAllowed returns the IsIcebergAllowed field value if set, zero value otherwise.
func (o *RpcInstrument) GetIsIcebergAllowed() bool {
	if o == nil || IsNil(o.IsIcebergAllowed) {
		var ret bool
		return ret
	}
	return *o.IsIcebergAllowed
}

// GetIsIcebergAllowedOk returns a tuple with the IsIcebergAllowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetIsIcebergAllowedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsIcebergAllowed) {
		return nil, false
	}
	return o.IsIcebergAllowed, true
}

// HasIsIcebergAllowed returns a boolean if a field has been set.
func (o *RpcInstrument) HasIsIcebergAllowed() bool {
	if o != nil && !IsNil(o.IsIcebergAllowed) {
		return true
	}

	return false
}

// SetIsIcebergAllowed gets a reference to the given bool and assigns it to the IsIcebergAllowed field.
func (o *RpcInstrument) SetIsIcebergAllowed(v bool) {
	o.IsIcebergAllowed = &v
}

// GetContractSize returns the ContractSize field value if set, zero value otherwise.
func (o *RpcInstrument) GetContractSize() string {
	if o == nil || IsNil(o.ContractSize) {
		var ret string
		return ret
	}
	return *o.ContractSize
}

// GetContractSizeOk returns a tuple with the ContractSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetContractSizeOk() (*string, bool) {
	if o == nil || IsNil(o.ContractSize) {
		return nil, false
	}
	return o.ContractSize, true
}

// HasContractSize returns a boolean if a field has been set.
func (o *RpcInstrument) HasContractSize() bool {
	if o != nil && !IsNil(o.ContractSize) {
		return true
	}

	return false
}

// SetContractSize gets a reference to the given string and assigns it to the ContractSize field.
func (o *RpcInstrument) SetContractSize(v string) {
	o.ContractSize = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *RpcInstrument) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *RpcInstrument) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *RpcInstrument) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *RpcInstrument) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcInstrument) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *RpcInstrument) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *RpcInstrument) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o RpcInstrument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpcInstrument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstrumentId) {
		toSerialize["instrumentId"] = o.InstrumentId
	}
	if !IsNil(o.Venue) {
		toSerialize["venue"] = o.Venue
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	if !IsNil(o.ExternalSymbol) {
		toSerialize["externalSymbol"] = o.ExternalSymbol
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.InstrumentType) {
		toSerialize["instrumentType"] = o.InstrumentType
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.BaseAsset) {
		toSerialize["baseAsset"] = o.BaseAsset
	}
	if !IsNil(o.QuoteAsset) {
		toSerialize["quoteAsset"] = o.QuoteAsset
	}
	if !IsNil(o.BaseSecurityType) {
		toSerialize["baseSecurityType"] = o.BaseSecurityType
	}
	if !IsNil(o.QuoteSecurityType) {
		toSerialize["quoteSecurityType"] = o.QuoteSecurityType
	}
	if !IsNil(o.BasePrecision) {
		toSerialize["basePrecision"] = o.BasePrecision
	}
	if !IsNil(o.QuotePrecision) {
		toSerialize["quotePrecision"] = o.QuotePrecision
	}
	if !IsNil(o.LotSize) {
		toSerialize["lotSize"] = o.LotSize
	}
	if !IsNil(o.PipSize) {
		toSerialize["pipSize"] = o.PipSize
	}
	if !IsNil(o.MinQuantity) {
		toSerialize["minQuantity"] = o.MinQuantity
	}
	if !IsNil(o.MaxQuantity) {
		toSerialize["maxQuantity"] = o.MaxQuantity
	}
	if !IsNil(o.MinNotional) {
		toSerialize["minNotional"] = o.MinNotional
	}
	if !IsNil(o.MaxNotional) {
		toSerialize["maxNotional"] = o.MaxNotional
	}
	if !IsNil(o.OrderTypes) {
		toSerialize["orderTypes"] = o.OrderTypes
	}
	if !IsNil(o.TimeInForceOptions) {
		toSerialize["timeInForceOptions"] = o.TimeInForceOptions
	}
	if !IsNil(o.Fee) {
		toSerialize["fee"] = o.Fee
	}
	if !IsNil(o.IsIcebergAllowed) {
		toSerialize["isIcebergAllowed"] = o.IsIcebergAllowed
	}
	if !IsNil(o.ContractSize) {
		toSerialize["contractSize"] = o.ContractSize
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableRpcInstrument struct {
	value *RpcInstrument
	isSet bool
}

func (v NullableRpcInstrument) Get() *RpcInstrument {
	return v.value
}

func (v *NullableRpcInstrument) Set(val *RpcInstrument) {
	v.value = val
	v.isSet = true
}

func (v NullableRpcInstrument) IsSet() bool {
	return v.isSet
}

func (v *NullableRpcInstrument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpcInstrument(val *RpcInstrument) *NullableRpcInstrument {
	return &NullableRpcInstrument{value: val, isSet: true}
}

func (v NullableRpcInstrument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpcInstrument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


