/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RpcGetPortfolioParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpcGetPortfolioParams{}

// RpcGetPortfolioParams Request to get portfolio for a trading account
type RpcGetPortfolioParams struct {
	// Trading account ID
	TradingAccountId string `json:"tradingAccountId"`
}

type _RpcGetPortfolioParams RpcGetPortfolioParams

// NewRpcGetPortfolioParams instantiates a new RpcGetPortfolioParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpcGetPortfolioParams(tradingAccountId string) *RpcGetPortfolioParams {
	this := RpcGetPortfolioParams{}
	this.TradingAccountId = tradingAccountId
	return &this
}

// NewRpcGetPortfolioParamsWithDefaults instantiates a new RpcGetPortfolioParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpcGetPortfolioParamsWithDefaults() *RpcGetPortfolioParams {
	this := RpcGetPortfolioParams{}
	return &this
}

// GetTradingAccountId returns the TradingAccountId field value
func (o *RpcGetPortfolioParams) GetTradingAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TradingAccountId
}

// GetTradingAccountIdOk returns a tuple with the TradingAccountId field value
// and a boolean to check if the value has been set.
func (o *RpcGetPortfolioParams) GetTradingAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TradingAccountId, true
}

// SetTradingAccountId sets field value
func (o *RpcGetPortfolioParams) SetTradingAccountId(v string) {
	o.TradingAccountId = v
}

func (o RpcGetPortfolioParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpcGetPortfolioParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tradingAccountId"] = o.TradingAccountId
	return toSerialize, nil
}

func (o *RpcGetPortfolioParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tradingAccountId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRpcGetPortfolioParams := _RpcGetPortfolioParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRpcGetPortfolioParams)

	if err != nil {
		return err
	}

	*o = RpcGetPortfolioParams(varRpcGetPortfolioParams)

	return err
}

type NullableRpcGetPortfolioParams struct {
	value *RpcGetPortfolioParams
	isSet bool
}

func (v NullableRpcGetPortfolioParams) Get() *RpcGetPortfolioParams {
	return v.value
}

func (v *NullableRpcGetPortfolioParams) Set(val *RpcGetPortfolioParams) {
	v.value = val
	v.isSet = true
}

func (v NullableRpcGetPortfolioParams) IsSet() bool {
	return v.isSet
}

func (v *NullableRpcGetPortfolioParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpcGetPortfolioParams(val *RpcGetPortfolioParams) *NullableRpcGetPortfolioParams {
	return &NullableRpcGetPortfolioParams{value: val, isSet: true}
}

func (v NullableRpcGetPortfolioParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpcGetPortfolioParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


