/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the WsSubscribePush type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WsSubscribePush{}

// WsSubscribePush Server-initiated subscribe notification
type WsSubscribePush struct {
	Recoverable *bool `json:"recoverable,omitempty"`
	Epoch *string `json:"epoch,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	Positioned *bool `json:"positioned,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
}

// NewWsSubscribePush instantiates a new WsSubscribePush object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWsSubscribePush() *WsSubscribePush {
	this := WsSubscribePush{}
	return &this
}

// NewWsSubscribePushWithDefaults instantiates a new WsSubscribePush object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWsSubscribePushWithDefaults() *WsSubscribePush {
	this := WsSubscribePush{}
	return &this
}

// GetRecoverable returns the Recoverable field value if set, zero value otherwise.
func (o *WsSubscribePush) GetRecoverable() bool {
	if o == nil || IsNil(o.Recoverable) {
		var ret bool
		return ret
	}
	return *o.Recoverable
}

// GetRecoverableOk returns a tuple with the Recoverable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsSubscribePush) GetRecoverableOk() (*bool, bool) {
	if o == nil || IsNil(o.Recoverable) {
		return nil, false
	}
	return o.Recoverable, true
}

// HasRecoverable returns a boolean if a field has been set.
func (o *WsSubscribePush) HasRecoverable() bool {
	if o != nil && !IsNil(o.Recoverable) {
		return true
	}

	return false
}

// SetRecoverable gets a reference to the given bool and assigns it to the Recoverable field.
func (o *WsSubscribePush) SetRecoverable(v bool) {
	o.Recoverable = &v
}

// GetEpoch returns the Epoch field value if set, zero value otherwise.
func (o *WsSubscribePush) GetEpoch() string {
	if o == nil || IsNil(o.Epoch) {
		var ret string
		return ret
	}
	return *o.Epoch
}

// GetEpochOk returns a tuple with the Epoch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsSubscribePush) GetEpochOk() (*string, bool) {
	if o == nil || IsNil(o.Epoch) {
		return nil, false
	}
	return o.Epoch, true
}

// HasEpoch returns a boolean if a field has been set.
func (o *WsSubscribePush) HasEpoch() bool {
	if o != nil && !IsNil(o.Epoch) {
		return true
	}

	return false
}

// SetEpoch gets a reference to the given string and assigns it to the Epoch field.
func (o *WsSubscribePush) SetEpoch(v string) {
	o.Epoch = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *WsSubscribePush) GetOffset() int64 {
	if o == nil || IsNil(o.Offset) {
		var ret int64
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsSubscribePush) GetOffsetOk() (*int64, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *WsSubscribePush) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int64 and assigns it to the Offset field.
func (o *WsSubscribePush) SetOffset(v int64) {
	o.Offset = &v
}

// GetPositioned returns the Positioned field value if set, zero value otherwise.
func (o *WsSubscribePush) GetPositioned() bool {
	if o == nil || IsNil(o.Positioned) {
		var ret bool
		return ret
	}
	return *o.Positioned
}

// GetPositionedOk returns a tuple with the Positioned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsSubscribePush) GetPositionedOk() (*bool, bool) {
	if o == nil || IsNil(o.Positioned) {
		return nil, false
	}
	return o.Positioned, true
}

// HasPositioned returns a boolean if a field has been set.
func (o *WsSubscribePush) HasPositioned() bool {
	if o != nil && !IsNil(o.Positioned) {
		return true
	}

	return false
}

// SetPositioned gets a reference to the given bool and assigns it to the Positioned field.
func (o *WsSubscribePush) SetPositioned(v bool) {
	o.Positioned = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *WsSubscribePush) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsSubscribePush) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *WsSubscribePush) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *WsSubscribePush) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o WsSubscribePush) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WsSubscribePush) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Recoverable) {
		toSerialize["recoverable"] = o.Recoverable
	}
	if !IsNil(o.Epoch) {
		toSerialize["epoch"] = o.Epoch
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Positioned) {
		toSerialize["positioned"] = o.Positioned
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableWsSubscribePush struct {
	value *WsSubscribePush
	isSet bool
}

func (v NullableWsSubscribePush) Get() *WsSubscribePush {
	return v.value
}

func (v *NullableWsSubscribePush) Set(val *WsSubscribePush) {
	v.value = val
	v.isSet = true
}

func (v NullableWsSubscribePush) IsSet() bool {
	return v.isSet
}

func (v *NullableWsSubscribePush) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWsSubscribePush(val *WsSubscribePush) *NullableWsSubscribePush {
	return &NullableWsSubscribePush{value: val, isSet: true}
}

func (v NullableWsSubscribePush) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWsSubscribePush) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


