/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WsCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WsCommand{}

// WsCommand WebSocket command sent from client to server. Only one command field should be set per message.
type WsCommand struct {
	// Unique command ID for request-response correlation
	Id int32 `json:"id"`
	Connect *WsConnectRequest `json:"connect,omitempty"`
	Subscribe *WsSubscribeRequest `json:"subscribe,omitempty"`
	Unsubscribe *WsUnsubscribeRequest `json:"unsubscribe,omitempty"`
	Publish *WsPublishRequest `json:"publish,omitempty"`
	Presence *WsPresenceRequest `json:"presence,omitempty"`
	PresenceStats *WsPresenceStatsRequest `json:"presenceStats,omitempty"`
	History *WsHistoryRequest `json:"history,omitempty"`
	// Ping request to keep connection alive
	Ping map[string]interface{} `json:"ping,omitempty"`
	Send *WsSendRequest `json:"send,omitempty"`
	Rpc *WsRPCRequest `json:"rpc,omitempty"`
	Refresh *WsRefreshRequest `json:"refresh,omitempty"`
	SubRefresh *WsSubRefreshRequest `json:"subRefresh,omitempty"`
}

type _WsCommand WsCommand

// NewWsCommand instantiates a new WsCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWsCommand(id int32) *WsCommand {
	this := WsCommand{}
	this.Id = id
	return &this
}

// NewWsCommandWithDefaults instantiates a new WsCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWsCommandWithDefaults() *WsCommand {
	this := WsCommand{}
	return &this
}

// GetId returns the Id field value
func (o *WsCommand) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WsCommand) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WsCommand) SetId(v int32) {
	o.Id = v
}

// GetConnect returns the Connect field value if set, zero value otherwise.
func (o *WsCommand) GetConnect() WsConnectRequest {
	if o == nil || IsNil(o.Connect) {
		var ret WsConnectRequest
		return ret
	}
	return *o.Connect
}

// GetConnectOk returns a tuple with the Connect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsCommand) GetConnectOk() (*WsConnectRequest, bool) {
	if o == nil || IsNil(o.Connect) {
		return nil, false
	}
	return o.Connect, true
}

// HasConnect returns a boolean if a field has been set.
func (o *WsCommand) HasConnect() bool {
	if o != nil && !IsNil(o.Connect) {
		return true
	}

	return false
}

// SetConnect gets a reference to the given WsConnectRequest and assigns it to the Connect field.
func (o *WsCommand) SetConnect(v WsConnectRequest) {
	o.Connect = &v
}

// GetSubscribe returns the Subscribe field value if set, zero value otherwise.
func (o *WsCommand) GetSubscribe() WsSubscribeRequest {
	if o == nil || IsNil(o.Subscribe) {
		var ret WsSubscribeRequest
		return ret
	}
	return *o.Subscribe
}

// GetSubscribeOk returns a tuple with the Subscribe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsCommand) GetSubscribeOk() (*WsSubscribeRequest, bool) {
	if o == nil || IsNil(o.Subscribe) {
		return nil, false
	}
	return o.Subscribe, true
}

// HasSubscribe returns a boolean if a field has been set.
func (o *WsCommand) HasSubscribe() bool {
	if o != nil && !IsNil(o.Subscribe) {
		return true
	}

	return false
}

// SetSubscribe gets a reference to the given WsSubscribeRequest and assigns it to the Subscribe field.
func (o *WsCommand) SetSubscribe(v WsSubscribeRequest) {
	o.Subscribe = &v
}

// GetUnsubscribe returns the Unsubscribe field value if set, zero value otherwise.
func (o *WsCommand) GetUnsubscribe() WsUnsubscribeRequest {
	if o == nil || IsNil(o.Unsubscribe) {
		var ret WsUnsubscribeRequest
		return ret
	}
	return *o.Unsubscribe
}

// GetUnsubscribeOk returns a tuple with the Unsubscribe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsCommand) GetUnsubscribeOk() (*WsUnsubscribeRequest, bool) {
	if o == nil || IsNil(o.Unsubscribe) {
		return nil, false
	}
	return o.Unsubscribe, true
}

// HasUnsubscribe returns a boolean if a field has been set.
func (o *WsCommand) HasUnsubscribe() bool {
	if o != nil && !IsNil(o.Unsubscribe) {
		return true
	}

	return false
}

// SetUnsubscribe gets a reference to the given WsUnsubscribeRequest and assigns it to the Unsubscribe field.
func (o *WsCommand) SetUnsubscribe(v WsUnsubscribeRequest) {
	o.Unsubscribe = &v
}

// GetPublish returns the Publish field value if set, zero value otherwise.
func (o *WsCommand) GetPublish() WsPublishRequest {
	if o == nil || IsNil(o.Publish) {
		var ret WsPublishRequest
		return ret
	}
	return *o.Publish
}

// GetPublishOk returns a tuple with the Publish field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsCommand) GetPublishOk() (*WsPublishRequest, bool) {
	if o == nil || IsNil(o.Publish) {
		return nil, false
	}
	return o.Publish, true
}

// HasPublish returns a boolean if a field has been set.
func (o *WsCommand) HasPublish() bool {
	if o != nil && !IsNil(o.Publish) {
		return true
	}

	return false
}

// SetPublish gets a reference to the given WsPublishRequest and assigns it to the Publish field.
func (o *WsCommand) SetPublish(v WsPublishRequest) {
	o.Publish = &v
}

// GetPresence returns the Presence field value if set, zero value otherwise.
func (o *WsCommand) GetPresence() WsPresenceRequest {
	if o == nil || IsNil(o.Presence) {
		var ret WsPresenceRequest
		return ret
	}
	return *o.Presence
}

// GetPresenceOk returns a tuple with the Presence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsCommand) GetPresenceOk() (*WsPresenceRequest, bool) {
	if o == nil || IsNil(o.Presence) {
		return nil, false
	}
	return o.Presence, true
}

// HasPresence returns a boolean if a field has been set.
func (o *WsCommand) HasPresence() bool {
	if o != nil && !IsNil(o.Presence) {
		return true
	}

	return false
}

// SetPresence gets a reference to the given WsPresenceRequest and assigns it to the Presence field.
func (o *WsCommand) SetPresence(v WsPresenceRequest) {
	o.Presence = &v
}

// GetPresenceStats returns the PresenceStats field value if set, zero value otherwise.
func (o *WsCommand) GetPresenceStats() WsPresenceStatsRequest {
	if o == nil || IsNil(o.PresenceStats) {
		var ret WsPresenceStatsRequest
		return ret
	}
	return *o.PresenceStats
}

// GetPresenceStatsOk returns a tuple with the PresenceStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsCommand) GetPresenceStatsOk() (*WsPresenceStatsRequest, bool) {
	if o == nil || IsNil(o.PresenceStats) {
		return nil, false
	}
	return o.PresenceStats, true
}

// HasPresenceStats returns a boolean if a field has been set.
func (o *WsCommand) HasPresenceStats() bool {
	if o != nil && !IsNil(o.PresenceStats) {
		return true
	}

	return false
}

// SetPresenceStats gets a reference to the given WsPresenceStatsRequest and assigns it to the PresenceStats field.
func (o *WsCommand) SetPresenceStats(v WsPresenceStatsRequest) {
	o.PresenceStats = &v
}

// GetHistory returns the History field value if set, zero value otherwise.
func (o *WsCommand) GetHistory() WsHistoryRequest {
	if o == nil || IsNil(o.History) {
		var ret WsHistoryRequest
		return ret
	}
	return *o.History
}

// GetHistoryOk returns a tuple with the History field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsCommand) GetHistoryOk() (*WsHistoryRequest, bool) {
	if o == nil || IsNil(o.History) {
		return nil, false
	}
	return o.History, true
}

// HasHistory returns a boolean if a field has been set.
func (o *WsCommand) HasHistory() bool {
	if o != nil && !IsNil(o.History) {
		return true
	}

	return false
}

// SetHistory gets a reference to the given WsHistoryRequest and assigns it to the History field.
func (o *WsCommand) SetHistory(v WsHistoryRequest) {
	o.History = &v
}

// GetPing returns the Ping field value if set, zero value otherwise.
func (o *WsCommand) GetPing() map[string]interface{} {
	if o == nil || IsNil(o.Ping) {
		var ret map[string]interface{}
		return ret
	}
	return o.Ping
}

// GetPingOk returns a tuple with the Ping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsCommand) GetPingOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Ping) {
		return map[string]interface{}{}, false
	}
	return o.Ping, true
}

// HasPing returns a boolean if a field has been set.
func (o *WsCommand) HasPing() bool {
	if o != nil && !IsNil(o.Ping) {
		return true
	}

	return false
}

// SetPing gets a reference to the given map[string]interface{} and assigns it to the Ping field.
func (o *WsCommand) SetPing(v map[string]interface{}) {
	o.Ping = v
}

// GetSend returns the Send field value if set, zero value otherwise.
func (o *WsCommand) GetSend() WsSendRequest {
	if o == nil || IsNil(o.Send) {
		var ret WsSendRequest
		return ret
	}
	return *o.Send
}

// GetSendOk returns a tuple with the Send field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsCommand) GetSendOk() (*WsSendRequest, bool) {
	if o == nil || IsNil(o.Send) {
		return nil, false
	}
	return o.Send, true
}

// HasSend returns a boolean if a field has been set.
func (o *WsCommand) HasSend() bool {
	if o != nil && !IsNil(o.Send) {
		return true
	}

	return false
}

// SetSend gets a reference to the given WsSendRequest and assigns it to the Send field.
func (o *WsCommand) SetSend(v WsSendRequest) {
	o.Send = &v
}

// GetRpc returns the Rpc field value if set, zero value otherwise.
func (o *WsCommand) GetRpc() WsRPCRequest {
	if o == nil || IsNil(o.Rpc) {
		var ret WsRPCRequest
		return ret
	}
	return *o.Rpc
}

// GetRpcOk returns a tuple with the Rpc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsCommand) GetRpcOk() (*WsRPCRequest, bool) {
	if o == nil || IsNil(o.Rpc) {
		return nil, false
	}
	return o.Rpc, true
}

// HasRpc returns a boolean if a field has been set.
func (o *WsCommand) HasRpc() bool {
	if o != nil && !IsNil(o.Rpc) {
		return true
	}

	return false
}

// SetRpc gets a reference to the given WsRPCRequest and assigns it to the Rpc field.
func (o *WsCommand) SetRpc(v WsRPCRequest) {
	o.Rpc = &v
}

// GetRefresh returns the Refresh field value if set, zero value otherwise.
func (o *WsCommand) GetRefresh() WsRefreshRequest {
	if o == nil || IsNil(o.Refresh) {
		var ret WsRefreshRequest
		return ret
	}
	return *o.Refresh
}

// GetRefreshOk returns a tuple with the Refresh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsCommand) GetRefreshOk() (*WsRefreshRequest, bool) {
	if o == nil || IsNil(o.Refresh) {
		return nil, false
	}
	return o.Refresh, true
}

// HasRefresh returns a boolean if a field has been set.
func (o *WsCommand) HasRefresh() bool {
	if o != nil && !IsNil(o.Refresh) {
		return true
	}

	return false
}

// SetRefresh gets a reference to the given WsRefreshRequest and assigns it to the Refresh field.
func (o *WsCommand) SetRefresh(v WsRefreshRequest) {
	o.Refresh = &v
}

// GetSubRefresh returns the SubRefresh field value if set, zero value otherwise.
func (o *WsCommand) GetSubRefresh() WsSubRefreshRequest {
	if o == nil || IsNil(o.SubRefresh) {
		var ret WsSubRefreshRequest
		return ret
	}
	return *o.SubRefresh
}

// GetSubRefreshOk returns a tuple with the SubRefresh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WsCommand) GetSubRefreshOk() (*WsSubRefreshRequest, bool) {
	if o == nil || IsNil(o.SubRefresh) {
		return nil, false
	}
	return o.SubRefresh, true
}

// HasSubRefresh returns a boolean if a field has been set.
func (o *WsCommand) HasSubRefresh() bool {
	if o != nil && !IsNil(o.SubRefresh) {
		return true
	}

	return false
}

// SetSubRefresh gets a reference to the given WsSubRefreshRequest and assigns it to the SubRefresh field.
func (o *WsCommand) SetSubRefresh(v WsSubRefreshRequest) {
	o.SubRefresh = &v
}

func (o WsCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WsCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Connect) {
		toSerialize["connect"] = o.Connect
	}
	if !IsNil(o.Subscribe) {
		toSerialize["subscribe"] = o.Subscribe
	}
	if !IsNil(o.Unsubscribe) {
		toSerialize["unsubscribe"] = o.Unsubscribe
	}
	if !IsNil(o.Publish) {
		toSerialize["publish"] = o.Publish
	}
	if !IsNil(o.Presence) {
		toSerialize["presence"] = o.Presence
	}
	if !IsNil(o.PresenceStats) {
		toSerialize["presenceStats"] = o.PresenceStats
	}
	if !IsNil(o.History) {
		toSerialize["history"] = o.History
	}
	if !IsNil(o.Ping) {
		toSerialize["ping"] = o.Ping
	}
	if !IsNil(o.Send) {
		toSerialize["send"] = o.Send
	}
	if !IsNil(o.Rpc) {
		toSerialize["rpc"] = o.Rpc
	}
	if !IsNil(o.Refresh) {
		toSerialize["refresh"] = o.Refresh
	}
	if !IsNil(o.SubRefresh) {
		toSerialize["subRefresh"] = o.SubRefresh
	}
	return toSerialize, nil
}

func (o *WsCommand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWsCommand := _WsCommand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWsCommand)

	if err != nil {
		return err
	}

	*o = WsCommand(varWsCommand)

	return err
}

type NullableWsCommand struct {
	value *WsCommand
	isSet bool
}

func (v NullableWsCommand) Get() *WsCommand {
	return v.value
}

func (v *NullableWsCommand) Set(val *WsCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableWsCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableWsCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWsCommand(val *WsCommand) *NullableWsCommand {
	return &NullableWsCommand{value: val, isSet: true}
}

func (v NullableWsCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWsCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


