/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// checks if the FermataCreateDealerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FermataCreateDealerRequest{}

// FermataCreateDealerRequest Create a new dealer in the Fermata venue
type FermataCreateDealerRequest struct {
	// Human-readable dealer name
	Name string `json:"name"`
	// Base currencies the dealer settles in
	BaseCurrencies []string `json:"baseCurrencies"`
	// Positive decimal value as string
	RiskThreshold *string `json:"riskThreshold,omitempty" validate:"regexp=^\\\\d+(\\\\.\\\\d+)?$"`
	// Additional dealer configuration
	Config map[string]interface{} `json:"config,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FermataCreateDealerRequest FermataCreateDealerRequest

// NewFermataCreateDealerRequest instantiates a new FermataCreateDealerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFermataCreateDealerRequest(name string, baseCurrencies []string) *FermataCreateDealerRequest {
	this := FermataCreateDealerRequest{}
	this.Name = name
	this.BaseCurrencies = baseCurrencies
	return &this
}

// NewFermataCreateDealerRequestWithDefaults instantiates a new FermataCreateDealerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFermataCreateDealerRequestWithDefaults() *FermataCreateDealerRequest {
	this := FermataCreateDealerRequest{}
	return &this
}

// GetName returns the Name field value
func (o *FermataCreateDealerRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FermataCreateDealerRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FermataCreateDealerRequest) SetName(v string) {
	o.Name = v
}

// GetBaseCurrencies returns the BaseCurrencies field value
func (o *FermataCreateDealerRequest) GetBaseCurrencies() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.BaseCurrencies
}

// GetBaseCurrenciesOk returns a tuple with the BaseCurrencies field value
// and a boolean to check if the value has been set.
func (o *FermataCreateDealerRequest) GetBaseCurrenciesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseCurrencies, true
}

// SetBaseCurrencies sets field value
func (o *FermataCreateDealerRequest) SetBaseCurrencies(v []string) {
	o.BaseCurrencies = v
}

// GetRiskThreshold returns the RiskThreshold field value if set, zero value otherwise.
func (o *FermataCreateDealerRequest) GetRiskThreshold() string {
	if o == nil || IsNil(o.RiskThreshold) {
		var ret string
		return ret
	}
	return *o.RiskThreshold
}

// GetRiskThresholdOk returns a tuple with the RiskThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FermataCreateDealerRequest) GetRiskThresholdOk() (*string, bool) {
	if o == nil || IsNil(o.RiskThreshold) {
		return nil, false
	}
	return o.RiskThreshold, true
}

// HasRiskThreshold returns a boolean if a field has been set.
func (o *FermataCreateDealerRequest) HasRiskThreshold() bool {
	if o != nil && !IsNil(o.RiskThreshold) {
		return true
	}

	return false
}

// SetRiskThreshold gets a reference to the given string and assigns it to the RiskThreshold field.
func (o *FermataCreateDealerRequest) SetRiskThreshold(v string) {
	o.RiskThreshold = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *FermataCreateDealerRequest) GetConfig() map[string]interface{} {
	if o == nil || IsNil(o.Config) {
		var ret map[string]interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FermataCreateDealerRequest) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *FermataCreateDealerRequest) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]interface{} and assigns it to the Config field.
func (o *FermataCreateDealerRequest) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o FermataCreateDealerRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FermataCreateDealerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["baseCurrencies"] = o.BaseCurrencies
	if !IsNil(o.RiskThreshold) {
		toSerialize["riskThreshold"] = o.RiskThreshold
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FermataCreateDealerRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"baseCurrencies",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFermataCreateDealerRequest := _FermataCreateDealerRequest{}

	err = json.Unmarshal(data, &varFermataCreateDealerRequest)

	if err != nil {
		return err
	}

	*o = FermataCreateDealerRequest(varFermataCreateDealerRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "baseCurrencies")
		delete(additionalProperties, "riskThreshold")
		delete(additionalProperties, "config")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFermataCreateDealerRequest struct {
	value *FermataCreateDealerRequest
	isSet bool
}

func (v NullableFermataCreateDealerRequest) Get() *FermataCreateDealerRequest {
	return v.value
}

func (v *NullableFermataCreateDealerRequest) Set(val *FermataCreateDealerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFermataCreateDealerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFermataCreateDealerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFermataCreateDealerRequest(val *FermataCreateDealerRequest) *NullableFermataCreateDealerRequest {
	return &NullableFermataCreateDealerRequest{value: val, isSet: true}
}

func (v NullableFermataCreateDealerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFermataCreateDealerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


