/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the RpcTradeOrderUpdatedEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpcTradeOrderUpdatedEvent{}

// RpcTradeOrderUpdatedEvent Trade order update event (pushed via WebSocket)
type RpcTradeOrderUpdatedEvent struct {
	Data *RpcTradeOrder `json:"data,omitempty"`
}

// NewRpcTradeOrderUpdatedEvent instantiates a new RpcTradeOrderUpdatedEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpcTradeOrderUpdatedEvent() *RpcTradeOrderUpdatedEvent {
	this := RpcTradeOrderUpdatedEvent{}
	return &this
}

// NewRpcTradeOrderUpdatedEventWithDefaults instantiates a new RpcTradeOrderUpdatedEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpcTradeOrderUpdatedEventWithDefaults() *RpcTradeOrderUpdatedEvent {
	this := RpcTradeOrderUpdatedEvent{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RpcTradeOrderUpdatedEvent) GetData() RpcTradeOrder {
	if o == nil || IsNil(o.Data) {
		var ret RpcTradeOrder
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcTradeOrderUpdatedEvent) GetDataOk() (*RpcTradeOrder, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RpcTradeOrderUpdatedEvent) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given RpcTradeOrder and assigns it to the Data field.
func (o *RpcTradeOrderUpdatedEvent) SetData(v RpcTradeOrder) {
	o.Data = &v
}

func (o RpcTradeOrderUpdatedEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpcTradeOrderUpdatedEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableRpcTradeOrderUpdatedEvent struct {
	value *RpcTradeOrderUpdatedEvent
	isSet bool
}

func (v NullableRpcTradeOrderUpdatedEvent) Get() *RpcTradeOrderUpdatedEvent {
	return v.value
}

func (v *NullableRpcTradeOrderUpdatedEvent) Set(val *RpcTradeOrderUpdatedEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableRpcTradeOrderUpdatedEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableRpcTradeOrderUpdatedEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpcTradeOrderUpdatedEvent(val *RpcTradeOrderUpdatedEvent) *NullableRpcTradeOrderUpdatedEvent {
	return &NullableRpcTradeOrderUpdatedEvent{value: val, isSet: true}
}

func (v NullableRpcTradeOrderUpdatedEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpcTradeOrderUpdatedEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


