/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the RpcOrderBookUpdatedEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpcOrderBookUpdatedEvent{}

// RpcOrderBookUpdatedEvent Order book update event (pushed via WebSocket)
type RpcOrderBookUpdatedEvent struct {
	Data *RpcOrderBook `json:"data,omitempty"`
}

// NewRpcOrderBookUpdatedEvent instantiates a new RpcOrderBookUpdatedEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpcOrderBookUpdatedEvent() *RpcOrderBookUpdatedEvent {
	this := RpcOrderBookUpdatedEvent{}
	return &this
}

// NewRpcOrderBookUpdatedEventWithDefaults instantiates a new RpcOrderBookUpdatedEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpcOrderBookUpdatedEventWithDefaults() *RpcOrderBookUpdatedEvent {
	this := RpcOrderBookUpdatedEvent{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RpcOrderBookUpdatedEvent) GetData() RpcOrderBook {
	if o == nil || IsNil(o.Data) {
		var ret RpcOrderBook
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RpcOrderBookUpdatedEvent) GetDataOk() (*RpcOrderBook, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RpcOrderBookUpdatedEvent) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given RpcOrderBook and assigns it to the Data field.
func (o *RpcOrderBookUpdatedEvent) SetData(v RpcOrderBook) {
	o.Data = &v
}

func (o RpcOrderBookUpdatedEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpcOrderBookUpdatedEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableRpcOrderBookUpdatedEvent struct {
	value *RpcOrderBookUpdatedEvent
	isSet bool
}

func (v NullableRpcOrderBookUpdatedEvent) Get() *RpcOrderBookUpdatedEvent {
	return v.value
}

func (v *NullableRpcOrderBookUpdatedEvent) Set(val *RpcOrderBookUpdatedEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableRpcOrderBookUpdatedEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableRpcOrderBookUpdatedEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpcOrderBookUpdatedEvent(val *RpcOrderBookUpdatedEvent) *NullableRpcOrderBookUpdatedEvent {
	return &NullableRpcOrderBookUpdatedEvent{value: val, isSet: true}
}

func (v NullableRpcOrderBookUpdatedEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpcOrderBookUpdatedEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


