/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RpcSaveInstrumentsParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RpcSaveInstrumentsParams{}

// RpcSaveInstrumentsParams Request to save instruments
type RpcSaveInstrumentsParams struct {
	Instruments []RpcInstrument `json:"instruments"`
}

type _RpcSaveInstrumentsParams RpcSaveInstrumentsParams

// NewRpcSaveInstrumentsParams instantiates a new RpcSaveInstrumentsParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRpcSaveInstrumentsParams(instruments []RpcInstrument) *RpcSaveInstrumentsParams {
	this := RpcSaveInstrumentsParams{}
	this.Instruments = instruments
	return &this
}

// NewRpcSaveInstrumentsParamsWithDefaults instantiates a new RpcSaveInstrumentsParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRpcSaveInstrumentsParamsWithDefaults() *RpcSaveInstrumentsParams {
	this := RpcSaveInstrumentsParams{}
	return &this
}

// GetInstruments returns the Instruments field value
func (o *RpcSaveInstrumentsParams) GetInstruments() []RpcInstrument {
	if o == nil {
		var ret []RpcInstrument
		return ret
	}

	return o.Instruments
}

// GetInstrumentsOk returns a tuple with the Instruments field value
// and a boolean to check if the value has been set.
func (o *RpcSaveInstrumentsParams) GetInstrumentsOk() ([]RpcInstrument, bool) {
	if o == nil {
		return nil, false
	}
	return o.Instruments, true
}

// SetInstruments sets field value
func (o *RpcSaveInstrumentsParams) SetInstruments(v []RpcInstrument) {
	o.Instruments = v
}

func (o RpcSaveInstrumentsParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RpcSaveInstrumentsParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instruments"] = o.Instruments
	return toSerialize, nil
}

func (o *RpcSaveInstrumentsParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instruments",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRpcSaveInstrumentsParams := _RpcSaveInstrumentsParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRpcSaveInstrumentsParams)

	if err != nil {
		return err
	}

	*o = RpcSaveInstrumentsParams(varRpcSaveInstrumentsParams)

	return err
}

type NullableRpcSaveInstrumentsParams struct {
	value *RpcSaveInstrumentsParams
	isSet bool
}

func (v NullableRpcSaveInstrumentsParams) Get() *RpcSaveInstrumentsParams {
	return v.value
}

func (v *NullableRpcSaveInstrumentsParams) Set(val *RpcSaveInstrumentsParams) {
	v.value = val
	v.isSet = true
}

func (v NullableRpcSaveInstrumentsParams) IsSet() bool {
	return v.isSet
}

func (v *NullableRpcSaveInstrumentsParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRpcSaveInstrumentsParams(val *RpcSaveInstrumentsParams) *NullableRpcSaveInstrumentsParams {
	return &NullableRpcSaveInstrumentsParams{value: val, isSet: true}
}

func (v NullableRpcSaveInstrumentsParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRpcSaveInstrumentsParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


