/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// UpdateType How the client should apply the order book payload.  - `SNAPSHOT`: Full state of the book at `timestamp`. Client replaces its local view. - `DIFF`: Incremental change since previous message. Client applies per-level: zero quantity removes the level, non-zero upserts. - `DELTA`: Reconciliation delta against a known reference state (venue-specific semantics — document per-connector). 
type UpdateType string

// List of updateType
const (
	UPDATETYPE_SNAPSHOT UpdateType = "SNAPSHOT"
	UPDATETYPE_DIFF UpdateType = "DIFF"
	UPDATETYPE_DELTA UpdateType = "DELTA"
)

// All allowed values of UpdateType enum
var AllowedUpdateTypeEnumValues = []UpdateType{
	"SNAPSHOT",
	"DIFF",
	"DELTA",
}

func (v *UpdateType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UpdateType(value)
	for _, existing := range AllowedUpdateTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UpdateType", value)
}

// NewUpdateTypeFromValue returns a pointer to a valid UpdateType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUpdateTypeFromValue(v string) (*UpdateType, error) {
	ev := UpdateType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UpdateType: valid values are %v", v, AllowedUpdateTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UpdateType) IsValid() bool {
	for _, existing := range AllowedUpdateTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to updateType value
func (v UpdateType) Ptr() *UpdateType {
	return &v
}

type NullableUpdateType struct {
	value *UpdateType
	isSet bool
}

func (v NullableUpdateType) Get() *UpdateType {
	return v.value
}

func (v *NullableUpdateType) Set(val *UpdateType) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateType) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateType(val *UpdateType) *NullableUpdateType {
	return &NullableUpdateType{value: val, isSet: true}
}

func (v NullableUpdateType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

