/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// CollateralMode Collateral mode - how margin is shared across positions
type CollateralMode string

// List of collateralMode
const (
	COLLATERALMODE_EMPTY CollateralMode = ""
	COLLATERALMODE_CROSS CollateralMode = "CROSS"
	COLLATERALMODE_ISOLATED CollateralMode = "ISOLATED"
)

// All allowed values of CollateralMode enum
var AllowedCollateralModeEnumValues = []CollateralMode{
	"",
	"CROSS",
	"ISOLATED",
}

func (v *CollateralMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CollateralMode(value)
	for _, existing := range AllowedCollateralModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CollateralMode", value)
}

// NewCollateralModeFromValue returns a pointer to a valid CollateralMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCollateralModeFromValue(v string) (*CollateralMode, error) {
	ev := CollateralMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CollateralMode: valid values are %v", v, AllowedCollateralModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CollateralMode) IsValid() bool {
	for _, existing := range AllowedCollateralModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to collateralMode value
func (v CollateralMode) Ptr() *CollateralMode {
	return &v
}

type NullableCollateralMode struct {
	value *CollateralMode
	isSet bool
}

func (v NullableCollateralMode) Get() *CollateralMode {
	return v.value
}

func (v *NullableCollateralMode) Set(val *CollateralMode) {
	v.value = val
	v.isSet = true
}

func (v NullableCollateralMode) IsSet() bool {
	return v.isSet
}

func (v *NullableCollateralMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollateralMode(val *CollateralMode) *NullableCollateralMode {
	return &NullableCollateralMode{value: val, isSet: true}
}

func (v NullableCollateralMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollateralMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

