/*
Algo724 Cadenza Fermata API

OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the AuthUpdateUserRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthUpdateUserRequest{}

// AuthUpdateUserRequest struct for AuthUpdateUserRequest
type AuthUpdateUserRequest struct {
	// New email address
	Email *string `json:"email,omitempty"`
	// New password (minimum 8 characters)
	Password *string `json:"password,omitempty"`
	// User metadata to update
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// NewAuthUpdateUserRequest instantiates a new AuthUpdateUserRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthUpdateUserRequest() *AuthUpdateUserRequest {
	this := AuthUpdateUserRequest{}
	return &this
}

// NewAuthUpdateUserRequestWithDefaults instantiates a new AuthUpdateUserRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthUpdateUserRequestWithDefaults() *AuthUpdateUserRequest {
	this := AuthUpdateUserRequest{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *AuthUpdateUserRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthUpdateUserRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *AuthUpdateUserRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *AuthUpdateUserRequest) SetEmail(v string) {
	o.Email = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *AuthUpdateUserRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthUpdateUserRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *AuthUpdateUserRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *AuthUpdateUserRequest) SetPassword(v string) {
	o.Password = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *AuthUpdateUserRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthUpdateUserRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *AuthUpdateUserRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *AuthUpdateUserRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o AuthUpdateUserRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthUpdateUserRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableAuthUpdateUserRequest struct {
	value *AuthUpdateUserRequest
	isSet bool
}

func (v NullableAuthUpdateUserRequest) Get() *AuthUpdateUserRequest {
	return v.value
}

func (v *NullableAuthUpdateUserRequest) Set(val *AuthUpdateUserRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthUpdateUserRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthUpdateUserRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthUpdateUserRequest(val *AuthUpdateUserRequest) *NullableAuthUpdateUserRequest {
	return &NullableAuthUpdateUserRequest{value: val, isSet: true}
}

func (v NullableAuthUpdateUserRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthUpdateUserRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


